### ISSUE TITLE
Correct Icon not Showing up.

### ISSUE THREAD

**Issue by TerminatorP** [equinusocio/vsc-material-theme#101]
The current version of Material Theme for VS-Code i.e. 1.0.5 does not show correct icon for .babelrc file types. Please Fix Soon!

**Comment by equinusocio** [comment]
Actually is used the json icon. Babelrc is not a json format?

**Comment by TerminatorP** [comment]
Yes, It is in json format but it would better if it showed the "B" symbol like in other file icon packages for vs code.
