### ISSUE TITLE
Current file not getting highlighted background in file explorer

### ISSUE THREAD

**Issue by octref** [equinusocio/vsc-material-theme#102]
This is Nord:

![image](https://user-images.githubusercontent.com/4033249/31730357-8b243ac4-b3e6-11e7-80a3-72d927374dba.png)

Dark+:

![image](https://user-images.githubusercontent.com/4033249/31730377-98779c34-b3e6-11e7-857e-c4349d4c62d5.png)

Material:

![image](https://user-images.githubusercontent.com/4033249/31730400-a60608cc-b3e6-11e7-9f60-d128796402ce.png)

It's much harder for me to track down the current file in the file explorer when using Material.

**Comment by equinusocio** [comment]
This is Material Theme. If you want to add the highlight you can do it with the custom workbench settings in your settings file.

**Comment by octref** [comment]
The thing is there are upcoming changes to the colors on File Explorer:

Modified and all opened files will be colored using foreground.
In this case, the currently focused file will be much harder to scan for.
I hope this decision can be revisited.

![image](https://user-images.githubusercontent.com/4033249/31731560-4d14496e-b3ea-11e7-9ca7-671de3df01d4.png)
