### ISSUE TITLE
Is it possible to change the colors of whitespaces?

### ISSUE THREAD

**Issue by devjb** [equinusocio/vsc-material-theme#104]
When I toggle the whitespace rendering in vscode while using the Material theme, those dots that are rendered are hardly visible. Could I change the greyish color of those whitespace dots to a grey which gives more contrast to the background?

**Comment by devjb** [comment]
Ok got it, there is a global color setting in vscode, that I found in one of the issues here

**Comment by D4NH** [comment]
For easier reference:
```
    "workbench.colorCustomizations": {
        "editorWhitespace.foreground": ""
     }
```
