### ISSUE TITLE
Is it possible to disable git gutter indicators?

### ISSUE THREAD

**Issue by andresg747** [equinusocio/vsc-material-theme#105]
Hi,

A recent update now opens the gutter indicators automatically when I try to fold / unfold code.
This surely is unwanted / strange behavior. 

I would like either to disable gutter indicators, because I don't even use it, or please review this if it can be solved.

Demo:
https://drive.google.com/file/d/0B_RhxVkVWH2VWTNFODgxeTk3Vzg/view?usp=drivesdk

Thanks!

**Comment by equinusocio** [comment]
Hi, this is not related to the theme. You should report this issue to @microsoft/vscode repo
