### ISSUE TITLE
Color scheme NEW vs OLD

### ISSUE THREAD

**Issue by TonyRocket** [equinusocio/vsc-material-theme#109]
Hello,
the new color scheme (RGB: 38,50,56 | HEX: #263238) after the last update is worse than the previous one and uncomfortable for eyes. Btw, how can I switch theme to Darker version thru settings? For now, I just replace content of Material-Theme-Default.json file with content from Material-Theme-Darker.json file.

**Comment by equinusocio** [comment]
wut?

**Comment by TonyRocket** [comment]
Which settings allows to choose Material-Theme-Darker? Since Material-Theme-Default after the last update is negatively perceived by my eyes (quickly get tired of low contrast).

**Comment by equinusocio** [comment]
Material Theme Default was not changed. We added 3 new theme variants that you can activate as always from the command palette. Please read this section:
https://github.com/equinusocio/vsc-material-theme#activate-theme

**Comment by acomito** [comment]
@equinusocio, thanks for porting this for vscode. I use it on sublime and love it. I'm having trouble finding how to get the dark theme. I read a few issues on it and also the readme, but I'm not seeing "Material Theme: Settings" option anywhere. I can select material theme from _Code > Preferences > Color Theme_, but I dont see any settings for material theme anywhere

**Comment by equinusocio** [comment]
After activating, open the command palette e search `material theme`

**Comment by equinusocio** [comment]
and don’t forget to activate the material theme icons set
