### ISSUE TITLE
Separate texteditor theme <-> the editor program

### ISSUE THREAD

**Issue by BenjaVR** [equinusocio/vsc-material-theme#111]
Would it be possible to be able to customize the texteditor (where you type your code) and the editor (vscode) separately? E.g. the default theme for the texteditor, and the darker theme for the rest of vscode. An example from my Jetbrains IDE:

![image](https://user-images.githubusercontent.com/17981138/32637765-540e25f2-c581-11e7-9557-3fd743254a53.png)

One and two are both different themes, but combined.

**Comment by equinusocio** [comment]
There is an open issue on vscode repository but atm is not possible
