### ISSUE TITLE
Show accent color for versioned selected items

### ISSUE THREAD

**Issue by dalemanthei** [equinusocio/vsc-material-theme#112]
My installation of Visual Studio Code updated today and with the enhancements that came with it, the accent color setting seems to work a little different.

If the file is selected and focused in the explorer, the accent color is applied in all cases. If the file is not updated or modified, the accent color is applied.

However, if the file has the new github indicators applied, the accent color is applied until the file is opened in the editor. so the two files shown below do not get the accent color applied when they are opened in an editor:

![data-table-example-dynamic_html_ _vdl-angular](https://user-images.githubusercontent.com/6266984/32685436-e1bb5174-c656-11e7-9701-623e0ef63e34.png)

**Comment by equinusocio** [comment]
HHi @dalemanthei, i think you should report this behavior to the vscode team -> https://github.com/microsoft/vscode/issues

**Comment by dalemanthei** [comment]
I'll check if someone's already reported and point them back here if not.

**Comment by equinusocio** [comment]
@dalemanthei If you report the issue please add reference to this one 👍

**Comment by equinusocio** [comment]
I close this for now.
