### ISSUE TITLE
Laravel Blade file icon is missing

### ISSUE THREAD

**Issue by kennith** [equinusocio/vsc-material-theme#114]
The .blade.php icon renders the PHP icon in VS code with (vsc-material-theme + material theme icon)
![image](https://user-images.githubusercontent.com/871161/32794527-fcf0592a-c91d-11e7-9a1d-09235a89f69d.png)

In Sublime Text, .blade.php renders with the Laravel icon (material-theme + a file icon)
![image](https://user-images.githubusercontent.com/871161/32794589-1aa94418-c91e-11e7-8c30-ac951467542b.png)

I am not sure if this is by design, but I just report it anyway. Thanks for the great work, by the way. I really like material-theme.

**Comment by equinusocio** [comment]
Hi @kennith. `.blade.php` is the file format for all laravel files? I can set the laravel icon by associating the exact file name (`.blade.php`), otherwise the laravel extension should set the correct icon. If the is not the extension that handle laravel files, the `.php` extension shows the php icon.

**Comment by kennith** [comment]
@equinusocio Laravel itself is a PHP framework. [Blade](https://laravel.com/docs/5.5/blade#introduction) is the templating engine provided with Laravel. 

I think only associate .blade.php with the Laravel icon is good.

**Comment by pwsandoval** [comment]
This is fix?

**Comment by equinusocio** [comment]
Not yet. It is a quick fix but i can't release a patch update only with this commit :)

**Comment by sharabindu** [comment]
Just install laravel Blade highlighter from package control, the Blade icon will be changed automatically
