### ISSUE TITLE
 How can deactivate the italic font?

### ISSUE THREAD

**Issue by carlosjfernandes** [equinusocio/vsc-material-theme#117]
I'm programming with PHP and some reserved language words italicize them. How can I deactivate that?

**Comment by equinusocio** [comment]
Atm you can't. The italic setting is hardcoded and it can't be exposed. We need some work to make scheme settings "flaggable" by the user. @OctoD What do you think?

**Comment by Zx-EvM** [comment]
Related Issue: https://github.com/Microsoft/vscode/issues/32579

Problem solved in this message: https://github.com/Microsoft/vscode/issues/32579#issuecomment-341502559

**Comment by OctoD** [comment]
I think it could be done programmatically with a command which sets the user settings referred by @Zx-EvM , so if everything would work, we could include it as a toggle command (on/off).
