### ISSUE TITLE
Theme Rendering White Text Instead of Traditional Gray

### ISSUE THREAD

**Issue by slamflipstrom** [equinusocio/vsc-material-theme#120]
A recent update has caused the VS Code theme (the Palenight variant) to render white text in the editor instead of the standard gray. Any advice on reverting it back to its normal state?

![image](https://user-images.githubusercontent.com/8062052/34213755-594b81a8-e55d-11e7-95b6-d65f993d715e.png)

**Comment by equinusocio** [comment]
Can you paste your vscode version, build and OS? I can't reproduce this issue on latest VS Code Insiders 1.20 and public VS Code

**Comment by slamflipstrom** [comment]
I'm on Code version 1.19.0 on Mac OS High Sierra (10.13.2).

**Comment by slamflipstrom** [comment]
Here are the extensions I'm currently using:

<img width="501" alt="screen shot 2017-12-20 at 9 20 14 am" src="https://user-images.githubusercontent.com/8062052/34216933-0cc309e6-e567-11e7-996d-c3f88111f562.png">

<img width="499" alt="screen shot 2017-12-20 at 9 18 28 am" src="https://user-images.githubusercontent.com/8062052/34216901-ef8f9bbe-e566-11e7-9e88-838230ad8047.png">

**Comment by equinusocio** [comment]
You are not using vsc-material-theme. You are using Material Palenight Theme that is a clone and bugged (i asked author to remove it) version of the original material theme. I can't help you about other themes. You can use the [original Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) and check again this issue.

**Comment by slamflipstrom** [comment]
Ahh yeah, I was using the wrong theme 🤦‍♂️ . VS Code should indicate which theme you have enabled in the Extensions bar to avoid that confusion. Thanks for your help!
