### ISSUE TITLE
Add support for Zephir files

### ISSUE THREAD

**Issue by sergeyklay** [equinusocio/vsc-material-theme#124]
VSCode Plugin page: https://marketplace.visualstudio.com/items?itemName=zephir-lang.zephir

Logos:
![i_serghei01_orig](https://user-images.githubusercontent.com/1256298/34519498-00b87560-f08d-11e7-9716-c8426d256255.png)
![i_serghei02_orig](https://user-images.githubusercontent.com/1256298/34519499-00da239a-f08d-11e7-9dbc-1c22512b4f2d.png)

Source attached  

[zephir-logos-src.zip](https://github.com/equinusocio/vsc-material-theme/files/1600203/zephir-logos-src.zip)

**Comment by equinusocio** [comment]
@sergeyklay What is the zephyr file extension?

**Comment by sergeyklay** [comment]
@equinusocio **`*.zep`**

**Comment by sergeyklay** [comment]
@equinusocio Just attached logos and source (AI)

**Comment by equinusocio** [comment]
Thank you.
