### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jabacchetta** [equinusocio/vsc-material-theme#125]
First, thanks for the great theme!

I'm going to drop a few screenshots here with some suggestions. I know design (especially in code editors) is highly subjective, so feel free to close this completely, run with some of the ideas, or request a PR — which I'd be glad to help with when I have some free time.

My custom settings can be [found here](https://gist.github.com/jabacchetta/671c45a2688859e39d3e62a6b0e11745).

Personally I found the "Default High Contrast" theme to be a bit too distracting, with not enough separation between the different layers. Notably, I:

- added a third color (to sidebar and terminal) to contrast those with not only the editor, but the activity and status bars

- lightened up the scroll bar, the highlighted line, and the matching bracket colors (making those less distracting while coding)

- matched the color of the ruler (showing my max line length) to the indent guides

- changed up the editor tabs a bit

<img width="1280" alt="tools" src="https://user-images.githubusercontent.com/12591890/34475511-6743f4bc-ef52-11e7-9e5c-112d69ef6492.png">

<img width="1280" alt="minimal" src="https://user-images.githubusercontent.com/12591890/34475512-6a023e98-ef52-11e7-87c8-630cf1ce543f.png">

**Comment by Zx-EvM** [comment]
Hi @jabacchetta. How did you make the theme look like this?

I created screenshot with arrows pointing things that are different from yours screenshots:

![02-01-2018 08-17-38](https://user-images.githubusercontent.com/20873402/34490771-c4dfc018-ef95-11e7-8869-cc85c03dd279.png)

I use vsc-material-theme 1.2.0.

**Comment by equinusocio** [comment]
@Zx-EvM 
```json
"workbench.colorCustomizations": {
        "activityBarBadge.background": "#80CBC4",
        "list.activeSelectionForeground": "#80CBC4",
        "list.inactiveSelectionForeground": "#80CBC4",
        "list.highlightForeground": "#80CBC4",
        "scrollbarSlider.activeBackground": "#80CBC450",
        "editorSuggestWidget.highlightForeground": "#80CBC4",
        "textLink.foreground": "#80CBC4",
        "progressBar.background": "#80CBC4",
        "pickerGroup.foreground": "#80CBC4",
        "tab.activeBorder": "#263238",
        "scrollbar.shadow": "#070a0c",
        "scrollbarSlider.background": "#37474F80",
        "editorBracketMatch.background": "#46535B",
        "editorBracketMatch.border": "#46535B",
        "editor.lineHighlightBackground": "#37474F80",
        "editorRuler.foreground": "#37474F80",
        "editorGroupHeader.tabsBackground": "#202A30",
        "tab.inactiveBackground": "#202A30",
        "tab.border": "#263238",
        "sideBar.background": "#202A30",
        "sideBarSectionHeader.background": "#202A30", 
        "terminal.background": "#202A30",
        "panel.background": "#202A30",
        "panelTitle.activeBorder": "#263238",
    },
```

**Comment by equinusocio** [comment]
@jabacchetta The contrast mod is made for users that need more contrast (and obviously will get more distractions). If you want less distraction, consider to use the non-hc variants. About other things, the tabs underline is a key element to recognise this theme. Active scrollbars color is handled by the current accent color and i can't change the opacity, some colors are more contrasted than others. For the line highlight you used the same color of the default (not hc) variant.

Thank you for your effort, but consider to use the default variants. **I just fixed the ruler color.**

**Comment by teohhanhui** [comment]
In `Material Theme Darker`, the scroll bar handle is almost invisible. Even using `Material Theme Darker High Contrast` does not help much. I think the scroll bar should just be a solid colour. (Black?)
