### ISSUE TITLE
Reason file support

### ISSUE THREAD

**Issue by futantan** [equinusocio/vsc-material-theme#126]
Hi there, thanks for this amazing theme, I am using this a lot in my work and it's the best theme choice.

I'm trying to write some [Reason](https://reasonml.github.io/) code, but it seems strange.
![image](https://user-images.githubusercontent.com/6268441/34476255-216a072e-efca-11e7-85bd-71650a0913a5.png)

The pipeline symbol `|` and semicolon are italic. 
I try to switch to other themes, it doesn't have this problem. I tried to find some config in my setting files but found nothing.

Hope you guys have some suggestion on this.

Thanks!

**Comment by equinusocio** [comment]
Hi @futantan, in material theme `keyword.controls` and `keyword.operators` are italic. If you don't like it you can override this syntax configuration, just add this to your config file:

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [ "keyword.control"],
                "settings": {
                  "fontStyle": "normal"
                }
            }
        ]
 }
```

**Comment by futantan** [comment]
It works fine! Thanks a lot!
