### ISSUE TITLE
Peek Definition

### ISSUE THREAD

**Issue by richardfeliciano** [equinusocio/vsc-material-theme#129]
<img width="1181" alt="screen shot 2018-01-06 at 11 15 41" src="https://user-images.githubusercontent.com/3297184/34640086-5c386f74-f2d3-11e7-939e-3e5912c7c9de.png">
When we choose "Peek Definition" on context menu, the code is not readable, because an orange color that sorrounds the code like an selection, it will be nice change to a more readable way.

**Comment by equinusocio** [comment]
Just a reminder for me.
`peekViewResult.matchHighlightBackground` and `peekViewEditor.matchHighlightBackground`

If you want, you can fix this by adding these rules to `workbench.colorCustomizations` setting.

**Comment by equinusocio** [comment]
Fixed by https://github.com/equinusocio/vsc-material-theme/commit/b66e88e1db711db22121c5bfbd769a8c622592ab
