### ISSUE TITLE
Improve theme builder

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme#13]
The builder should start from a `yaml` template (the theme template with color placeholders inside) and for each theme variant (json files with defined colors) output "bundled" themes files

- Material-Theme-Default.json
- Material-Theme-Darker.json
- Material-Theme-Lighter.json
- Material-Theme-Palenight.json

Since i'm using Gulp for other tasks i need to make the builder on Gulp, using gulp-data and gulp-template.
@balanceiskey is working on it, maybe you can help :) If you want, you can join the conversation on Gitter here https://gitter.im/original-material-theme/visual-studio-code?utm_source=share-link&utm_medium=link&utm_campaign=share-link

This the scheme draft, and is similar to the one used for generating the icons theme

![theme-builder](https://cloud.githubusercontent.com/assets/10454741/24707190/f510c9f2-1a12-11e7-834b-3adcaa0e40a8.jpg)

@skbolton A custom panel for choosing accent colors is not a bad idea, but at the moment i don't have idea how to apply

**Comment by skbolton** [comment]
What are your end goals with this? Is this like the modals in sublime text where you could customize the accent colors and configuration?

**Comment by equinusocio** [comment]
no, the build should start from a `yaml` template (the theme template with color placeholders inside) and for each theme variant (a json files with defined colors) output themes files

- Material-Theme-Default.json
- Material-Theme-Darker.json
- Material-Theme-Lighter.json
- Material-Theme-Palenight.json

**Comment by skbolton** [comment]
I would love help out. I have been rocking your material themes on every editor and would love to give back. I will have to be more of a weekend warrior, but I will step in on the chat towards the weekend and see if I can be of service!

**Comment by equinusocio** [comment]
I just updated the first comment.

**Comment by balanceiskey** [comment]
Hi @skbolton and @equinusocio! I've got a first pass brewing here: https://github.com/balanceiskey/vsc-material-theme/tree/template-gen

Diff here: 
https://github.com/equinusocio/vsc-material-theme/compare/develop...balanceiskey:template-gen

You should be able to run `gulp build:themes` to actually build the themes (be sure to `yarn` or `npm install` first). A couple notes:

* I didn't use `gulp-template` and `gulp-data` and instead used `mustache` for the templating. There may be downsides to this, I'm unsure. The mental model was a little easier for me to hold in my head of what was actually going on.
* Because it's using mustache, it's also using mustache's default for templates vars: `{{}}`. That can be swapped though if the Ruby-style `<% %>` delimiters are preferable.
* Right now the files are building directly into the `themes` directory but in the long-run I don't think these things should be included in version control and should instead produce a separate `dist/` folder which is what is eventually shipped. This should include icons and anything else as well.

**Comment by equinusocio** [comment]
@balanceiskey If you want to use `mustache`, you can replace `gulp-template` and `gulp-data` as well for the `icons` task? Just to have a consistent codebase. You can also use `paths.js` instead to hardcode paths :) and if you need you can extend/improve it.

I just update variants schemas, this is the model for each theme variant:
```json
{
  "id": "material.theme.lighter",
  "name": "Material-Theme-Lighter",
  "scheme": {
    "background": "#fafafa",
    "comments": "#CCD7DA",
    "caret": "#27272790",
    "findHighlight": "#F8E71C",
    "foreground": "#80CBC4",
    "guides": "#B0BEC570",
    "activeGuide": "#00000070",
    "stackGuides": "#B0BEC580",
    "gutter": "#CFD8DC",
    "invisibles": "#E7EAEC",
    "highlight": "#90A4AE20",
    "selection": "#80CBC440",
    "shadow": "#90A4AE50",
    "keywords": "#AAB3B5",
    "constant": "#80CBC4",
    "string": "#F9355A",
    "constantEscape": "#FFC400",
    "base": {
      "white": "#ffffff",
      "black": "#000000",
      "red": "#E53935",
      "orange": "#F76D47",
      "yellow": "#FFB62C",
      "green": "#91B859",
      "cyan": "#39ADB5",
      "blue": "#6182B8",
      "paleblue": "#8796B0",
      "purple": "#7C4DFF",
      "brown": "#C17E70",
      "pink": "#FF5370",
      "violet": "#945EB8"
    }
  }
}
```
so we can start using eg `scheme.background` and `scheme.base.cyan`

**Comment by skbolton** [comment]
I think it would be a better option to stick with gulp-template and gulp-data since thats whats in place already. Plus it fits in with other tasks and things with the project.

**Comment by equinusocio** [comment]
@skbolton @balanceiskey Can you investigate about the builder? i'm updated the theme template (and changed the themes output folder) and now i get this error when building:

```
Error: <ParseException> You cannot define a mapping item when in a sequence
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/index.js:264:8)
    at /Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/index.js:275:23
    at finish (/Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/equinusocio/Repositories/Private/vsc-material-theme/node_modules/orchestrator/index.js:214:10)
```
