### ISSUE TITLE
Sidebar font color is too fade in Darker theme

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [equinusocio/vsc-material-theme#131]
Hi, current sidebar color is too fade. Especially in Darker theme. When recognizing all the file names is hard enough, recognizing VS Code git coloring is even harder.    
There is another circumstance when such fade grey color hard to be seen is when PC turns on night light, which has been a useful feature in both Windows 10 and Linux. This is really really hard to read in the sidebar when my night light turned on. Please take this into consideration.

**Comment by equinusocio** [comment]
This is just a personal preference. You can easily fix that by adding the `sideBar.foreground` setting to your `workbench.colorCustomizations` object.
