### ISSUE TITLE
Make active file recognizable in explore section. It's impossible to see which file is open!

### ISSUE THREAD

**Issue by Jensen0710** [equinusocio/vsc-material-theme#132]
Make active file recognizable in explore section. It's impossible to see which file is open!
<img width="241" alt="screen shot 2018-01-11 at 10 33 00" src="https://user-images.githubusercontent.com/9888000/34818453-1cee7d7c-f6bb-11e7-9928-dfaa615b6e67.png">
<img width="224" alt="screen shot 2018-01-11 at 10 33 27" src="https://user-images.githubusercontent.com/9888000/34818454-1d1ddc48-f6bb-11e7-8b0a-ce7f1ab8f3f4.png">

**Comment by equinusocio** [comment]
A quick fix can be adding `"list.inactiveSelectionBackground": "#FFFFFF10"` to your `workbench.colorCustomizations` config

**Comment by Zx-EvM** [comment]
This issue presents when `"git.decorations.enabled"` set to `true`

**Comment by equinusocio** [comment]
@Zx-EvM Yes because the vsc git status decoration have a high priority over the custom `list.inactiveSelectionForeground`. I can't force it but i can only set the background color, that i don't like very much..

**Comment by Zx-EvM** [comment]
@equinusocio https://github.com/Microsoft/vscode/issues/41643

**Comment by Zx-EvM** [comment]
@equinusocio it's possible to customize colors to `M` and `U` decorators/symbols separately?

**Comment by equinusocio** [comment]
@Zx-EvM No, we can just set the git file changed foreground.
<img width="427" alt="screen shot 2018-01-16 at 15 05 43" src="https://user-images.githubusercontent.com/10454741/34992865-d62e69fc-face-11e7-979a-32f139bca840.png">

**Comment by Jensen0710** [comment]
@equinusocio are you working on an update?

**Comment by Zx-EvM** [comment]
@equinusocio I think I asked not correctly. I told about to make the color for `list.inactiveSelectionForeground` and for `M` (and `U`) decorators different at the same time when the file is selected. Is it possible?

**Comment by equinusocio** [comment]
@Zx-EvM Is not possible. `list.inactiveSelectionForeground` is applied to the entire row and is overwritten by `gitDecoration.*` that also are applied to the entire row.

**Comment by Zx-EvM** [comment]
@equinusocio `and set the background`. I don't like this idea too :) (only if temporarily until bug fix).

BTW, in issue added `bug` tag now.
