### ISSUE TITLE
High contrast theme - difficult to read commented code

### ISSUE THREAD

**Issue by drawcard** [equinusocio/vsc-material-theme#134]
Referencing #7 and #11 

When using "Darker High Contrast", the colour settings for comments are anything but high contrast :smile: For poor vision users (like myself) it's quite impossible to read paragraphs of text set in this colour even in large text sizes.

I'm aware that I can set my own colours locally, but apparently those settings [get erased](https://github.com/equinusocio/vsc-material-theme/issues/7#issuecomment-280865524) every time a new version of the theme is installed.

Please consider adding a lighter tint of grey to the High Contrast versions of the theme, and conversely, darker tints for the Light theme. I love using Material Theme and think it's the best one out there for VSCode, and it would truly suck having to switch to something else.

![image](https://user-images.githubusercontent.com/1435638/35181076-155d799e-fe0b-11e7-8952-6c4990d1f194.png)

![image](https://user-images.githubusercontent.com/1435638/35181093-6cbf4c6c-fe0b-11e7-8564-857c93b8d225.png)

**Comment by equinusocio** [comment]
Hi, @drawcard High Contrast variant refer to the UI theme, not the code colors. At the moment we have no time to redesign the high contrast version for all the color schemes.

**Comment by drawcard** [comment]
That's a shame. Otherwise it's a really useful theme.

Would you accept a PR if myself or someone else looked into it?

**Comment by equinusocio** [comment]
Is a shame that people ask for more features from open source projects and then tell "that is a shame". I'm the only one contributor to this project, and since is a free non-commercial open source project, my time is dedicated to other projects. I'm open to PR but i need to review colors changes/improvements.

**Comment by drawcard** [comment]
Sorry, didn't mean to make it sound like a personal attack - I definitely appreciate the time and effort you've put into creating this theme, and I'd be interested in looking into this issue to enhance the theme for everyone. I'll fork it and see what can be done.

**Comment by equinusocio** [comment]
@drawcard If you want to collaborate you need to set up the GPG enviroment and install git-crypt, then generate/share your public key before you can start to develop.

**Comment by drawcard** [comment]
No worries, I wondered why some files were binary :) I haven't used GPG before but I'll set that up. Will be in touch with my public key shortly.

**Comment by drawcard** [comment]
Here's my public key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFpmdisBCAC+HuyDltiaN3xC7gccEIXPUTAy6SrNqAti7TLA8jY/rk4Wczu/
ynWH2rYGzzjXtn33Dglt8VC83DPa51leLSrfriApEhee1Tlg+1d0vC19ZOF6ZU2n
Ectp02/LW3B85oceyNL1vf9+5GpWG1QHfj2Eijn+DkAn5X/Xg9KSTWwflU0FClKA
ymZ64hNN9anXISN3Z1WzNBjHUJPj/lF4VZbMhdo5qFcNUkab2VoHwLKVURilF9s7
u3IKvEnC6c7r/D1k6mQJu917SmnQXLwI5lFYBYiTOVh/6pfHopu4YD17smd3t/lM
C36tFyWP64VT/kT5cuHX9Xm7VuuYOYZJ1odjABEBAAG0I0RyYXdjYXJkIDxjcmVh
dGl2ZUBkcmF3Y2FyZC5jb20uYXU+iQFbBBMBCABFAhsDBQkDwmcAAh4BAheAFiEE
B/D65hUi68UvnKAne1qx8vc1a1MFAlpmd8YKCwkNCAwHCwoDAgcVCgkICwIDBRYC
AwEAAAoJEHtasfL3NWtTASsH/3X6l5DtbRSX6HJGheoCMjctv188GAcJS6xieJtW
XIgRQV9WeIfkvMBoCnkYSMIUbTCtEc3+pk9UohcExaLGd400onF54cyFRxNel2TJ
5JhIhnijJtRVhIIA4a1kk/OeTsbrb2zHr0hyV2wiSzt/pm6W0F98FtLCdnoRNacb
wQ4CEtJbj+n5+9yKATPSx97YrVBKDjlyUbtOt9f4eQel8EXWiPbUd0Gcr5C5epvk
1lEVkI1VcCQ3Y1KtCp2AdW3Do08kN4WgrE/hutSoaweCTr0fxl4BBbC4hDKkGeFk
wZN5xAjVa7GT4PWk3ITSWK8Ls0L/wZbg8QBwhdsUlG/W9my5AQ0EWmZ2KwEIALZI
NJOwuiTKCU9S5BwozAaQCTWZq0EpQ7RNb7zYNrs7s14kL7Xri735EcTd/OvVjVx4
l4yZwQbV64wVGcA9orHhA84bOtrjgU2grZ3DGIBsKFkGpJbnf4BX9SiYo4n6PSz6
fUQvUWNMlaEbHKTJNF3+P6u15xJfpPTiBxb27QWKG0OK5ojjAWu45LiSKwo9Assy
0l/zGc1bzQkUVZdhZb3jLZupDNeW1dIrM2xUa/PZcXxlr8/F/stmB5I0MvKs0ebm
0Xvw0A9TMecYDhHPfENxljzIeXZ6ET0U5X067H0x6z0UbrD8VdOfogPlKRoCNx2g
S67tfBdVgV2bFYUdZJUAEQEAAYkBPAQYAQgAJhYhBAfw+uYVIuvFL5ygJ3tasfL3
NWtTBQJaZnYrAhsMBQkDwmcAAAoJEHtasfL3NWtTwfQIALulH0+LPecCPLqxjKYe
2v9/iQrLDoD+Vx3klcmM5KTRPuLtE3FnzzF/piC9as7pZhaGdjPAvDMpcULIzrbQ
6q24MHViUVNQ33WQTSgLHVP1eXiCGZ74EajfyeTwnah4W3ozn7BV/xTEl9l3Z892
Of1NMpNqt3GRC+CREVdhm10GijWb0HX4KY+WGP2JclG2atevZ7EUYRRe6jptagTc
Ax0L5ATv0E6CD2FcBP7z/OpK2LK84+WFLYaY0do75gABZlOnnvIVQk5N3VHXud0o
H83DznnOzgb6bbJr6349qKPixp73zyeXUIQYzNcX4srRxGC4ODu9FiBUtAtDmmu0
ZBU=
=JtDQ
-----END PGP PUBLIC KEY BLOCK-----

**Comment by equinusocio** [comment]
@drawcard Hi, i need the gpg file :)
