### ISSUE TITLE
Add more italic

### ISSUE THREAD

**Issue by lednhatkhanh** [equinusocio/vsc-material-theme#136]
Hello, currently I'm using Operator Mono so I really really want to have to italic character in this theme, can we have an italic version for this? Thank you.

**Comment by sladiri** [comment]
There is a fork that seems to do just this, I did have to add some keywords to be italised:
https://github.com/faultless/vsc-material-theme
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Attributes",
        "scope": "entity.other.attribute-name",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "name": "ES6 Modules",
        "scope": "keyword.operator.module.js",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "name": "ES6 Classes",
        "scope": "entity.name.class.js",
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  },
```

**Comment by equinusocio** [comment]
Please be more specific. Actually the theme aready have support for italic.

![screen shot 2018-01-29 at 12 08 36](https://user-images.githubusercontent.com/10454741/35507496-3e573ea0-04ed-11e8-8979-79c936123785.png)

![screen shot 2018-01-29 at 12 09 14](https://user-images.githubusercontent.com/10454741/35507497-3fe989a8-04ed-11e8-8334-1bbf0e79346a.png)

![screen shot 2018-01-29 at 12 10 03](https://user-images.githubusercontent.com/10454741/35507539-5dae5608-04ed-11e8-84a0-fe9bb762f810.png)

**Comment by lednhatkhanh** [comment]
It turns out to be that I added some configs that overrides the italic setting of this theme, gonna close this now.
