### ISSUE TITLE
Add shadows to file explorer, terminal, and other panels

### ISSUE THREAD

**Issue by ddobson** [equinusocio/vsc-material-theme#137]
When trying adjust the width of a panel such as the file explorer or terminal, it can be very difficult to figure out where the panel starts/ends. This makes it tough to know where to place your cursor so you can click and drag the panel to a different size. Consider adding an option that would enable some shadow on these panels to make it easier to find their edges.

![screenshot 2018-02-08 10 52 28](https://user-images.githubusercontent.com/7988792/35992223-8b77b20e-0cbe-11e8-9e52-1c4a7a6c184c.png)

**Comment by equinusocio** [comment]
This is a material theme killer feature, providing a full immersive workspace with no distractions, separators or other UI elements that breaks the unified experience. You can use the HC contrast version to have more distinction between the panels.

**Comment by odyright** [comment]
i desagree beccause Mat Design is built on top of elevation and shadow, and it would be good if we can use it to distinguish panels!

**Comment by equinusocio** [comment]
Use the high contrast variant. It is not possible to set shadow.
