### ISSUE TITLE
Add a note at the top of the changelog indicating which project it's for.

### ISSUE THREAD

**Issue by cdfuller** [equinusocio/vsc-material-theme#139]
When I opened vscode the changelog opened up since it updated, but I had no immediate way of knowing what it was for. It might be a good idea to put the project name in there.

![image](https://user-images.githubusercontent.com/2310581/36408198-a1ad2d4c-15c9-11e8-881b-6f2d8d48eefb.png)

**Comment by equinusocio** [comment]
Hi, i also think that it would useful but i need help on this because i don’t have any support on the typescript code and i’m not a js/ts developer.

**Comment by cdfuller** [comment]
I've looked into `standard-release` package that is being used and there doesn't appear to be any command line options to set a title in this file.

https://github.com/conventional-changelog/standard-version/blob/master/command.js

Looking at the package that they are using underneath, it looks like there must be some way to set the title when looking at the header file.
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/templates/header.hbs

**Comment by equinusocio** [comment]
I thinkwe could set the tab name throught the VSC api or run a post release script that add the title at the top of the changelog.
