### ISSUE TITLE
Make Material Theme stickers

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme#14]
Make Material Theme sticker due 16/04
https://dribbble.com/shots/3413607-Free-Custom-Labels-Giveaway?utm_source=Dribbble&utm_campaign=71512bfa5d-Dribbble_LabelsGiveaway&utm_medium=email&utm_term=0_8787544c2d-71512bfa5d-417287869&mc_cid=71512bfa5d&mc_eid=89f46fbab2

**Comment by equinusocio** [comment]
**V1**
![v1](https://cloud.githubusercontent.com/assets/10454741/24767952/35b3242a-1b01-11e7-9f53-3747a883fcad.jpg)

**Comment by equinusocio** [comment]
**V2**
![v2](https://cloud.githubusercontent.com/assets/10454741/24767953/35b4483c-1b01-11e7-9fa1-501534521bd3.jpg)

**Comment by skbolton** [comment]
I really like the font! I do wonder though if the heart could look a little more materialy for homage sake?

**Comment by equinusocio** [comment]
Updated.

**Comment by equinusocio** [comment]
I like the V1 :)
