### ISSUE TITLE
Subtle highlight on tab hover does not work

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#141]
Or maybe I don't understand something.

Gif:

![hover-mt](https://user-images.githubusercontent.com/20873402/36678497-aeae13e2-1b5c-11e8-8674-1f76762c8790.gif)

Material Theme 1.4.2 (by the way, why 1.4.2 when on changelog 1.4.0?)

![16](https://user-images.githubusercontent.com/20873402/36679870-09cf2ff6-1b60-11e8-9037-2ee794a3d77e.png)

VSCode:

```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Also I noticed you added `tab.unfocusedActiveBorder` https://github.com/equinusocio/vsc-material-theme/commit/a5a392ac08310c1552935c2f2589d4e9f138c32b color but this doesn't work too (as you can see on gif or read first line of my issue 😀 )

**Comment by equinusocio** [comment]
I noticed that on the default variant the tab hover background is to much subtle :D

**Comment by Zx-EvM** [comment]
@equinusocio I can not see it :) It's possible to fix that?

**Comment by equinusocio** [comment]
@Zx-EvM This feature is completely removed in the next release. It will be released in the future only for HC variants.
