### ISSUE TITLE
How to disable highlighting of line number on active line?

### ISSUE THREAD

**Issue by AriaMinaei** [equinusocio/vsc-material-theme#142]
The change that seems to be introduced on cf69a74e4933f8952d8f70e07da6f535a821e559 gives a bright color to the line number on the active line. It is obtrusive imo as it looks like normal code and so directs the eye to the wrong place.

![image](https://user-images.githubusercontent.com/593118/37241867-7d08d81a-2460-11e8-9b90-58d7bbb4fcae.png)

It would be good if the color of the highlight wasn't so bright, and there was an option to disable it.

**Comment by equinusocio** [comment]
Unfortunately i can't make it behind a flag. I will change the color

**Comment by AriaMinaei** [comment]
The new color is perfect! Thank you :)
