### ISSUE TITLE
Notification color

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#143]
color variant: default (might looks a little warmer because of f.lux)

![color](https://user-images.githubusercontent.com/7588612/37242083-6a815f4e-249e-11e8-83f7-7de0f9cd73ba.gif)

Is this as designed? It looks too transparent before hovering over it.

**Comment by equinusocio** [comment]
Can you provide a gif using material theme?

**Comment by neilsustc** [comment]
This is exactly using material theme (the gif looks warmer because I forgot to exit f.lux, which makes the whole screen warmer at night).
I notice this issue after the latest update of this theme.
And I just tried the vscode v1.21.0 stable build with only this extension installed, the same issue.
You might need to put some code under the notification so it is easy to test.

**Comment by neilsustc** [comment]
Another gif (f.lux exited)

![color2](https://user-images.githubusercontent.com/7588612/37242526-f85b4d1e-24a5-11e8-97f3-e39a0c419745.gif)

**Comment by equinusocio** [comment]
Ok thank you :) i will fix that.
