### ISSUE TITLE
Cannot see icons

### ISSUE THREAD

**Issue by johndhpark** [equinusocio/vsc-material-theme#144]
Every since this morning, I am unable to see the majority of the icons except for .json and web pack files. I have tried uninstalling and installing back, but still having the same problem. I would love some help with this issue. Thank you.

**Comment by equinusocio** [comment]
Have you tried to reactivate Material Theme icons?

**Comment by johnhpark** [comment]
Thank you for the quick response. Yes I have.

**Comment by equinusocio** [comment]
Can you share some screenshots or gif?

**Comment by johnhpark** [comment]
Sure. 
<img width="268" alt="screen shot 2018-03-11 at 10 32 59 am" src="https://user-images.githubusercontent.com/30715332/37256866-cb5234cc-251d-11e8-978a-abadada544a6.png">

**Comment by johnhpark** [comment]
<img width="237" alt="screen shot 2018-03-11 at 11 18 45 am" src="https://user-images.githubusercontent.com/30715332/37256881-fa6517de-251d-11e8-928b-57a449623ce7.png">

**Comment by equinusocio** [comment]
Are you sure you activated material theme?

**Comment by johnhpark** [comment]
<img width="579" alt="screen shot 2018-03-11 at 12 29 13 pm" src="https://user-images.githubusercontent.com/30715332/37257527-d6eeb1ac-2527-11e8-84c9-51d2377344e0.png">
<img width="523" alt="screen shot 2018-03-11 at 12 28 47 pm" src="https://user-images.githubusercontent.com/30715332/37257528-d70935a4-2527-11e8-969f-058ed9442863.png">

This is the current setting that I have.

**Comment by equinusocio** [comment]
I can't figure out how to reproduce this issue.

**Comment by johnhpark** [comment]
Is there any way that I can reinstall the icons? I tried reinstalling VSCode before.

**Comment by equinusocio** [comment]
You have to remove the Material Theme extension, restart vscode and reinstall it.
