### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by pronebird** [equinusocio/vsc-material-theme#146]
Hey,

Great theme I use it on macOS a lot but now I installed it on VSCode on Windows and switching themes does nothing. :/ Accent color works though :) I still see the default VSCode theme active.

Cheers,
Andrej

**Comment by equinusocio** [comment]
Hi, before change the theme variant you first need to activate material theme. Please check the readme section:

https://github.com/equinusocio/vsc-material-theme#activate-theme

**Comment by pronebird** [comment]
Sorry, silly me.
