### ISSUE TITLE
Active accents different color

### ISSUE THREAD

**Issue by alexbet** [equinusocio/vsc-material-theme#149]
I am having an issue with the active accents. I set my accent color to Acid Lime. When I make the change, the active text accents have the Acid Lime color for about 5 seconds, and then they switch to a burgundy color. It is pretty ugly. Here is a screenshot of what happens. 

![screen_shot_2018-03-26_at_12_21_44_pm](https://user-images.githubusercontent.com/3966760/37919169-29812092-30f1-11e8-832d-c46e7acb4b90.png)

BTW, the accent colors are very wonky in this way. Can you please fix this? Thanks!

**Comment by equinusocio** [comment]
Hi. This is not a bug, the error color is used by vsc to indicate that the file have a linter errors. To disable it you have to disable the vsc related setting.
