### ISSUE TITLE
Theme stuck on high contrast versions

### ISSUE THREAD

**Issue by coe-comm** [equinusocio/vsc-material-theme#150]
VSCode 1.21.1, Material Theme 1.5.1, Mac OS High Sierra

Theme won't change from the high contrast versions. I've also tried changing the color variant with and without the settings window open and no luck. I'm able to select the non high contrast versions, but it doesn't do anything. I also tried uninstalling and reinstalling with no luck.

**Comment by coe-comm** [comment]
One other thing that I noticed that happens is that whenever I change the variant it tells me to reload because some settings have changed.

**Comment by equinusocio** [comment]
Please try to:
1. Remove all material theme settings from your setting file and **close it**
2. Remove the theme, restart vsc and then reinstall the theme.
3. Reactivate it and set a variant, with the setting file closed.

**Comment by coe-comm** [comment]
That worked! :)
