### ISSUE TITLE
Make accent color cover more ground

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/vsc-material-theme#151]
1. At the moment, `accent color` seems to only change the color of the folder icon when it's open which is not very useful. There are so many places like `border bottom of the active tab`, `text for the currently opened file`, etc. where accent color can be applied. However, it's always kind of teal color atm. Is this by design?

2. Is there a reason why most of the `property/key texts` are set to white (light grey)? It looks so pale at a glance. Is it possible we use a different color for this type, like any less intrusive color will do. Everything just looks so bright on a dark theme

![68747470733a2f2f696d6167652e6962622e636f2f6d4743746e6e2f4d6174657269616c5f5468656d652e676966](https://user-images.githubusercontent.com/17170199/38127211-d6cc0dbe-3440-11e8-8eee-23eafc11ce9f.gif)

**Comment by equinusocio** [comment]
Here where accent color is used:

![screen_shot_2018-03-30_at_11_28_38](https://user-images.githubusercontent.com/10454741/38133057-d63961a4-340d-11e8-9503-c5d1267f9985.png)

This is the full properties list:

```js
{
      "activityBarBadge.background": "#64FFDA",
      "list.activeSelectionForeground": "#64FFDA",
      "list.inactiveSelectionForeground": "#64FFDA",
      "list.highlightForeground": "#64FFDA",
      "editorSuggestWidget.highlightForeground": "#64FFDA",
      "textLink.foreground": "#64FFDA",
      "progressBar.background": "#64FFDA",
      "pickerGroup.foreground": "#64FFDA",
      "tab.activeBorder": "#64FFDA"
}
```

Visual studio code allows you to complete override theme and color scheme colors, please check the readme section:

https://github.com/equinusocio/vsc-material-theme#override-theme-colors

**Comment by pingshunhuangalex** [comment]
Thanks for the reply and closing issues so swiftly.

As you can see from the screenshot below, my choice of accent color - `purple` is only effective on current folder. All other places you've marked above remain `teal` at all time no matter what color I changed.

I've also tried reinstalling the theme, but no luck. I'm using VS Code Insider 1.22

Meanwhile, some explanation on item 2 above would be much appreciated. Thanks.

**Comment by equinusocio** [comment]
1. The issue tittle is "Make accent color cover more ground". Nice, there is a lot of place where accent color is used. If you don't see them, there is another issue (if you want open a related one).

2. The second point is a subjective consideration. What you see as "so bright" can be "so dark"  for others. Since i can make happy all people, material theme start with a default set of colors (picked up from the consolidated sublime text version) then people can adjust the colors based on personal preferences, as described in the README.
