### ISSUE TITLE
Accent color doesn't work properly (only works on current folder icon)

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/vsc-material-theme#152]
From the screenshot below, my choice of accent color - `purple` is only effective on the current folder icon no matter what color I changed.

I've also tried reinstalling the theme, but no luck. I'm using VS Code Insider 1.22. Thanks.

![2018-03-30](https://user-images.githubusercontent.com/17170199/38133501-44191f96-345b-11e8-976b-bf5c529dc47c.png)

**Comment by equinusocio** [comment]
I can't reproduce this issue:

A screenshot on 1.22.0-insiders on mac os
![screen shot 2018-03-30 at 12 08 21](https://user-images.githubusercontent.com/10454741/38134388-10ea1276-3413-11e8-9d5d-34267afa3bfc.png)

**Comment by pingshunhuangalex** [comment]
I'm using windows 10. Is there a windows machine you can maybe test things on? The theme is the first thing I installed, so there should be no other reasons for this.

**Comment by pingshunhuangalex** [comment]
Actually, the folder color will only change when I add the below settings I got from other issues.
```
"materialTheme.cache.workbench.settings": {
        "themeColours": "Darker High Contrast",
        "accent": "Purple"
},    
```

If I just use the default settings, the accent color doesn't work at all.

**Comment by equinusocio** [comment]
Even on windows i don't have this issue.. this sound strange. Can you try to purge all material-theme related settings from your setting file, remove the theme, restart vsc, and reinstall material theme?

![capture 1](https://user-images.githubusercontent.com/10454741/38134692-7cbd3aea-3414-11e8-87ec-04ed629839f6.PNG)

**Comment by pingshunhuangalex** [comment]
I delete all theme related settings -> uninstall theme -> reinstall theme -> activate theme -> change color variant -> change accent color

Each step above is followed by a restart of the editor, and still no luck. The accent color is not applying at all.

**Comment by equinusocio** [comment]
You should try to remove all the material theme related settings, including 
```
"workbench.colorTheme": "Material Theme",
"workbench.iconTheme": "eq-material-theme-icons",
"materialTheme.cache.workbench.settings": {}
```

**Comment by pingshunhuangalex** [comment]
They weren't there when I start from a clean installation, and it still doesn't quite work.

The solution I discovered is actually to have everything including all the color reference items in the setting files, then select accent color from command palate would work.

Therefore, the issue here is if the property is not in the setting files, material theme isn't able to create that key-value pair. All it can do it change it if it's there already.

**Comment by equinusocio** [comment]
Ok thank you.

**Comment by equinusocio** [comment]
@pingshunhuangalex We are working to fix this annoying issue next release.

**Comment by pingshunhuangalex** [comment]
Hi @equinusocio I can confirm that this has been fixed. It also makes more sense to have the theme option integrated in the VS command. Thanks for fix and please keep up the good work 😄
