### ISSUE TITLE
[Question] The Title Bar in Preview Design

### ISSUE THREAD

**Issue by sulkhanp** [equinusocio/vsc-material-theme#156]
Hi. In the preview pictures the design looks different because of how the topmost menu bar overlays with the whole editor. I couldn't replicate the same visual on Windows and I don't see how it's done on Linux either. How is it done? I don't think choosing an exactly matching color for the Windows window accent color would make the transition as smooth as shown in the pictures below. I attached pictures for clarity.
https://i.imgur.com/cRB2cXd.png
https://i.imgur.com/AFptjKO.png

This is how my code looks:
https://i.imgur.com/pI4JPgd.png

**Comment by equinusocio** [comment]
You need to change the `window.titleBarStyle` setting to `"custom"`. But i don't know if it works on vsc for windows.

https://code.visualstudio.com/docs/getstarted/settings#_default-settings
