### ISSUE TITLE
[Question] Custom color change in JSX 

### ISSUE THREAD

**Issue by gjhughes** [equinusocio/vsc-material-theme#157]
Is it possible to target and change the color of the text inside the JSX tags so that it doesn't match the opening/closing tag color, please? 

<img width="375" alt="screen shot 2018-04-18 at 00 58 00" src="https://user-images.githubusercontent.com/18194213/38904665-98e68f80-42a3-11e8-9936-4719560fa252.png">

**Comment by equinusocio** [comment]
VSC have a tool to inspect syntax scopes. Open the command palette and search for "scope" then select the `Developer: Inspect TM Scopes` command. You can now select the code segment (blue text) you want to get his scope. When you have the element scope you can follow the readme section to [override theme colours](https://github.com/equinusocio/vsc-material-theme#override-theme-colors). Like this:

```js
"editor.tokenColorCustomizations": {
    "[Material Theme]": {
        "ELEMENT_SCOPE": "HEX COLOR"
    },
},
```


Here more info about this VSC feature:
https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by dagolinuxoid** [comment]
@EliasJorgensen thanks a lot! This is what I was looking for! BTW. I'm using your Material Lighter theme and wonted to fine tune one thing - font-color of my sass class. Now I'm happy :)

**Comment by equinusocio** [comment]
Hi @dagolinuxoid check also our section 
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

**Comment by EliasJorgensen** [comment]
@dagolinuxoid Thanks for the praise, but I think you have me mistaken for @equinusocio 😅

**Comment by dagolinuxoid** [comment]
> @dagolinuxoid Thanks for the praise, but I think you have me mistaken for @equinusocio sweat_smile

indeed, that's fast auto-completion is *evil* - just kidding.
