### ISSUE TITLE
consider releasing the source or removing the license

### ISSUE THREAD

**Issue by bleything** [equinusocio/vsc-material-theme#159]
Hello! I found your theme and really like it. I'm an emacs user and would like to port it to emacs, but it seems the source is encrypted. I found #115 wherein @equinusocio says:

> Only the theme builder (ts files) and theme source is encrypted, not the output.

This seems to be incompatible with the Apache license that you've chosen. Section 2 of that license says in part:

> ...each Contributor hereby grants to You a ... copyright license to reproduce, prepare Derivative Works of ... and distribute the Work and such Derivative Works in Source or Object form.

By encrypting the source you've made it impossible for anyone to create a derivative work except by reverse-engineering the output. Based on #115 it seems that's what you expect people to do, but that makes for a pretty crappy experience when someone wants to build on top of your work.

I totally understand the frustration of people stealing your work and releasing it as their own, and I understand wanting to prevent that. But encrypting the source of an open source project is the wrong way to go about that. The proper response is to report those projects for violating your copyright and license and get them removed. It sucks, I know, but it's one of the responsibilities of maintaining an open source project.

It is of course your choice how to license and release your work. If you want to keep the source private and release the compiled theme, that's completely fine! But that's not open source, and it's definitely not compatible with the license you've chosen. So please either release the source or remove the license.

**Comment by equinusocio** [comment]
Hi, the ts code is encrypted by default and it can be decrypted by everyone who have a valid GPG key and GPG system to sign commits. So, if someone want to collaborate or just see the code it should simply ask. Each user is added as a trusted user and they can then see the ts code, auto-crypt and auto-decrypt each commit. 

By the way, the ts code is not relevant if you want to port the theme to other tools.

**Comment by bleything** [comment]
> Hi, the ts code is encrypted by default and it can be decrypted by everyone who have a valid GPG key and GPG system to sign commits.

Right, I understand that. But that's not open source.

> By the way, the ts code is not relevant if you want to port the theme to other tools.

I can't find anything in the repo that looks like the output of compilation. Can you show me where it is?

**Comment by equinusocio** [comment]
The js output is ignored on the repo. But you can find it inside the extension package. You can install the extension and browse his files or extract the vsix package with the vsc cli tool. 

After your comment, and since no one want to collaborate to this project, i can consider to decrypt all the files. Since this project require a ts developer i can’t fix related issue.

**Comment by bleything** [comment]
> The js output is ignored on the repo. But you can find it inside the extension package. You can install the extension and browse his files or extract the vsix package with the vsc cli tool.

I don't think it's reasonable to expect someone to install VS Code and an extension or figure out how to unpack that extension in order to work with your theme. That's what I was referring to as a bad experience before.

That said, I've done all of that and found the theme files, so I'm off and working. Thanks for the pointer.

> After your comment, and since no one want to collaborate to this project, i can consider to decrypt all the files. Since this project require a ts developer i can’t fix related issue.

I respect your decision either way. It's your work and you can do with it as you like. I'd love to see you decrypt the source and release it openly, but if you choose not to that's totally fine too. But please do consider removing the license if you don't want to release the source, because it's misleading in its current form.

Cheers.

**Comment by equinusocio** [comment]
@bleything All files are now unlocked. Thank you for your suggestion.

**Comment by equinusocio** [comment]
I will add a section to the README file where to put official portings. When you are ready just make a PR whit the updated README with your porting.

**Comment by wizard-28** [comment]
> Thanks! That's amazing!
> 
> Would you be interested in a pull request when I put together the emacs version, or would you like to keep this repo focused on the VS Code version?

Any updates on the emacs port?
