### ISSUE TITLE
No inactive border on input boxes

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#16]
As you can see in screenshot there is no color given for the border of inactive input boxes (here Search settings and Replace), while the active one has a border. 

Even if you intentionally haven't given any border,  I'll suggest you to give one because then new users on VS Code have to predict whether its just a text or it is clickable.

OS: Windows 10
Version: VS Code 1.11.2

Thanks for giving official Material Theme to VS Code too!!

![screenshot 122](https://cloud.githubusercontent.com/assets/26769888/25092400/203d5360-23ab-11e7-9172-90c7305debb7.png)

**Comment by equinusocio** [comment]
Thank you for your suggestion. Remember that is still a beta release :), When official API will be released i will fix this kind of issues.

**Comment by ajitid** [comment]
Okay thanks!! 🙌

**Comment by ajitid** [comment]
Can you also give yellow/gold colour caret like in Sublime Text when official API is released? It goes well with the theme

**Comment by equinusocio** [comment]
I don't know it at the moment because there is not documentation about the theming. If i can, i will do it :)

**Comment by equinusocio** [comment]
done with c5f2508423c0928ef7e64f751880208f5ddd097e
