### ISSUE TITLE
annotations color changed

### ISSUE THREAD

**Issue by lihua06** [equinusocio/vsc-material-theme#166]
I like this topic and use a lot of annotations in the development. Its annotation color makes me have to give up using vs dark+, because the color of the annotation is green, which can reduce my eye fatigue. Hope that the future updates can see it
![005](https://user-images.githubusercontent.com/20437381/39101470-bdc19e12-46cc-11e8-9c35-2fb026404c87.png)
![006](https://user-images.githubusercontent.com/20437381/39101472-c370d684-46cc-11e8-993d-89eef0729d7e.png)

**Comment by DamianRivas** [comment]
I agree. The gray on gray makes it a lot harder to read comments. It's my only gripe about the darker theme.

**Comment by DamianRivas** [comment]
I'm also loving the new Ocean theme, but with my high DPI monitor, some text is just way too hard to read. There should be a minimum amount of contrast between the text and background no matter what.

![image](https://user-images.githubusercontent.com/10257813/39102262-fcf32a68-4656-11e8-89d7-8a5d730735ff.png)

The Grays here could be brighter:

![image](https://user-images.githubusercontent.com/10257813/39102281-2dbee006-4657-11e8-99e3-141d00b69d8b.png)

**Comment by equinusocio** [comment]
@lihua06 About the comments color, it's a personal taste and the green color may be distracting for other users. VS Code allows you to tune the active theme through your setting file, more info [here](https://github.com/equinusocio/vsc-material-theme#override-theme-colors)

So for example, if you use `Material Theme Ocean`, you can add this to your setting file:

```js
    "editor.tokenColorCustomizations": {
        "[Material Theme Ocean]": {
            "comments": "#229977"
        }
    }
```

**Comment by lihua06** [comment]
@equinusocio Thank you
