### ISSUE TITLE
editor.renderWhitespace color

### ISSUE THREAD

**Issue by LykanIX** [equinusocio/vsc-material-theme#167]
VSCode 1.22
OS Version: Windows 10

I added "editor.renderWhitespace": "all" in my User Settings.
But we don't see them in any of Material Themes. (See images below)
![material-theme](https://user-images.githubusercontent.com/23478544/39129486-9cd1e7f0-46d8-11e8-9fcd-e1570795f8b5.png)
![kimbie-dark](https://user-images.githubusercontent.com/23478544/39129487-9ce28506-46d8-11e8-903b-c0a63eeb0585.png)

**Comment by equinusocio** [comment]
Thank you, we need to increase the invisibles color a bit 😅

**Comment by neilsustc** [comment]
Em, I think it is too bright now, comparing to the indent guides.
(seems that the size of the dot is related with your chosen font)

![image](https://user-images.githubusercontent.com/7588612/39169863-faceef3a-47cb-11e8-8a84-bb1709d5b995.png)

**Comment by equinusocio** [comment]
😔

**Comment by philippkuehn** [comment]
you do not see any difference between whitespace and comments now 😢

![8mrndzpqbw](https://user-images.githubusercontent.com/2500670/39630883-fa51971e-4fb0-11e8-82fb-a970f5c0f2b5.png)
