### ISSUE TITLE
Icons of closed directories are not visible

### ISSUE THREAD

**Issue by ioanungurean** [equinusocio/vsc-material-theme#168]
After updating to the latest version I cannot see the icons of closed folders anymore (src, public, node_modules). It becomes visible after I click on them.

I also ran `Fix File Icons`, but the result is the same.

![image](https://user-images.githubusercontent.com/11721719/39130131-a76a167c-470c-11e8-8cc9-6f0b8718af86.png)

**Comment by equinusocio** [comment]
Hi @ioanungurean try this steps:
1. Remove the extension
2. Restart VS Code
3. Reinstall the extension
4. Activate one materla theme variant and wait the windows refresh.

**Comment by ioanungurean** [comment]
Thanks alot @equinusocio, it's working now. :smile:
