### ISSUE TITLE
Better CSS coloring

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#17]
Hello,

I suggest to improve CSS coloring, picture below will explain more.

![screenshot from 2017-04-30 22-02-30](https://cloud.githubusercontent.com/assets/10441177/25567176/c7a8971e-2df0-11e7-9644-503ed62f6ae8.png)

**Comment by equinusocio** [comment]
You have to install the language extension to have a proper highlight. Native css syntax doesn't allow (not at the moment) nesting, so you have to install less, sass, or postcss extension.

**Comment by svipben** [comment]
@equinusocio Thank you, found https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language.
