### ISSUE TITLE
Light version problems

### ISSUE THREAD

**Issue by langolf** [equinusocio/vsc-material-theme#170]
Hi!
As you can see there are some problems with highlighted text in search mode.
![material-light](https://user-images.githubusercontent.com/1225205/39156832-db1f6f60-474f-11e8-9bc3-a6f79004e5b0.png)

**Comment by TrevorEyre** [comment]
I'm currently getting around this issue with some local color customizations. I'm posting them here if anyone is interested. I set all selections and highlights to just two colors of light grey, to simplify those options a bit, and search highlights to a light red. Seems to be working okay so far.

    "workbench.colorCustomizations": {
        "[Material Theme Lighter]": {
            "selection.background": "#0000001c",
            "editor.selectionBackground": "#0000001c",
            "editor.inactiveSelectionBackground": "#0000000f",
            "editor.selectionHighlightBackground": "#0000000f",
            "editor.wordHighlightBackground": "#0000000f",
            "editor.wordHighlightStrongBackground": "#0000000f",
            "editor.findMatchBackground": "#ffcdd2",
            "editor.findMatchHighlightBackground": "#ffebee",
            "editor.findRangeHighlightBackground": "#0000000f"
        }
    }

Here's an example screenshot. In the example, I'm selecting the word "state" and searching for the word "experiments".

![vscode material color mods](https://user-images.githubusercontent.com/6662070/39590149-4b87567c-4ebd-11e8-995b-458e09771b38.PNG)

**Comment by chibicode** [comment]
A temp fix would be great! Thank you :)

**Comment by equinusocio** [comment]
@chibicode As a tem fix you can customise your local installation by yourself. Please follow these steps:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

**Comment by TrevorEyre** [comment]
@equinusocio Can we please re-open? I don't believe this is fixed yet.
