### ISSUE TITLE
TypeScript file icon color

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#172]
It was blue in previous versions and is what we used to see in other places.
Is it changed by design or by accident?

![image](https://user-images.githubusercontent.com/7588612/39170959-f06e0324-47cf-11e8-98ac-b4ae79bc3fd1.png)

![image](https://user-images.githubusercontent.com/7588612/39170974-fdd688ba-47cf-11e8-8cfc-b60545f0ae11.png)

**Comment by neilsustc** [comment]
Thanks for the fix!

However, I think the background color is `#007ACC` in the official logo rather than `#3965BD` 😳
Maybe you have some considerations for this choice, but `#3965BD` is more like purple rather than blue to me.

**Comment by equinusocio** [comment]
@neilsustc No one of our icons use the original colors. We use our color palette to match the full theme experience and to keep a general consinstency between icons.

**Comment by neilsustc** [comment]
Thanks for the explanation.
