### ISSUE TITLE
Stop forcing material-theme-icon when changing from a color theme to another

### ISSUE THREAD

**Issue by Guema** [equinusocio/vsc-material-theme#176]
Hello,

it seems changing color theme from any to another material theme color theme forces icon theme to be material theme icon (the one bundled with the package).

Could you please prevent this ? i sometimes change my color theme, but must everytime change the icon theme again.

Thanks,
Guema

**Comment by equinusocio** [comment]
Hi @Guema. Actually this is not possible, we let user able to change the icon theme after the theme activation, but, by default each material theme variant will use his icons set to provide a full experience and immersion. They are a full package bundled togheter, every system works like that.

**Comment by usernamehw** [comment]
Well, that's terrible. Should this `bundle` deactivate your icon theme when switching back then?

Even if it did, it still would've been a bad experience.

[Ayu theme](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu) contributes `icon-theme` and not forces you to use it - it is example of good way of doing things.

**Comment by equinusocio** [comment]
@usernamehw ayu theme stealed our icons without credits ;) We can't force you to use Material Theme, so feel free to switch to another theme. But keep a note, windows have his os icons, mac os have his os icons, even a linux distro have his set of icon than you can change, but if you switch desktop environment, you are forced to change them again. **So, don't talk about "a good way" because we don't force anyone to use our set icons, it is just automatically activated when you choose the theme. Then you can choose to change it or not.**

**Comment by usernamehw** [comment]
It just so happens, I can use about 5+ themes a day and switching is a very natural operation. But now it changes my icon-theme and reloads my window, which is really frustrating. So, yeah, count me out.

**Comment by equinusocio** [comment]
> I can use about 5+ themes a day
This is not a theme related issue.

> and switching is a very natural operation
May not be normal for everyone.

**Comment by usernamehw** [comment]
> and switching is a very natural operation

I mean, vscode devs come through trouble of making instant hot-reload of current color theme and this theme is an exception.

**Comment by equinusocio** [comment]
Please give us some real arguments to talk about. We can consider to add a new command like `Disable icons theme auto apply` that will disable this behavior, that it will be active by default.

What to you think about that? Do you have other suggestions about possible solutions that meet both requirements?

**Comment by usernamehw** [comment]
> add a new command like Disable icons theme auto apply that will disable this behavior, that it will be active by default.

That should do it.

**Comment by equinusocio** [comment]
We are talking about that, our proposal is to make a new command that will disable this behavior and we will change the icon theme system using the vsc api and providing differents icons themes variants, that will be activated by default (if this behavior is not disabled)

**Comment by equinusocio** [comment]
Ref #181
