### ISSUE TITLE
Test files icon change

### ISSUE THREAD

**Issue by rafaelyates** [equinusocio/vsc-material-theme#179]
It'd be very cool if you guys provide **different icons for .spec.ts** files. Thanks

**Comment by equinusocio** [comment]
Hi @rafaelyates, right now `.ts` and `.d.ts` have different icons. what do you think about using the  `.d.ts` icon also with `.spec.ts`?

**Comment by equinusocio** [comment]
Fixed as said.
https://github.com/equinusocio/vsc-material-theme/blob/develop/src/icons/partials/fileExtensions.js#L97
