### ISSUE TITLE
Add coloring for types in comments

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#18]
Hello,

my suggestion is to make types in comments colorized like it's in Atom. This will be really cool to have in this theme. The color of types will be as it is right now if we write it outside of comments.

This theme:
![screenshot from 2017-04-30 22-10-56](https://cloud.githubusercontent.com/assets/10441177/25567225/f3a027f0-2df1-11e7-850b-5b7e752ac149.png)

Atom:
![ded6b92c-2d08-11e7-9019-1bd34ddf06b6](https://cloud.githubusercontent.com/assets/10441177/25567226/f8fc453a-2df1-11e7-95c6-1035d0bda485.png)

As you can see in Atom it is colorized like it was outside of comments, it will be very cool to have it same in this theme.

**Comment by equinusocio** [comment]
This is the official [Material Theme](https://github.com/equinusocio/material-theme). Other versions are just customised porting. I'm sorry at the moment there is no plans for changing the color scheme/ui theme, just porting.

**Comment by svipben** [comment]
@equinusocio No problem. I really like this theme, because it's really good, tested almost all popular material themes, but this one is best!
