### ISSUE TITLE
Contrast issues with Terminal Powerline

### ISSUE THREAD

**Issue by ekfuhrmann** [equinusocio/vsc-material-theme#180]
Is there any way we can improve the legibility of powerline in terminal?

![image](https://user-images.githubusercontent.com/8878152/39646448-7851524c-4fa9-11e8-9663-0fe56e26180b.png)

It could really use some better contrast between the background color and text color.

For comparison, this is how it looks with One Dark Theme:

![image](https://user-images.githubusercontent.com/8878152/39646529-bacec884-4fa9-11e8-9a0c-8cd46bf0ce19.png)

**Comment by equinusocio** [comment]
Hi @ekfuhrmann. This issue is not related to this project, please consider to report your issue to the terminal theme author

**Comment by ekfuhrmann** [comment]
This theme according to the src file does modify the following terminal colors:

```json
"workbench.colorCustomizations": {
    "terminal.ansiWhite": "{{variant.scheme.base.white}}",
    "terminal.ansiBlack": "{{variant.scheme.comments}}",
    "terminal.ansiBlue": "{{variant.scheme.base.blue}}",
    "terminal.ansiCyan": "{{variant.scheme.base.cyan}}",
    "terminal.ansiGreen": "{{variant.scheme.base.green}}",
    "terminal.ansiMagenta": "{{variant.scheme.base.purple}}",
    "terminal.ansiRed": "{{variant.scheme.base.red}}",
    "terminal.ansiYellow": "{{variant.scheme.base.yellow}}",
    "terminal.ansiBrightWhite": "{{variant.scheme.base.white}}",
    "terminal.ansiBrightBlack": "{{variant.scheme.comments}}",
    "terminal.ansiBrightBlue": "{{variant.scheme.base.blue}}",
    "terminal.ansiBrightCyan": "{{variant.scheme.base.cyan}}",
    "terminal.ansiBrightGreen": "{{variant.scheme.base.green}}",
    "terminal.ansiBrightMagenta": "{{variant.scheme.base.purple}}",
    "terminal.ansiBrightRed": "{{variant.scheme.base.red}}",
    "terminal.ansiBrightYellow": "{{variant.scheme.base.yellow}}"
}
```

Some of these colors do not have good contrast at all with this themes `"terminal.ansiBlack": "{{variant.scheme.comments}}",` which is the font color, causing there to be the contrast issue I highlighted. My suggestion is to just make sure that the greens, blues, grays, etc. do not conflict with the font color.

I personally resolved the issue by modifying to the following value `"terminal.ansiBlack": "#333"`.

**Comment by equinusocio** [comment]
Ok now I get the point. What do you think about set `terminal.ansiBlack` to a pure '#000'?

**Comment by ekfuhrmann** [comment]
Sorry for not being more descriptive with the issue! 

I have no issue with setting `terminal.ansiBlack` to `#000`.  That will resolve any contrast issues I've come across within the integrated terminal.
