### ISSUE TITLE
php specifying HTTP method only colors DELETE?

### ISSUE THREAD

**Issue by dingo-d** [equinusocio/vsc-material-theme#189]
**Describe the bug**
Not sure how much of a bug this is, but when working on php files, specifying the `DELETE` keyword when making cURL requests for instance, the `'DELETE'` will be colored red, but for the same thing, specifying `'POST'` colors it green.

That kinda makes it inconsistent. It would be great if the `POST` is also in red.

**To Reproduce**
1. Make a php file
2. Create `'POST', 'DELETE'` keywords anywhere in the code
3. The colors are different

**Expected behavior**
It would be great if the methods were colored the same

**Screenshots**
![screen shot 2018-05-14 at 09 23 45](https://user-images.githubusercontent.com/8638515/39983700-d5c1a7a4-5758-11e8-991f-4f114d1fed1c.png)
![screen shot 2018-05-14 at 09 24 16](https://user-images.githubusercontent.com/8638515/39983701-d5df8332-5758-11e8-8a40-b246e5311b3f.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra v 10.13.4
 - VS Code: Version 1.23.1 (1.23.1)
 - Material theme v 2.0.1

**Comment by dingo-d** [comment]
In Sublime, the color of the `DELETE` is purple, and that's because it recognizes it as an SQL statement. So I reckon that's the same issue here. Either all the HTTP request methods should be colored in a different way, or they should just be green :)

**Comment by equinusocio** [comment]
@dingo-d After some investigation, i found the issue. The built-in php extension does not associate the correct scope to the `POST` method, while it do with the `DELETE` method. As you can see these are the TM Scopes inspector outputs:

**POST**
<img width="464" alt="screen shot 2018-05-18 at 21 39 19" src="https://user-images.githubusercontent.com/10454741/40254566-3ffddffa-5ae4-11e8-9afe-9ba694cfee12.png">

**DELETE**
<img width="339" alt="screen shot 2018-05-18 at 21 39 11" src="https://user-images.githubusercontent.com/10454741/40254572-470fe2de-5ae4-11e8-8afa-3063bd886d7c.png">


As you can see the `DELETE` keyfoword is recognised as  `source.sql.embedded.php > keyword.other.DML.sql` which is not associated to the `POST` method, which is `string.quoted.single.php`.

You should report this issue to the vscode team to fix the built-in php language.

**Comment by dingo-d** [comment]
Cool, thanks for the explanation.
