### ISSUE TITLE
Improve JSX / HTML tags attributes

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#19]
Hello,

1. As you can see in Atom HTML tags attributes are italic, it really helps.

![screenshot from 2017-04-30 22-27-28](https://cloud.githubusercontent.com/assets/10441177/25567353/43830d44-2df4-11e7-8daa-b4d279781807.png)

2. To don't create new issue since it's related with JSX, we need to have white or another color for text I think, picture below explains.

![screenshot from 2017-04-30 22-31-00](https://cloud.githubusercontent.com/assets/10441177/25567377/c75012e8-2df4-11e7-937c-0bc32a552c45.png)

**Comment by equinusocio** [comment]
As mentioned [here](https://github.com/equinusocio/vsc-material-theme/issues/18#issuecomment-298254654) the atom material theme is just a customised port of the original one (this one). There is not links between the original version and portings. I'm sorry. 

Eventually improvements will be considered after the 1.0.0 release
