### ISSUE TITLE
Add icon for prettier

### ISSUE THREAD

**Issue by azdanov** [equinusocio/vsc-material-theme#191]
[Prettier](https://prettier.io/) is quite popular.

An icon for `.prettierrc` file would be nice. Here are some other variations for the [configuration](https://prettier.io/docs/en/configuration.html#docsNav) file.

The [vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/prettier.svg) has a nice icon for this.

Thoughts?

**Comment by equinusocio** [comment]
Hi @azdanov. Thank you for your suggestion, with the May release we will ship a complete new set of file icons, and yes, we will add this.
