### ISSUE TITLE
Using Material Theme Ocean High Contrast editor window is different color

### ISSUE THREAD

**Issue by Nojil** [equinusocio/vsc-material-theme#193]
**Describe the bug**
In your screenshots of the theme the Ocean High Contrast them has a dark sidebar and a dark editor, both the same color. It is presenting with different colors.

**To Reproduce**
1.) Download Material Theme v2.0.1
2.) Change theme to Material Theme Ocean High Contrast

**Expected behavior**
I expected the sidebar and the editor to be the same color

**Screenshots**
![capture](https://user-images.githubusercontent.com/11978772/40490753-9f2711e2-5f29-11e8-97ac-d25a8cc42a01.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 

**Smartphone (please complete the following information):**
 - Desktop

**Comment by equinusocio** [comment]
Hi @Nojil. All high contrast variants use a different background color for the sidebar. To have the unified color use the normal Ocean variant. (not high contrast)
