### ISSUE TITLE
Add css folder icon

### ISSUE THREAD

**Issue by shubhamtiwari23** [equinusocio/vsc-material-theme#194]
The css folder icon is less specified than js and images it is looking like a normal folder and the js and images icons are looking more classified

![capture](https://user-images.githubusercontent.com/36166024/40525567-7028f434-5ffe-11e8-8da1-5ec4050c77a6.PNG)

**Comment by shubhamtiwari23** [comment]
like js and images

**Comment by equinusocio** [comment]
Hi @shubhamtiwari23, can you please be more specific and provide additional informations? Thank you.

**Comment by shubhamtiwari23** [comment]
the css folder icon is less specified than js and images it is looking like a normal folder

**Comment by shubhamtiwari23** [comment]
the js and images icons are looking more classified

**Comment by equinusocio** [comment]
Close in favor pf #199

**Comment by equinusocio** [comment]
#198
