### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by makcakaya** [equinusocio/vsc-material-theme#195]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The theme should support Visual Studio 2017 too.

**Comment by equinusocio** [comment]
Hi, material theme is made for Visual Studio Code, if you want it to be ported for other software, you need to hope that someone will do it, or make it yourself. Here you can check the officials portings:
https://github.com/equinusocio/vsc-material-theme#official-portings
