### ISSUE TITLE
Enabling issue

### ISSUE THREAD

**Issue by MandarSant** [equinusocio/vsc-material-theme#2]
After installation cannot able to enable the theme

**Comment by equinusocio** [comment]
Just reload the editor and type color theme inside the command palette

![2017-02-08 15 04 06](https://cloud.githubusercontent.com/assets/10454741/22740413/efe7de4a-ee0f-11e6-8cb4-c3b1b1f4a079.gif)

**Comment by MandarSant** [comment]
@equinusocio i done same way but the effect is not getting i also tried uninstalling other theme
