### ISSUE TITLE
After update Material Theme is not working correctly

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#20]
Hi,

right now I updated it to 0.0.10 and it doesn't work correctly, picture below explains.

![screenshot from 2017-05-01 01-58-00](https://cloud.githubusercontent.com/assets/10441177/25568721/a6f2dce8-2e11-11e7-838e-fb32124571b0.png)

**Comment by assuming** [comment]
Same problem here, seems like all the background colors are gone

**Comment by Devinnan** [comment]
Same problem too,when set "workbench.colorTheme": "Material Theme", background colors disappear

**Comment by svipben** [comment]
We get update from `develop` branch, not from `master`, maybe that's why, any news @equinusocio? With 0.0.8 everything was good, but after update to 0.0.10 theme is corrupted.

**Comment by abhineettandon** [comment]
Having the same problem even after purging the editor and reinstalling.

**Comment by shpasser** [comment]
Same problem here, the short term solution would be to downgrade to version 0.0.8. Just clone tag 0.0.8 via git (or download the zip file for tag 0.0.8), replace the current copy of the plugin and you are good to go.

**Comment by fredrikaverpil** [comment]
0.0.10 works fine with vscode insiders but seems not to work well with the regular vscode.

**Comment by svipben** [comment]
The update of regular VS Code will be soon I think, so our best solution right now is wait or use @shpasser  method :smile:

**Comment by equinusocio** [comment]
My fault. Please check for a new extension update. After 1.12 will be released i will push the latest updates.

**Comment by svipben** [comment]
@equinusocio Yey!

**Comment by abhineettandon** [comment]
@equinusocio Thanks for the update.
