### ISSUE TITLE
Icon request: Windows shortcut `.lnk`

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#201]
A Windows file shortcut is something like a symbolic link (or termed soft link) in Unix or a Macintosh alias. It's file extension is `lnk`.

**Comment by equinusocio** [comment]
Hi @neilsustc, thank you for your request. Can you provide more info? There is a standard icon for these files? is `lnk` a standard file extension or just for windows?

**Comment by neilsustc** [comment]
Thank you for this nice project 😉
