### ISSUE TITLE
Light Theme: List items are difficult to see in various situations

### ISSUE THREAD

**Issue by JSteitz** [equinusocio/vsc-material-theme#204]
**Describe the bug**
As the title says, I have many problems to see which item is selected or have difficulties to read unfocused selected items.

**File selected, focus in editor**
![file_selected_focus_in_editor](https://user-images.githubusercontent.com/677821/41295001-b5a476b4-6e59-11e8-8c18-de05398d1b66.jpg)

**File selected, focus on list item**
![file_selected_focus_on_list_item](https://user-images.githubusercontent.com/677821/41295170-2eb5da20-6e5a-11e8-855f-55af262d743c.jpg)

**Both states switch depending on which tree you have the focus**
![file_selected_tree_states_different](https://user-images.githubusercontent.com/677821/41295338-9ef2238e-6e5a-11e8-87ce-8badc5d9450d.jpg)

This are current my settings for the "Lime" accent:
```json
{
    "list.hoverForeground": "#B1C7D3",
    "list.hoverBackground": "#FAFAFA",
    "list.activeSelectionBackground": "#80CBC4",
    "list.activeSelectionForeground": "#FAFAFA",
    "list.inactiveSelectionBackground": "#80CBC4",
    "list.inactiveSelectionForeground": "#FAFAFA"
}
```
And this the result for all states, except for hover (bug in vscode itself)
![fixed_1](https://user-images.githubusercontent.com/677821/41295643-5d365c02-6e5b-11e8-889f-87781d5fefae.jpg)

**Comment by equinusocio** [comment]
The default accent color is not optimised for the lighter version, you should use another accent color when you work with the lighter variant.

Btw, we need to fix the `list.inactiveSelectionBackground` to make more contrast with the accented foreground.
