### ISSUE TITLE
Accomodate For Custom Menubar Implementation

### ISSUE THREAD

**Issue by sulkhanp** [equinusocio/vsc-material-theme#206]
VScode will be adding custom menu bars in 1.25. I think this should be a #1 priority to adjust all material themes for this update.  
Reference: https://github.com/Microsoft/vscode/pull/51422

**Comment by LasaleFamine** [comment]
Hey @sulkhanp, actually we are working to align the Material Theme to the new VSCode update. The Custom Menubar I think will be one of the improvement. Would you like to follow the other issue? Reference: #197
