### ISSUE TITLE
Lack of colorization in the struct members after arrow operator in C++

### ISSUE THREAD

**Issue by donatoaguirre24** [equinusocio/vsc-material-theme#21]
I'm running vs code 1.11 on Ubuntu 16.04. 

Using the theme with a **C++** project I notice the **lack of colorization** in the struct members after arrow operator in stock and darker variants of the theme but not in the other variants. 

It would be great if you could fix it, the theme is beautiful and actually became my main but solving this little bug is all that's missing to be perfect.

**Attached below captures to better explain the problem:**

* Material Theme Palenight (Here the color of the members is different from that of the structure variable)
![issue1](https://cloud.githubusercontent.com/assets/20030075/25588547/230f8386-2e7f-11e7-8ce3-0ee73a0cc98b.png)
* Material Theme (Here the members have the same color that the variable)
![issue2](https://cloud.githubusercontent.com/assets/20030075/25588593/54599ae4-2e7f-11e7-9f58-4c83aef7ab84.png)
* Material Theme Darker (Here the members have the same color that the variable)
![issue3](https://cloud.githubusercontent.com/assets/20030075/25588630/6b95883a-2e7f-11e7-9da4-9d9628097880.png)

**Comment by equinusocio** [comment]
You have a different color highlight, there are actual highlight:
<img width="294" alt="screen shot 2017-05-11 at 11 18 15" src="https://cloud.githubusercontent.com/assets/10454741/25941958/94dff98c-363b-11e7-9d1c-5d04299919ca.png">
<img width="289" alt="screen shot 2017-05-11 at 11 17 55" src="https://cloud.githubusercontent.com/assets/10454741/25941957/94dcb7f4-363b-11e7-9e01-a3c557eb55bf.png">
<img width="298" alt="screen shot 2017-05-11 at 11 18 03" src="https://cloud.githubusercontent.com/assets/10454741/25941955/94db0706-363b-11e7-898f-db520ff8d0a4.png">
<img width="300" alt="screen shot 2017-05-11 at 11 17 38" src="https://cloud.githubusercontent.com/assets/10454741/25941956/94dc0fa2-363b-11e7-90bd-a86e30547fd0.png">

**Comment by donatoaguirre24** [comment]
But that is wrong. The idea was that the arrow operator and the field of the structure had syntax highlighting like other themes. Before the themes palenight and light were fine only needed support for the other two, but now all themes are broken.

**Comment by equinusocio** [comment]
They are not broken, this is the current highlight. Eventually scheme improvements will be considered for a 1.x release

**Comment by donatoaguirre24** [comment]
I updated vs code and the extension and I have the same syntax highlighting what do you show up. It would be great if the following versions included highlighting in the struct fields. Thanks for the answer. Continue with the great work 👍🏻

**Comment by equinusocio** [comment]
@donatoaguirre24 from next release it will be:
<img width="312" alt="screen shot 2017-05-16 at 21 22 48" src="https://cloud.githubusercontent.com/assets/10454741/26124175/dac12ed0-3a7d-11e7-9433-b203bee7e19b.png">

**Comment by equinusocio** [comment]
Next release it will be:
<img width="292" alt="screen shot 2017-05-16 at 21 26 49" src="https://cloud.githubusercontent.com/assets/10454741/26124357/7315c51a-3a7e-11e7-89db-2459efb57230.png">

**Comment by donatoaguirre24** [comment]
Looks great, thank you very much for solving it so fast. Keep up the good work

**Comment by equinusocio** [comment]
Please feel free to open another issue for highlight improvements.
