### ISSUE TITLE
How to change the basic text color from bright-white?

### ISSUE THREAD

**Issue by AlexFiliakov** [equinusocio/vsc-material-theme#213]
**Is your feature request related to a problem? Please describe.**
I'd like to change the default font color from the bright-white to an off-white color. This is the text that shows up when you're simply working with plain text (also looks to be used for variable names). I wasn't able to do it through TextMate because I don't think this text has a scope. Is it an editor setting?

**Describe the solution you'd like**
It would be really great if the doc section "Color Scheme override" contained an example of how to override the plain text color setting.

**Describe alternatives you've considered**
I know it must be possible because the light variations of this theme contain dark plain text. Unfortunately I wasn't able to find the setting, even doing a text compare on the two themes.

**Additional context**
I'm new to VSC theming, but have spent over an hour reading various docs and experimenting to find the plain text setting. The scope paradigm of TextMate seems very powerful, unfortunately it looks like plain text is unscoped or part of UI.

**Comment by AlexFiliakov** [comment]
Of course I find it right after I post this message...

It might save someone a bunch of headache in the future if this were included in the doc:

```
{
    "workbench.colorCustomizations": {
        "editor.foreground": "#f1f1f1"
    }
}
```

**Comment by jmonteros81** [comment]
thks!
