### ISSUE TITLE
Request: notify user before reloading

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#215]
**Describe the bug**
Please don't automatically reload window after changing the theme setting
My running tasks in the integrated terminal are terminated by the reloading.

**To Reproduce**
1. Start with the default theme
2. Change to the Material theme
3. See vscode reloads

**Expected behavior**
Notify user and provide "reload now" and "later" options

**Comment by equinusocio** [comment]
Hi @neilsustc, i can't reproduce this issue. On my machines it seems to working fine.

![kapture 2018-06-29 at 14 11 57](https://user-images.githubusercontent.com/10454741/42091657-84859158-7ba6-11e8-8dc1-6a55387b9686.gif)

**Comment by neilsustc** [comment]
@LasaleFamine I guess you mean `materialTheme.autoApplyIcons`. I found it before opening this issue. But I didn't expect it to be the reason why my vscode reloads. If it is the case, I think it may solve this issue.

And IMHO, it is weird to have such a setting. As a user, I don't know much about the mechanism of this extension. It is always good to tell users before doing such a "dangerous" operation.
If we need this option to dismiss the annoying messages ("reload now" or "later"), we'd better set `autoApplyIcons` to `false` by default.

@equinusocio You need to choose vscode default dark+ theme at first and then change it to the Material theme.
I'm on vscode v1.25.0-insider

**Comment by equinusocio** [comment]
@neilsustc Same even starting from the default vscode theme:
![kapture 2018-06-29 at 22 00 57](https://user-images.githubusercontent.com/10454741/42112398-f92d76c4-7be7-11e8-92b8-613adab8abd2.gif)

Have you tried to remove the extension, clean all the material theme related settings form your setting file and reinstall it?

**Comment by neilsustc** [comment]
@equinusocio I tried to reinstall the extension and remove all settings contain "material" including

```
"workbench.colorTheme": "Material Theme",
"materialTheme.fixIconsRunning": false,
"workbench.iconTheme": "eq-material-theme-icons"
```

And it still reloads. That makes sense because by default `autoApplyIcons` is `true` (which means vscode will reload without asking). I am wondering whether you have set `autoApplyIcons` to `false` before 😂

![reload](https://user-images.githubusercontent.com/7588612/42120771-943630d2-7c53-11e8-9c33-94435013e2a1.gif)

**Comment by LasaleFamine** [comment]
> If we need this option to dismiss the annoying messages ("reload now" or "later"), we'd better set autoApplyIcons to false by default.

Absolutely agree. This is something we can do on new installation. 

The real problem is that we need to reload the window to fix the icons color and before the introduction of the new flag we were forcing auto-reload.

@neilsustc do you think this UX problem can be solved adding the flag as false by default?

**Comment by neilsustc** [comment]
I think so 😉
