### ISSUE TITLE
editor.findWidgetResizeBorder is invalid.

### ISSUE THREAD

**Issue by Guema** [equinusocio/vsc-material-theme#218]
**Describe the bug**
findWidgetResizeBorder is invalid flag in colorCustomization, at least in the latest version of vscode (1.24.1)
Setting accent color will add this incorect flag, instead of the right (or new) one : "editorWidget.resizeBorder"

**To Reproduce**
- use quick command menu
- set accent color to blue, for exemple
-> find feature (CTRL+F on windows) border is not colored with accent.

**Expected behavior**
-> No invalid flag in options
-> Color the widget border according accent color

**Screenshots**
![image](https://user-images.githubusercontent.com/8943532/42090792-06943d2e-7ba3-11e8-924c-161e89dc2cc9.png)

![image](https://user-images.githubusercontent.com/8943532/42090803-145d1958-7ba3-11e8-98db-098eb34b43aa.png)

**Desktop (please complete the following information):**
OS : win7x64
Vscode : 1.24.1
Ext: 2.2.0

edit : on the screenshot accent color is blue. i cleared whole color customisation object in the user-customisation json to let Material Theme rewrite it.

**Comment by equinusocio** [comment]
Thank you.
