### ISSUE TITLE
Theme Light: General improvements

### ISSUE THREAD

**Issue by JSteitz** [equinusocio/vsc-material-theme#22]
Hello,

I'm using the light theme and the normal text color is white and not visible.
There are some more problems with the light theme, but I'm waiting for 0.0.12 to see if they are already fixed.

![docker groovy - codebase 2017-05-02 12-05-54](https://cloud.githubusercontent.com/assets/677821/25613802/d4faa82c-2f2f-11e7-9238-e81fbfe5307b.jpg)

**Comment by equinusocio** [comment]
Can you paste this code snippet?

**Comment by JSteitz** [comment]
Codesnippet from Groovy file.

```groovy
if (param.tags != null) {
    if (param.tags instanceof String) {
        tags = ["${param.tags}"]
    } else if (param.tags instanceof List) {
        tags = param.tags
    } else if (param.tags instanceof Boolean && param.tags == true) {
        tags = [
            "${env.BRANCH_NAME_SAFE}",
            "${env.BRANCH_NAME_SAFE}-${env.BUILD_NUMBER}-${env.GIT_COMMIT_SHORT}"
        ]
    }
}
```

**Comment by equinusocio** [comment]
Thank you, i will fix this issue with the 0.0.12 after vscode 1.12 will be reelased.

**Comment by equinusocio** [comment]
This is what i get with vsc 1.12- insiders:
<img width="635" alt="screen shot 2017-05-03 at 17 09 52" src="https://cloud.githubusercontent.com/assets/10454741/25667285/587dd518-3023-11e7-9b2d-d895e658abd1.png">

**Comment by JSteitz** [comment]
Can I pull the changes and take a look for more bugs in the Light Theme?
I have some more, but want to check them before posting.

And I have a suggestion for a second light theme.

**Comment by equinusocio** [comment]
If you want to try a pre-release, you have to install Visual Studio Code Insiders (1.12), then install the packaged extension, by run the `Install from VSIX`..here the release for vsc 1.12:

[vsc-material-theme-0.0.10.vsix.zip](https://github.com/equinusocio/vsc-material-theme/files/975564/vsc-material-theme-0.0.10.vsix.zip)

**Don't install this inside the regular Visual Studio, and please don't publish it**

**Comment by JSteitz** [comment]
Most bugs that I have with v0.0.11 are fixed in v0.0.12 (VSCode Insider).

**1**  
The cross should be black like the hover one.
If possible "open files" should be styled the same as the tabs

**2**
The contrast could be a bit higher

**3**
The ident lines are missing. I don't know if it is coming from the new theming thing or a bug in the Insider. (Tested with Material Theme and Default Themes)

![docker groovy - codebase 2017-05-04 11-27-08](https://cloud.githubusercontent.com/assets/677821/25698652/ef37cf44-30bf-11e7-8e56-a320be016e46.jpg)

**Comment by equinusocio** [comment]
Check my screenshot above, the indent guides are visible..

**Comment by equinusocio** [comment]
**1:** Is a vsc bug, i can't fix it now. The active list item inherit style form the sidebar tree, i can't differentiate it atm. I will fix this when https://github.com/Microsoft/vscode/issues/26720 will be closed

**2:** Fixed

**3:** Indent lines are there.
