### ISSUE TITLE
JS self keyword is not italic and doesn't have any color on it

### ISSUE THREAD

**Issue by paul321** [equinusocio/vsc-material-theme#220]
Hi,

In js if i have the following script self var doesn't have any color or italic font, see screenshots compared to Sublime.

First one is VS-Code with material theme, second is Sublime with material theme
![vs-code](https://user-images.githubusercontent.com/555502/42128118-fc9be6ae-7cac-11e8-9b7d-901889360a41.jpg)
![sublime](https://user-images.githubusercontent.com/555502/42128120-00bc4a30-7cad-11e8-9e1b-537d284675f1.jpg)

**Comment by equinusocio** [comment]
Hi @paul321. Can you try with the insiders build? I can reproduce this issue only on the normal vscode version but not on the insiders one.

<img width="216" alt="screen shot 2018-07-01 at 18 52 05" src="https://user-images.githubusercontent.com/10454741/42136668-1380e41a-7d60-11e8-8177-4f7550edaa72.png">

**Comment by paul321** [comment]
Hi @equinusocio, can you give me a hint how to install the insider build?

Thank!

**Comment by equinusocio** [comment]
It is just a different vscode version that is updated more frequently before updates become official. You can download it here:
https://code.visualstudio.com/insiders/

**Comment by paul321** [comment]
I just tested the insider version and it doesn't work, here is the screenshot. I've tested it on a project that uses requirejs and the files are loaded with define([], function() {}) maybe that can cause the problem.

![screen shot 2018-07-02 at 12 20 58](https://user-images.githubusercontent.com/555502/42155982-858309d4-7df2-11e8-8385-2b8bb4efdde5.png)

**Comment by equinusocio** [comment]
Can you give the snippet? Are you using some js extension?

**Comment by paul321** [comment]
Here is a simple snippet: 

define(['base'], function('Base') {
    return Base.extend({    
    }, {
        init: function() {
            var self = this;
            self.log();
        },
        log: function() {
            console.log('Log something');
        }
    });
});

This one doesn't work and i'm not using any js extensions.

**Comment by equinusocio** [comment]
On my second machine i can't reproduce this issue on both insiders and normal vscode. Here a screen:
<img width="1440" alt="screen shot 2018-07-02 at 12 12 22" src="https://user-images.githubusercontent.com/10454741/42158634-533ed918-7df1-11e8-8269-026021151f86.png">

Can you please check if you have the same language association (Javascript Babel) and if they have the same scope assigned?

You can check the scope by searching for `scope` in the command palette and then highlight the `self` keyword.

**Comment by paul321** [comment]
Ok i installed babel plugin and now everything works even on official version.

Thanks!
