### ISSUE TITLE
How to Make VS Code look like the featured image 

### ISSUE THREAD

**Issue by SethuSenthil** [equinusocio/vsc-material-theme#223]
I was switching between all my theme options but I still can't get my IDE to look like this (the first, biggest theme displayed).
![Image of the featured photo](https://camo.githubusercontent.com/9bed7cd5e05a4af0d6e52496de7df87aa490dce5/68747470733a2f2f692e696d6775722e636f6d2f71767863374f412e6a7067)
Are there any specific settings I need to set in order to accomplish that look? Thanks in advance.

**Comment by equinusocio** [comment]
Hi @SethuSenthil you just need to activate the Ocean theme variant.
