### ISSUE TITLE
Markdown links highlighting

### ISSUE THREAD

**Issue by Ash258** [equinusocio/vsc-material-theme#224]
**Describe the bug**
Markdown links highlighting is broken, when URL contains parenthess **()**.

**To Reproduce**
1. Create empty (/untitled) markdown file
2. Insert some link with parenthess `[Episodes](https://en.wikipedia.org/wiki/Those_Who_Kill_(U.S._TV_series)#Episodes)`
3. See broken syntax highlight.

**Expected behavior**
Highlight should be aware of 

**Screenshots**

![Bug](https://i.imgur.com/WVFmNjq.png)

**Desktop (please complete the following information):**
 - OS: Windows 10x64 17134.112
 - VScode Version: 1.26-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426)
 - Material theme extension: 2.3.0

**Comment by equinusocio** [comment]
Hi, this issue is related to the built-in markdown language. I suggest you to report the issue to the vscode team.

<img width="1019" alt="screenshot 2018-07-09 at 22 07 16" src="https://user-images.githubusercontent.com/10454741/42473343-b060fba2-83c4-11e8-9a21-64c73ae56efa.png">
