### ISSUE TITLE
Suggestion for an additional Light Theme

### ISSUE THREAD

**Issue by JSteitz** [equinusocio/vsc-material-theme#23]
I like to have the color scheme to be light but the workspace itself should be dark.
Here is a screenshot from my current setup of Material Theme Light for color scheme and Material Theme (normal) for statusbar/activitybar.

![light-theme-alternative](https://cloud.githubusercontent.com/assets/677821/25698940/55b94da0-30c1-11e7-865c-25d2d93c4ae7.jpg)

**Comment by equinusocio** [comment]
Material Theme provide a full-ui experience as the original one for Sublime Text. You can override the workbench colors by yourself with the settings. Check this reference:
https://code.visualstudio.com/docs/getstarted/theme-color-reference
