### ISSUE TITLE
Status Bar background color remains VS Code default

### ISSUE THREAD

**Issue by melwas** [equinusocio/vsc-material-theme#230]
**Describe the bug**
Status Bar background color remains VS Code default which causes text to be barely visible.

**To Reproduce**
1. Open VS Code with either an old project, a new project or a single file.
2. Take a look at status bar. 

**Expected behavior**
Text on the Status Bar is clearly visible.

**Screenshots**
<img width="1645" alt="screen shot 2018-08-10 at 12 06 03" src="https://user-images.githubusercontent.com/644856/43952723-0a655626-9c97-11e8-9be1-f05b8d212a0a.png">

**Desktop (please complete the following information):**
 - macOS High Sierra
 - VS Code Version: 1.25.1
 - Material Theme Version: 2.3.0

**Comment by equinusocio** [comment]
Hi @melwas. Can you please make sure that you don't have any override in your settings (both project and global)?

**Comment by melwas** [comment]
Hi @equinusocio, you're right :) There were some overrides which caused the issue. Closing the issue. Thanks!
