### ISSUE TITLE
Breadcrumbs have been added [Patch 1.26.0]

### ISSUE THREAD

**Issue by ekfuhrmann** [equinusocio/vsc-material-theme#234]
With the release of 1.26.0, VScode has now added breadcrumbs to the mix. It would be great if these could be brought in to the theme.

The new theme colors for the breadcrumbs are:
- `breadcrumb.foreground`: Color of breadcrumb items.
- `breadcrumb.focusForeground`: Color of focused breadcrumb items.
- `breadcrumb.activeSelectionForeground`: Color of selected breadcrumb items.
- `breadcrumbPicker.background`: Background color of breadcrumb item picker.

**Comment by equinusocio** [comment]
Hi @ekfuhrmann Thank yuou for your report. We already added these new api in 681db679b94b83128065e2288651fe62fbbaae5b as you can se in #228. This feature will be released with the August release at the end of the month-

**Comment by ekfuhrmann** [comment]
Fantastic, sorry for missing that!
