### ISSUE TITLE
Italicised Keywords

### ISSUE THREAD

**Issue by ahmedu007** [equinusocio/vsc-material-theme#235]
**Is your feature request related to a problem? Please describe.**
I really like this theme. The colors are awesome, everything works great. The only thing I would love to have is the ability to have italicised keywords. 

**Describe the solution you'd like**
Is there a way to add an option to toggle them? Or maybe have another variant with them?

**Describe alternatives you've considered**
I've tried a few other themes which do it fine, but the color scheme is not something I could adjust to.

**Comment by equinusocio** [comment]
Hi @ahmedu007 Vs code allows you to customise your themes in easy way through user settings:

```json
"editor.tokenColorCustomizations": {
    "[Material Theme High Contrast]": {
      "textMateRules": [
        {
          "scope": [
            "comment",
            "comment.block",
            "comment.line",
            "storage.type",
            "storage.modifier",
            "entity.other.attribute-name",
          ],
          "settings": {
            "fontStyle": "italic"
          }
        }
      ]
    }
},
```

**Comment by ahmedu007** [comment]
Thank you so much for the prompt reply. Cheers 💯 🎉
