### ISSUE TITLE
Add styling for the new breadcrumb dropdowns

### ISSUE THREAD

**Issue by mserajnik** [equinusocio/vsc-material-theme#238]
The July update of VS Code has added [breadcrumbs](https://code.visualstudio.com/updates/v1_26#_breadcrumbs) which are a really welcome addition.

When you click on them, a dropdown opens:

<img width="608" alt="screen shot 2018-08-16 at 16 38 35" src="https://user-images.githubusercontent.com/28833155/44215545-11fe7580-a173-11e8-9727-ea9cc26dd083.png">

As you can see, the dropdown currently has the default dark VS Code background color which doesn't really match the rest of the theme. I think it would be nice to have an appropriate background color for each of the color schemes.

**Comment by mserajnik** [comment]
Whoops, I just saw #234. Sorry, I think this is redundant, correct?

**Comment by equinusocio** [comment]
Yes. Already fixed. 💣
