### ISSUE TITLE
contrast for titlebar's menus on windows

### ISSUE THREAD

**Issue by camiant** [equinusocio/vsc-material-theme#239]
the new setting ``"window.titleBarStyle": "custom"`` needs  some fixes on the contrast

![screenshot](https://preview.ibb.co/nHFixe/2018_08_17_09_26_30.png)

**Comment by equinusocio** [comment]
Thank you.

Note for me:
https://github.com/equinusocio/vsc-material-theme/blob/master/src/themes/theme-template-color-theme.json#L832
