### ISSUE TITLE
Italic font

### ISSUE THREAD

**Issue by martinezguillaume** [equinusocio/vsc-material-theme#24]
Hello, is it possible to have italic font in this theme ? Like this : (const & default for example)
![image](https://cloud.githubusercontent.com/assets/17292331/25703683/cdda69bc-30d6-11e7-9f49-2420fd0f7ccd.png)

Thanks ! It's an awesome theme 💯  ! ❤️

**Comment by equinusocio** [comment]
This a personal preference style, if you want it you have to edit your local theme installation. I can't delivery this change globally, i'm sorry.
