### ISSUE TITLE
Feature Request: Workspace Icon

### ISSUE THREAD

**Issue by jabacchetta** [equinusocio/vsc-material-theme#241]
As documented [here](https://stackoverflow.com/questions/51578984/make-root-folders-stand-out-in-explorer-for-vscode/51583021#51583021) and [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_editor), VS Code supports root folder icons.

It'd be great to see one added for Material Theme.

**Comment by equinusocio** [comment]
Note
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
