### ISSUE TITLE
Contrast text in theme

### ISSUE THREAD

**Issue by GrimLink** [equinusocio/vsc-material-theme#244]
Many elements have bad contrast.
The main issues are the treeview and the status bar text.

Please change the text contrast or make an option for this.

**Comment by equinusocio** [comment]
Hi, tru the high contrast theme variants.

**Comment by equinusocio** [comment]
Hi, tru the high contrast theme variants.

**Comment by GrimLink** [comment]
@equinusocio that makes its a little better.
But still bad.

I of course tried it →
