### ISSUE TITLE
Increase hover element highlighting in context or topbar menus (custom titlebarstyle mode)

### ISSUE THREAD

**Issue by Guema** [equinusocio/vsc-material-theme#245]
I feel that only applying accent color on the hovered element's text is too discreet.

The hovered element needs its background to be colored according the theme. 

![image](https://user-images.githubusercontent.com/8943532/44513093-bd9c4e00-a6bc-11e8-94e0-93842b2f8784.png)

**Comment by equinusocio** [comment]
Thank you
Row to change `"menu.selectionBackground": "{{variant.scheme.inactiveSelectionBackground}}",`

**Comment by equinusocio** [comment]
@Guema If you want you can test this fix by adding a [theme customisation](https://github.com/equinusocio/vsc-material-theme#override-theme-colors) to your settings file:

```js
"editor.tokenColorCustomizations": {
    "[Material Theme VARIANT]": {
        "menu.selectionBackground": "HEXCOLOR50",
    },
},
```

Replace `HEXCOLOR` with the color based on your theme variant. Go [here](https://github.com/equinusocio/vsc-material-theme/tree/master/src/themes/settings/specific) and pick the value of `lineHighligh` key from the variant file. So, for example, if you are using Ocean you will have `"menu.selectionBackground": "#00000050",`
