### ISSUE TITLE
White text on a white background

### ISSUE THREAD

**Issue by Serega124** [equinusocio/vsc-material-theme#246]
**Describe the bug**
In the Issue Reporter's drop-down lists I see white text on a white background.

**To Reproduce**
1. Select any dark Material theme
2. Click on Help - Report Issue
3. Select any drop-down list

**Expected behavior**
White text on a dark background

**Screenshots**
![1](https://user-images.githubusercontent.com/5006548/44546619-274e4380-a721-11e8-8d5a-0060c06667bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.17134
 - VSCode: 1.26.1 and 1.27-insider
 - vsc-material-theme: v2.3.0

**Comment by equinusocio** [comment]
@Serega124 Can you check if you have the same issue inside the new settings view?

**Comment by equinusocio** [comment]
@Serega124 You should report this issue to the vscode team. Feel free to refer this issue if you want.
