### ISSUE TITLE
Feature request: cabal icon

### ISSUE THREAD

**Issue by azdanov** [equinusocio/vsc-material-theme#247]
[Cabal](https://www.haskell.org/cabal/) is used with Haskell projects to denote package metadata and build information. Configuration files use `*.cabal` extension.

Here's a logo in _SVG_: https://www.haskell.org/cabal/images/Cabal.svg.

Would it be possible to integrate a new _cabal_ icon into _material-theme_?

**Comment by equinusocio** [comment]
Done  in next release
