### ISSUE TITLE
Unable to call any Material design theme command

### ISSUE THREAD

**Issue by Guema** [equinusocio/vsc-material-theme#249]
System : Windows 10 x64
VSCode 1.26.1 x64
Lang : Fr-fr
Extensions : Material Theme 2.4.1

Repro steps :
- Open command menu
- Try to exec any Material design theme command

BUG : 

![image](https://user-images.githubusercontent.com/8943532/44821159-66363a80-abf4-11e8-9250-9bc04bf4dd6c.png)

none of them work.
I didn't get anything relevant in console for Material Design Theme, so i suppose it's useless to add it here.
Thanks.

**Comment by SilverMight** [comment]
Receiving the same issue on Arch Linux x64

**Comment by SidIcarus** [comment]
Also experiencing this on MacOS 10.13.6
VSCode: 1.6.1
Material Theme Version: 2.4.1

**Comment by equinusocio** [comment]
We are investigating about this issue. We will release an hotfix very soon. Thank you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by equinusocio** [comment]
This fix is out now with `2.4.2`. Can you test it?

**Comment by Guema** [comment]
Seams to work for me after installing and restarting vscode entierly !
