### ISSUE TITLE
Theme broken with new VSCode version 1.12.0

### ISSUE THREAD

**Issue by Fenwil** [equinusocio/vsc-material-theme#25]
![screen shot 2017-05-04 at 15 45 57](https://cloud.githubusercontent.com/assets/2475912/25719732/ca7322c8-30e0-11e7-9a73-3e0329c677f4.png)
You can see more info here: https://code.visualstudio.com/updates/v1_12#_workbench

**Comment by equinusocio** [comment]
Yes, the release is ready.

**Comment by equinusocio** [comment]
0.0.12 is out
