### ISSUE TITLE
Why my color scheme isn't the same of the screenshot?

### ISSUE THREAD

**Issue by joaodematte** [equinusocio/vsc-material-theme#251]
http://prntscr.com/kotyr9
http://prntscr.com/kotyz3

the color scheme of the screenshot that you show us the theme isn't the same as the theme have

**Comment by LasaleFamine** [comment]
Hi @joaodematte, I think you are using the "Palenight" variant of the theme, but the piece of screenshot you got from the main Material Theme screenshot is about the "Ocean" variant of the theme.
Checkout [this section](https://github.com/equinusocio/vsc-material-theme#activate-theme) of the readme and just select your favourite variant of the Material Theme through VSCode configurations.

Let me know if this won't solve your problem.
