### ISSUE TITLE
Add clearer border on panel

### ISSUE THREAD

**Issue by kbrose** [equinusocio/vsc-material-theme#253]
**Is your feature request related to a problem? Please describe.**
The panel border is not visible on some themes.

**Describe the solution you'd like**
Add a more clear border. I'm a fan of using the `editorRuler.foreground` color for the `panel.border`.

**Describe alternatives you've considered**
I've just been hacking the local installation to change the panel border, but this is not ideal when setting up a new computer.

**Additional context**
Current palenight style:
![screenshot from 2018-09-03 10-45-09](https://user-images.githubusercontent.com/4053170/44995055-05499200-af67-11e8-8e35-55a43caa94fa.png)

Suggested palenight style (use the `editorRuler.foreground` color for `panel.border`)
![screenshot from 2018-09-03 10-50-29](https://user-images.githubusercontent.com/4053170/44995149-56f21c80-af67-11e8-8839-3e5f46fa673f.png)

**Comment by equinusocio** [comment]
Hi @kbrose. Material Theme provide different High Contrast theme variant that you can use to improve the editor areas recognition. Also you can customise your own theme installation through the powerful vscode settings, for more info please check this section of the readme https://github.com/equinusocio/vsc-material-theme#override-theme-colors
