### ISSUE TITLE
Applying material theme makes some of the text italic

### ISSUE THREAD

**Issue by mbaljeetsingh** [equinusocio/vsc-material-theme#255]
**Describe the bug**
When I change the theme to Material Theme, some of the text in the editor turns italic. When I change the theme back to any default vscode theme then it is not italic.

**Expected behavior**
Text should remain the same.

**Screenshots**
You can take a look at the import lines in both the screenshots.
**With Dark+ Theme**
![image](https://user-images.githubusercontent.com/872762/45376488-8ebb2d00-b615-11e8-9dbe-4bd6d8e87766.png)

**With Material Dark Theme**
![image](https://user-images.githubusercontent.com/872762/45376472-83680180-b615-11e8-9242-2741eced9796.png)

**Comment by equinusocio** [comment]
VSCode provide powerful settings to override installed extensions. Since this is a personal preference you can change this behaviour inside your settings file:


More info here:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors


```json
"editor.tokenColorCustomizations":{
   "[Material Theme VARIANT]":{
      "textMateRules":[
         {
            "scope":[
               "Keyword",
               "Storage",
               "keyword.control",
               "variable.language",
               "variable.language",
               "entity.name.method.js"
            ],
            "settings":{
               "fontStyle": ""
            }
         }
      ]
   },

}
```
