### ISSUE TITLE
Icon request: add icon for .alioth file

### ISSUE THREAD

**Issue by dn-ezr** [equinusocio/vsc-material-theme#257]
Thank you for developing this perfect theme, I can't leave it now.
I'll be appreciate if we can see icons for the programming language named "alioth".
"alioth" is a new language developed by myself to work on operating system level.
Its main picture is a little cat like this:
![](https://www.dn-ezr.cn/assets/i/icon_with_A.png)
I have already made a version with size of 128*128:
![](https://www.dn-ezr.cn/assets/i/icon_128.png)

**Comment by LasaleFamine** [comment]
Hi @dn-ezr, thank you for your interest. 

I think we can't add any type of file as icons, maybe is better to know if it will be used for more than one user.
I think also that we don't have the right knowledge about your new programming language `alioth`. 
Anyway, our icons are original and developed by @equinusocio, so I think this will take time and effort if we need to add this new one.

You can always customize your installed theme adding this new icon if you want.

Can you share with us some resources about your new programming language so we can at least understand the current popularity?

**Comment by dn-ezr** [comment]
I'm sorry to trouble with my question, that was my fault.
The development of first stable version of `Alioth` compiler is still in progress.
It runs on linux64 platform by now, generate machine code via `LLVM`.
The compiler I'm working on generates software, which runs properly without support of any other runtime environment.
But the compiler is still functionally incomplete so I can't publish it right now.
Here is the repository address of the compiler `http://www.dn-ezr.cn:3000/dn-ezr/alioth.git`
Anyway, thank you very much for your reply, I will keep working hard developing this programming language.

**Comment by equinusocio** [comment]
Hi @dn-ezr. I'm sorry but we can't add the Aliot icon right now since it sounds  more like a "personal project" than a world-wide programming language. Also the logo should be a vector image that must be recognised at small size.
