### ISSUE TITLE
Changelog on the cloud

### ISSUE THREAD

**Issue by LasaleFamine** [equinusocio/vsc-material-theme#258]
As discussed with @equinusocio, we will save our changelog within an online service as structured content and load them inside the webview of our changelog. 

The choice could be: https://www.sanity.io/

**Comment by equinusocio** [comment]
@LasaleFamine Any update? We have to pospone this issue?

**Comment by LasaleFamine** [comment]
They're thinking about implementing a new option for this problem, see: https://github.com/sanity-io/sanity/issues/1009#issuecomment-430384350

I'm afraid this would be a problem for all the solution/alternative we can find since it is likely a security problem. 

Just wait few more days and let's see what happens.

**Comment by kmelve** [comment]
Protocol and wildcard support is now deployed, so now you should be able to implement this 👍 

Available on [manage.sanity.io)(https://manage.sanity.io) now, and soon in the CLI https://github.com/sanity-io/sanity/pull/1093
