### ISSUE TITLE
Scroll jank

### ISSUE THREAD

**Issue by radum** [equinusocio/vsc-material-theme#259]
With the latest version of VSCode 1.27.1 the performance of the editor is really bad.

There is scroll jank and the all interactions are very sluggish. Switching to one of the default ones works fine.

I removed all extensions and settings and installed only the theme and the same issue appears. So its not because of an extension.

I tried the insider build of VSCode with no extensions and just the theme and the same issue.

Something is slowing the entire thing down.

I will edit my post with a video to show how it works.

**Comment by equinusocio** [comment]
I can't reproduce this issue. Can you try on other machine?

**Comment by radum** [comment]
Here is a demo https://youtu.be/wqCfuiHZCvw recorded at 60fps.

You can see that with the default theme the scroll is fast and snappy. You can't see me scrolling but the scrollbar follows my scroll position.

Once I switch the jank can be seen, also the scroll bar is always behind my actual scrolling, once I'm done I still need to wait for 1s or 2 to settle.

**Comment by LasaleFamine** [comment]
@equinusocio I don't think soo. 

I think this isn't a theme problem, I think it actually can't be since the theme is doing nothing more than changing settings and icons. 

So strange. @radum did you try with another "custom" theme instead of one of the default and checking what happens?

**Comment by radum** [comment]
@equinusocio Yeah with all variants.

@LasaleFamine Good point, I tried others and its kind of the same. I never actually looked at the code and now I realise that there is nothing there that could break it to be honest.

To be honest it all started happening since I upgraded to 1.27, before it was ok. I will try and open a ticket on Vscode.

**Comment by stalkerg** [comment]
I have the same problem, Material theme slower than other (all material variants). 
My system not so fast and it is annoying.
