### ISSUE TITLE
Background color of ellipsis for collapsed panels

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#260]
**Describe the bug**

Collapsed panels

![image](https://user-images.githubusercontent.com/7588612/45513406-7e808a80-b79a-11e8-9e02-a35e08e3621d.png)

**To Reproduce**

Open the VSCode panels. Decrease the width of VSCode to make the panels collapsed.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by equinusocio** [comment]
I can't reproduce this issue on Mac. Have you tried to:

1. Remove the theme
2. Clean all the theme related settings
3. Reboot
4. Reinstall the theme

**Comment by neilsustc** [comment]
I found that it seems to be an issue of vscode insider build...
v1.27.1 portable - no problem
v1.28.0 insider build - has this problem even with default Dark+ theme

Sorry
