### ISSUE TITLE
More contrast in the scroll bar

### ISSUE THREAD

**Issue by RichieAHB** [equinusocio/vsc-material-theme#262]
Unfortunately I (and some others) have the misfortune of occasionally using VS Code on a desktop without a scroll wheel on the mouse, so have to resort to using the scrollbar. Currently the scrollbar is practically invisible (I'm using Material Theme Ocean) so I actually have to change away from the theme in order to get a better idea of where the scrollbar is. I know others may find it distracting but it would be nice to have a higher contrast option. Other than that I love it, thanks.

**Comment by equinusocio** [comment]
I agree, we will fix this next release. You can add a temp fix by customizing it through the settings. Or you can use code minimap as navigator (it works also as scrollbar)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RichieAHB** [comment]
A) thank you, that was a lightning response.
B) thanks for the minimap suggestion - my muscle memory is a bit too strong
but I will try!

**Comment by equinusocio** [comment]
Check the readme for more details about the customization. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
