### ISSUE TITLE
Floating bar

### ISSUE THREAD

**Issue by guledali** [equinusocio/vsc-material-theme#264]
![screenshot 122](https://user-images.githubusercontent.com/20647282/45927030-01d57500-bf2d-11e8-86c2-26154e912319.png)

I love vsc-material-theme  but it would feel more like an app if the bar had more emphasises like the image above

**Comment by equinusocio** [comment]
Hi @guledali. From your screenshot i can notice that you aren't using material theme at all. Have you activated it by following this https://github.com/equinusocio/vsc-material-theme#activate-theme?

**Comment by guledali** [comment]
@equinusocio Here is an example of the current material theme
![screenshot 120](https://user-images.githubusercontent.com/20647282/45987386-6863ab80-c071-11e8-9605-4d604a6449b6.png)

It's completely flat there is no distinction between the top section and main section.
