### ISSUE TITLE
UX improvement with slight lines

### ISSUE THREAD

**Issue by mimamuh** [equinusocio/vsc-material-theme#265]
Hi, 

I like the clear appeareance of the material themes. There is only one issue I always get: It is hard to see were the line is to drag the sidebar or terminal and resize them as it is only color and not visually seperated. Somehow that is the principle, but I think it is a little bit too much as I always have to find out with my mouse were the dragable line is. Some visual hint would be good at least to have at least the line a little bit brighter or darker. Right now it is a paint. Would it be a option to change that?

**Comment by equinusocio** [comment]
Hi @mimamuh. Material Theme provides different variant. Each **High Contrast** variant improve the area definition and recognition of the UI. Please consider to use these variants.
