### ISSUE TITLE
Make arg key and arg value have different colours

### ISSUE THREAD

**Issue by tiagocborg** [equinusocio/vsc-material-theme#266]
This is just a cosmectic change that I think it would be nice to have.

When you have the following code:
`random_var = models.Charfield('max_lenght=20, null=True, help_text='A random variable')`

```max_lenght``` and its value ```20``` will have the same colour, and the same goes to ```null``` and ```True```.

This is not a big deal, but I think it would make readability a little better.

Thanks for the good work!

<img width="606" alt="captura de tela 2018-09-26 as 15 43 25" src="https://user-images.githubusercontent.com/6026596/46101724-0d31d600-c1a3-11e8-938e-78ee5c9e876a.png">

**Comment by equinusocio** [comment]
@tiagocborg Can you specify the language we talking about?

**Comment by httpsterio** [comment]
after a quick google I think it's either a Django or just Python snippet he posted.

**Comment by equinusocio** [comment]
I close this due to inactivity.
