### ISSUE TITLE
[Icon Request] Add icon for MATLAB (.m) files

### ISSUE THREAD

**Issue by choffa** [equinusocio/vsc-material-theme#267]
Currently .m files defaults to objective-C and therefore the C icon. This is not wrong per se, but I would like to be able to change this to a matlab icon as this is the only types of .m files I work with.

**Comment by equinusocio** [comment]
Hi @choffa. Can you try adding this to your setting file?

```json
"files.associations": {
  ".m": "matlab"
},
```

**Comment by choffa** [comment]
I have. The files are recognised as MATLAB files by VSCode, but they are not assigned the correct icon.

**Comment by Pedro-Mendes** [comment]
Hi @choffa 

Just to let you know, there is a similar issue on https://github.com/vscode-icons/vscode-icons/issues/128
Let's follow up there too, to see if we can fix this.

cc @equinusocio

**Comment by choffa** [comment]
I also found a similar issue on https://github.com/PKief/vscode-material-icon-theme/issues/164. Here they seem to solve it using an internal `<extension>.files.associations` attribute.

**Comment by choffa** [comment]
Still doesn't work for me, as Material Theme doesn't have the internal attrib mentioned above. I also don't think that should be necessary, but that would make this an VSCode issue instead...

**Comment by equinusocio** [comment]
@choffa We talked about this issue and we'll only provide the matlab icon by fixing [this line](https://github.com/equinusocio/vsc-material-theme/blob/master/src/icons/partials/fileExtensions.js#L145). We will not provide any type of fix/workaround since we think is out of the project scope.
