### ISSUE TITLE
Export icon theme as separate extension

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#269]
Hi, what do you think by exporting icon theme as a separate extension? I really love your icon theme, but I don't want to use the theme so I need to keep it in my extension list to use these beautiful icons, maybe you can create a separate extension only for icons?

**Comment by equinusocio** [comment]
Hi @svipben. We talked about this and we agree that separating the icons from the theme can be a good thing also in terms of codebase management. 

Material Theme icons are designed to match the ux of the theme so using them outside Material Theme can generate some issue, but we'll investigate about how to facing this change.

**Comment by svipben** [comment]
Thanks, if any help is needed, feel free to ask :)

**Comment by equinusocio** [comment]
Hi @svipben we are almost ready to release this update. Also the next Material Theme update will be available only for `vscode 1.31+` users.

**Comment by svipben** [comment]
Good news! I guess this can be closed then 👍

**Comment by equinusocio** [comment]
@svipben We released the February release and Material Theme Icons as separated extension. Please feel free to open a new issue if you encount some weird behaviours :D
