### ISSUE TITLE
Add gRPC .proto file icon

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#274]

**Comment by equinusocio** [comment]
Hi @svipben, what icon we should use?

The grpc logo?
https://grpc.io

**Comment by svipben** [comment]
![5a7bfe09-b656-4e2f-be00-da7ba0d8c595](https://user-images.githubusercontent.com/10441177/47373774-2d4aab80-d6f5-11e8-8acb-e5e12d379eb2.jpeg)

Maybe something like this?

**Comment by svipben** [comment]
Best will be this icon: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_protobuf.svg
