### ISSUE TITLE
Add all icons to the languageIds

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#276]
The current list is very small even if there are way more icons. The problem is if I create a new file which is Untitled and set the language to for e.g. JavaScript it shows me simple icon, to enable JavaScript icon I need to add `"javascript": "_file_js"` to the `languageIds`.

```
  "languageIds": {
    "git": "_file_git",
    "ng-template": "_file_angular",
    "haxe": "_file_haxe",
    "hxml": "_file_haxe",
    "polymer": "_file_polymer",
    "matlab": "_file_matlab",
    "makefile": "_file_settings"
  },
```

**Comment by equinusocio** [comment]
@svipben Can you help with a PR?

**Comment by svipben** [comment]
@equinusocio Yes :)

**Comment by equinusocio** [comment]
@svipben Are you working on that?

**Comment by svipben** [comment]
@equinusocio Yes, today I will create a PR.

**Comment by svipben** [comment]
@equinusocio PR is already opened: https://github.com/equinusocio/vsc-material-theme/pull/282

**Comment by equinusocio** [comment]
Merged
