### ISSUE TITLE
Material Theme Icon for VSCode Like in ST3 Material Theme

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#28]
Are you have a plans to create material icon for VSCode?

![06-05-2017 02-52-14](https://cloud.githubusercontent.com/assets/20873402/25771466/350576c8-3207-11e7-8b81-3120677d2fdd.png)

**Comment by equinusocio** [comment]
Maybe :)
At the moment you can convert this by yourself 
https://github.com/equinusocio/vsc-material-theme/blob/master/logo.png

**Comment by equinusocio** [comment]
[vsc-material-theme-appicon.zip](https://github.com/equinusocio/vsc-material-theme/files/989048/vsc-material-theme-appicon.zip)
