### ISSUE TITLE
Comments color too low contrast

### ISSUE THREAD

**Issue by chris-nikolov** [equinusocio/vsc-material-theme#280]
Hey,

That's a really great theme. I have 1 issue with it, and I edit the files manually for that after each update, so I decided to post here.

Basically, the comments color is REALLY low contrast and very very hard to see if you are not forcing yourself (I don't have issues with my eyesight, I've checked :D). It can be easily overlooked which is not ideal.

I suggest bumping it up. For example, in the "darker" themes from #4A4A4A to #848484 or simply making this configurable in settings.

Will be great if others share if this impacts them as well.

Thanks

**Comment by equinusocio** [comment]
Hi @chris-nikolov , this issue is a duplicated of many other similar issue. Please check this readme section to unlock the power of vscode settings (that are persistent) :)

https://github.com/equinusocio/vsc-material-theme#override-theme-colors
