### ISSUE TITLE
Handlebars icon

### ISSUE THREAD

**Issue by svipben** [equinusocio/vsc-material-theme#281]
Even if `"hbs": "_file_handlebars",` is defined there's no such icon.

**Comment by equinusocio** [comment]
I can't reproduce this:
<img width="130" alt="screenshot 2018-10-29 at 15 39 14" src="https://user-images.githubusercontent.com/10454741/47657153-d16aa180-db90-11e8-98f9-9efaf2666413.png">


Do you have installed the extension to handle `.hbs` files?

**Comment by svipben** [comment]
@equinusocio You're right I was without an extension 😄
