### ISSUE TITLE
Support new dirty file indicator

### ISSUE THREAD

**Issue by Ash258** [equinusocio/vsc-material-theme#290]
**Is your feature request related to a problem? Please describe.**
Visual Studio Code presented new dirty file indicator in 1.29 November update (see: https://code.visualstudio.com/updates/v1_29#_new-theme-colors)

**Describe the solution you'd like**
Indicator should respect extension wide color / settings. I 

**Additional context**

![Indicator](https://i.imgur.com/R88klIg.png)

Settings:

```json
	"materialTheme.accent": "Yellow",
	"workbench.colorTheme": "Material Theme Darker High Contrast",
	"workbench.iconTheme": "eq-material-theme-icons-darker",
```

**Comment by equinusocio** [comment]
We will set `tab.activeModifiedBorder` to use the same sidebar text color. We don't want to pollute the UI with a lot of accent indicators and borders (we don't think that this indicator must be visible like the selected tab indicator)
