### ISSUE TITLE
Request: tone down the colour of Python docstring

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#296]
**Is your feature request related to a problem? Please describe.**

Python docstring is more like a comment rather than a string. Currently, the highlight is sort of distractive...

![image](https://user-images.githubusercontent.com/7588612/50045196-821bfa00-0086-11e9-8562-ac54ee88bd4e.png)

**Describe the solution you'd like**

Make its colour closer to that of a comment

![image](https://user-images.githubusercontent.com/7588612/50045222-dfb04680-0086-11e9-88f0-150bd301cb4b.png)

**Comment by equinusocio** [comment]
Hi @neilsustc. Please note if strings share the same `docstring` scope they will be "grayish" too.

**Comment by neilsustc** [comment]
> if strings share the same `docstring` scope they will be "grayish" too

I think it is reasonable

> Can you paste a code snippet?

Sure

```Python
str1 = "double-quoted string"
str2 = 'single one'

# Python comment

def complex(real=0.0, imag=0.0):
    """(Here comes a multi-line doc string)
    Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    pass
```

**Comment by neilsustc** [comment]
Here is an example from PyCharm (a really popular Python IDE)

![image](https://user-images.githubusercontent.com/7588612/50047904-c7f0b680-00b6-11e9-85a4-73cedf84736f.png)
Source: [Using Docstrings to Specify Types - Help | PyCharm](https://www.jetbrains.com/help/pycharm/using-docstrings-to-specify-types.html#c00de15c)

**Comment by equinusocio** [comment]
Fixed from next release
<img width="419" alt="screenshot 2018-12-26 at 20 31 09" src="https://user-images.githubusercontent.com/10454741/50455271-394d2680-094d-11e9-9a49-cbae3b73d60c.png">
