### ISSUE TITLE
[Icon Request]: Add icon for Terraform files

### ISSUE THREAD

**Issue by willsoto** [equinusocio/vsc-material-theme#297]
_Thanks for this great theme and all the hard work you put into it!_

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would love to see an icon for [Terraform](https://www.terraform.io/) (`.tf`) files

**Describe alternatives you've considered**
N/A

**Additional context**

<img width="109" alt="screen shot 2018-12-17 at 7 04 27 pm" src="https://user-images.githubusercontent.com/2791730/50123463-c5b16800-022e-11e9-830a-1e0b2c15014e.png">

**Comment by equinusocio** [comment]
Hi @willsoto Can you move the issue to this repo?
https://github.com/equinusocio/vsc-material-theme-icons/issues

We are going to separate icons from the theme

**Comment by equinusocio** [comment]
#Ref: https://github.com/equinusocio/vsc-material-theme-icons/issues/6
