### ISSUE TITLE
Material Theme for VCL Applications (Delphi)

### ISSUE THREAD

**Issue by CharlieEtienne** [equinusocio/vsc-material-theme#302]
I just released a Material (Dark) Theme for VCL Applications (for Delphi users for example), inspired by yours.

https://github.com/CharlieEtienne/material-vcl

**Comment by equinusocio** [comment]
Hi @CharlieEtienne thank you for your work. We add only portings that implment all the theme variants. If you want this project to be added to the official portings keep working on it to add other variants.

**Comment by CharlieEtienne** [comment]
Thanks @equinusocio. I will think about it. Is it possible to get the full list of colors and accents for all variants ? It would help me a lot !

**Comment by equinusocio** [comment]
These are the basic colors used for the syntax:
```json
"white": "#ffffff",
"black": "#000000",
"red": "#FF5370",
"orange": "#F78C6C",
"yellow": "#FFCB6B",
"green": "#C3E88D",
"cyan": "#89DDFF",
"blue": "#82AAFF",
"paleblue": "#B2CCD6",
"purple": "#C792EA",
"brown": "#C17E70",
"pink": "#f07178",
"violet": "#bb80b3"
```

Here you can find the variant specific colors:
https://github.com/equinusocio/vsc-material-theme/tree/master/src/themes/settings/specific
