### ISSUE TITLE
Style React propTypes configuration

### ISSUE THREAD

**Issue by mikeerickson** [equinusocio/vsc-material-theme#306]
**Describe the bug**

Curious if you could add support for applying syntax coloring for React component propTypes definition (see screenshot)

 
![image](https://user-images.githubusercontent.com/183153/51353407-6a5cda80-1a65-11e9-900f-4606a0a91900.png)

**Comment by equinusocio** [comment]
Hi @mikeerickson are you using the correct language extension? Are you sure that you're using the official `vsc-material-theme` and not other copies?

As you can see here te correct syntax highlighting for jsx files (using the correct extension javascript-react)

<img width="545" alt="screenshot 2019-01-18 at 09 40 41" src="https://user-images.githubusercontent.com/10454741/51375078-25888080-1b05-11e9-9ca2-36fe6f52c2db.png">

As you can note you are using a very different color scheme (red parameters and yellow curly bracket)

**Comment by mikeerickson** [comment]
Hmmm, AFAIK I know I am, how can I confirm?

**Comment by mikeerickson** [comment]
@equinusocio OK, I have reset theme and snippets, etc.  They are as correct so far as I can tell.  I can see how your settings have the correct color for the `propTypes` but they are definitely different than what I have set here.

I am using Material Theme - Panelnight

![image](https://user-images.githubusercontent.com/183153/51401778-85c8f380-1b00-11e9-9b2c-bfe19f9430a8.png)

**Comment by equinusocio** [comment]
Have you checked the extension i linked? Make sure to use it and using the correct language for jsx files.

**Comment by mikeerickson** [comment]
@equinusocio Yes, I have done both (see screenshots)

![image](https://user-images.githubusercontent.com/183153/51402753-3d5f0500-1b03-11e9-9665-044ba12bd92d.png)

![image](https://user-images.githubusercontent.com/183153/51402801-6089b480-1b03-11e9-8fd9-e7093d157dd7.png)

**Comment by mikeerickson** [comment]
@equinusocio If I am missing something, please let me know.  I believe I have everything configured correctly.  Surely puzzled thats for sure.

**Comment by equinusocio** [comment]
Can you try to remove all theme customisation from your config file?

**Comment by jonnyasmar** [comment]
I'm experiencing this same issue as OP using the primary Material Theme extension that boasts almost 3m+ downloads.

I've tried clearing any theme-related customizations and installing the ES7 extension mentioned above. I've cycled through numerous code-styles beyond just JavaScript React and tried every variation of Material Theme to no avail.

As a matter of fact, I just tested my theme in CodeSandbox and still have the same issue.

Here's the gist of my generated theme: https://gist.github.com/jonnyasmar/4eb1ce30880d74a16f392acabe7f1cde

**Comment by equinusocio** [comment]
Sorry guys we can't still replicate this issue. We will close this for now.
![Kapture 2019-03-17 at 18 42 02](https://user-images.githubusercontent.com/10454741/54495476-7093f980-48e4-11e9-9b04-d5bb3331a6b5.gif)

**Comment by RrNn** [comment]
hey @mikeerickson, I had the same problem. Fixed it by adding the [Babel JavaScript](http://bit.ly/2OqVNrH) extension to vscode. You have to have [Material Theme](http://bit.ly/2OovkuK) too for it to work, I guess.

**Comment by artlp** [comment]
Hi guys sorry to necro this, I'm having the same issue as well. I have babel js installed and no color customizations. With all other themes the syntax is being highlighted, but not with material theme, it's just white https://i.ibb.co/hZ6Qdnp/image.png
