### ISSUE TITLE
Question: will there be a plan to distinguish editor group, sidebar, debug console and statusbar?

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#31]
![image](https://cloud.githubusercontent.com/assets/7588612/25891634/5638cf8e-35a4-11e7-9ddd-5ef47d367f08.png)

At present, there is no boundary between them. And it looks kind of strange for me because I keep imagining some invisible boundaries in my mind. 😂

**Comment by equinusocio** [comment]
The original material theme have no separator and provide a semi-full flat interface. I will add the "contrast mode” but not now. Something like that:
<img width="762" alt="screen shot 2017-05-10 at 11 44 35" src="https://cloud.githubusercontent.com/assets/10454741/25892885/2259f180-3576-11e7-8f90-355f8dc271f4.png">

**Comment by neilsustc** [comment]
👍
