### ISSUE TITLE
Cyan color when using React Components

### ISSUE THREAD

**Issue by barrosfilipe** [equinusocio/vsc-material-theme#312]
Hello guys! 

I just switched to VS Code today and I installed my favorite theme, but I noticed a difference between the colors in between VS Code and Sublime Text. 

The text inside HTML tags when using a React component displays in cyan instead of white just like when using plain HTML or when using the same theme on Sublime Text. Here's a screenshot to try to explain what I mean:

![vscode-react-sublime](https://user-images.githubusercontent.com/25266300/52292894-d2b02500-295c-11e9-97f0-e2e31f2a17e6.png)

Shouldn't this be `white` be default or can I switch to?

Thank you!

**Comment by equinusocio** [comment]
I we will investigate in that. The strange thing is that the react language and javascript babel extensions assign the `meta.tag` scope to the text inside html, causing the wrong highlighting
