### ISSUE TITLE
VSCode Power User button broken

### ISSUE THREAD

**Issue by ajmeese7** [equinusocio/vsc-material-theme#313]
**Describe the bug**
The VSCode Power User button is broken.

**To Reproduce**
1. Download the theme in VS Code
2. Navigate to the extension page
3. Look at button

**Expected behavior**
The button to appear properly like the other buttons, and without the text surrounding the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/17814535/52297868-4c3d1880-2947-11e9-8f79-da5b42aefc27.png)

**Comment by equinusocio** [comment]
Thank you. This will be fixed next release
