### ISSUE TITLE
Design a configurations system integrated with themes

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme#32]
We need a system to write/read user settings (through the vsc api) and customise themes.

**Comment by skbolton** [comment]
For reference do you mean similar to the sublime setup for the theme with the menus?

**Comment by equinusocio** [comment]
As first step we can just implement a way to allow user to set the accent color (now generated at build-time, so hardcoded). I things we need to read user settings (there is API for that) and pass the setting value to the theme.

**Comment by skbolton** [comment]
Yeah I will dig around in their documentation this weekend and see what we can do. Shouldn't be too hard to do.

**Comment by equinusocio** [comment]
Checke here:
- https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration
- https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfigurationdefaults
- https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands
- https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by equinusocio** [comment]
@skbolton, @OctoD will work on this and we switch all to typescript
