### ISSUE TITLE
Google chrome DevTools extension

### ISSUE THREAD

**Issue by SebastianWesolowsik** [equinusocio/vsc-material-theme#321]
**Describe the solution you'd like**
Extension Google Chrome to change devtool default color.

**Additional context**
I saw possibility change default color. Maybe someone do this extension or want help me to do it ?

https://developers.google.com/web/tools/chrome-devtools/ui

Use custom color is experimental setting
chrome://flags/#enable-devtools-experiments

**Comment by equinusocio** [comment]
Hi @SebastianWesolowsik we can provide you the official colors but we are not informed about chrome extensions development.
