### ISSUE TITLE
missing material icons 

### ISSUE THREAD

**Issue by bibblebabl** [equinusocio/vsc-material-theme#322]
I must have missed something. where are the icons and where do I get them now?

![2019-02-12 12 23 33](https://user-images.githubusercontent.com/9008978/52625035-2b357400-2ec1-11e9-817d-6e7300b9481e.png)

**Comment by pingshunhuangalex** [comment]
I had the same issue today, both the file tree and the tab...

![image](https://user-images.githubusercontent.com/17170199/52626384-272c4500-2f07-11e9-83ca-6a7636434188.png)

**Comment by equinusocio** [comment]
Hi. Please check the release notes inside the extension (and #269). From 2.7.0 the icons will live as [separated extension](https://github.com/equinusocio/vsc-material-theme-icons) which you can install by searching for "material theme icons" if you have vscode 1.31+

https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons
