### ISSUE TITLE
FS not showing file/directory icons any longer

### ISSUE THREAD

**Issue by mrpharderwijk** [equinusocio/vsc-material-theme#323]
**Describe the bug**
As of version 2.7.0 the filesystem in the sidebar is no longer showing icons when this theme is activated. I have no icon set extensions installed. Even after updating to 2.7.0 and installing the material icons the filesystem doesn't show any icons for directories and files. Downgrading to version 2.6.3 will show the filesystem icons as expected.

**To Reproduce**
1. Go to 'extensions' and update the material theme to 2.7.0
2. Open a workspace/project and see the icons for directories/files are no longer displayed
3. Downgrade material theme to 2.6.3
4. Now in the filesystem you should see the icons as expected

**Expected behavior**
Upgrading to 2.7.0 should show the default icons in the filesystem

**Screenshots**
version 2.6.3
![screenshot 2019-02-12 at 11 41 41](https://user-images.githubusercontent.com/3908096/52630013-5321d900-2ebb-11e9-9cc9-91c86c6ea619.png)
version 2.7.0
![screenshot 2019-02-12 at 11 42 03](https://user-images.githubusercontent.com/3908096/52630014-5321d900-2ebb-11e9-9421-a4e9a2dae69a.png)

**Comment by OctoD** [comment]
duplicated #322

**Comment by equinusocio** [comment]
Thanks @OctoD 😅
