### ISSUE TITLE
Theme Icons won't be applied after installing or switching themes

### ISSUE THREAD

**Issue by Nonag** [equinusocio/vsc-material-theme#324]
When installing or switching to any of the Material Themes, the according icon set is not used anymore. Also the note, telling you about the successful icon switch, won't show up anymore.

Re-installing the theme via the Marketplace or repeatedly switching the theme variants didn't seem to solve the problem.

This only occured to me after upgrading Visual Studio Code to version 1.31.0. I've read something about a window reload being obsolete after installing a new plugin. Also about an issue / feature request regarding the option to turn on/off the auto load of the Material Theme Icon Set. I couldn't find anything about this in the readme though.

Am I missing something?

**Comment by OctoD** [comment]
Icons are now in a different extension. You should first install them, then set your accent and use the theme icon command. Duplicates of #322

**Comment by DJPumpkin** [comment]
In that case, please update https://material-theme.site/
The part that said "File & folders icons included." really mislead me to think i had a bug somewhere in vsc.

**Comment by Nonag** [comment]
@OctoD Thank you for pointing that out. I'm glad I can use those beautiful icons again. However @DJPumpkin is right. It should be mentioned atleast somewhere (apart from release notes), that the icons have moved to a seperate extension ;)
