### ISSUE TITLE
Better overview ruler color for "information"

### ISSUE THREAD

**Issue by yzhang-gh** [equinusocio/vsc-material-theme#325]
**Is your feature request related to a problem? Please describe.**

Currently, the ruler color of "information" looks dim and old fashioned

![image](https://user-images.githubusercontent.com/7588612/52725608-762ab680-2fa9-11e9-9d43-658e099168eb.png)

Theme key `editorOverviewRuler.infoForeground`

(There are "information", "warning" and "error")

![image](https://user-images.githubusercontent.com/7588612/52726040-4334f280-2faa-11e9-9634-6a1676f67d3b.png)

**Describe the solution you'd like**

Would be better to make it brighter

**Comment by yzhang-gh** [comment]
A way to produce an information overview ruler:

- install [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) extension
- set `spellright.notificationClass` to `information`
- type some wrong words

**Comment by yzhang-gh** [comment]
😂

**Comment by equinusocio** [comment]
Hi @yzhang-gh sorry for the late response. I'm working on it right now, available next release (coming very soon)
