### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by igarcido95** [equinusocio/vsc-material-theme#328]
Hello. 
I have installed Material Theme and whereas the Color Theme applies correctly, the custom icons are not automatically applied. Also, under the "Icon Theme" menu I cannot see anything from Material Theme.

I've already tried to reinstall the extension but without luck. 

Thanks

**Comment by equinusocio** [comment]
Hi @igarcido95 please check these duplicated #324 #323 #322. From 2.7.0 material theme icons live as external extension. You need to install it separately
https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons
