### ISSUE TITLE
Main workbench container has wrong background color

### ISSUE THREAD

**Issue by JSteitz** [equinusocio/vsc-material-theme#33]
I use the theme with zoom  -1 and get a vertical line that separates the sidebar from the editor (and many more places).
The actual culprit is the main workbench container that has the color #F3F3F3.
I can't find any ID that would target this one. So maybe you have some more insight and if not this should be reported in VSC.

![_headline scss - int 2017-05-11 14-32-20](https://cloud.githubusercontent.com/assets/677821/25949959/a15e5190-3659-11e7-93e1-66af731299bf.jpg)

**Comment by equinusocio** [comment]
I can't reproduce this issue but i think this is a visual glitch of VSC. I will close for now.
