### ISSUE TITLE
change status bar font color to whiter or light color

### ISSUE THREAD

**Issue by bhavik-knight** [equinusocio/vsc-material-theme#331]
**Is your feature request related to a problem? Please describe.**
It's hard to read fonts on the status bar with the default color scheme. 
Especially on using git, vim - where we can have some useful info from the status bar

**Describe the solution you'd like**
A clear readable font color -> white or light grey or similar

**Describe alternatives you've considered**
Default vs code color scheme has readable fonts in their status bar

**Additional context**

**Comment by equinusocio** [comment]
Hi @bhavik-knight, such kind of customisations are personal. Fortunately vscode allows you to easily customise your local installation. Check this section for more informations:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

The key you have to change is `statusBar.foreground`

**Comment by bhavik-knight** [comment]
Thank you @equinusocio - will try that definitely! I love the material theme overall for everything, it's just in VSC I found this minor thing. 

It's really good work!
