### ISSUE TITLE
[PHP] Wrong Syntax Coloring

### ISSUE THREAD

**Issue by andremacola** [equinusocio/vsc-material-theme#332]
![Captura de Tela 2019-03-11 às 22 29 17](https://user-images.githubusercontent.com/3408809/54168483-781f5280-444d-11e9-8868-390dcc20b940.png)

Copy and paste the code below. The brackets are with the wrong color

```
<?php if ($test) { ?>
	<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae ipsam eius quos voluptate hic recusandae excepturi cum. Dolores vitae sunt optio assumenda soluta aliquam numquam voluptatum modi minima, labore illo.</p>
<?php } else { ?>
	<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae ipsam eius quos voluptate hic recusandae excepturi cum. Dolores vitae sunt optio assumenda soluta aliquam numquam voluptatum modi minima, labore illo.</p>
<?php } ?>
```

**Comment by andremacola** [comment]
hey @equinusocio The update broke the color from $ sign of the variable. I wonder if the brackets would be better in blue and not white? Remember how was in Sublime Text?

VSCODE

![Captura de Tela 2019-03-18 às 00 44 56](https://user-images.githubusercontent.com/3408809/54505540-13656b80-4917-11e9-872f-73e200e8275f.png)

SUBLIME TEXT

![Captura de Tela 2019-03-18 às 00 46 16](https://user-images.githubusercontent.com/3408809/54505590-414ab000-4917-11e9-948d-0045b0ad2162.png)

**Comment by equinusocio** [comment]
HI @andremacola, unfortunately we can find a solution for this issue since vscode doesn't provide a restricted scope to this kind of formatting:
<img width="290" alt="Screenshot 2019-03-18 at 20 58 20" src="https://user-images.githubusercontent.com/10454741/54559671-d81f7700-49c0-11e9-8152-5d4f059ab28f.png">

As you can see it provides us just a generic `source.php meta.embedded.line.php`that we can't target. This is sort of bug because the second curly bracket (the opening one) have a different scope:

<img width="356" alt="Screenshot 2019-03-18 at 21 02 12" src="https://user-images.githubusercontent.com/10454741/54559784-1f0d6c80-49c1-11e9-8a34-b807e081b18e.png">

**Comment by andremacola** [comment]
hey @equinusocio could you check how another themes does that? For example, `Kimbie Dark` have a similar approach and the bracket is working fine.
 
![Captura de Tela 2019-05-20 às 01 25 07](https://user-images.githubusercontent.com/3408809/57996523-62a65480-7a9e-11e9-89de-62c36c8a3f64.png)
![Captura de Tela 2019-05-20 às 01 25 18](https://user-images.githubusercontent.com/3408809/57996525-62a65480-7a9e-11e9-950a-cbad25a6a0d2.png)

**Comment by andremacola** [comment]
For anyone who are interested. A temp fix until the VSCode team fix the https://github.com/microsoft/vscode/issues/74382

```
	"editor.tokenColorCustomizations": {
		"[Material Theme Palenight High Contrast]": {
			"textMateRules": [
					{
						"name": "Html Text Color PHP",
						"scope": [
							"text.html.php"
						],
						"settings": {
							"foreground": "#FFFFFF"
						}
					},
					{
						"name": "Fix Brackets Colors",
						"scope": [
							"meta.embedded.line.php"
						],
						"settings": {
							"foreground": "#89DDFF"
						}
					},
					{
						"name": "IF/ELSE",
						"scope": [
							// "keyword.control.conditional.js"
							"keyword.control.if.php",
							"keyword.control.else.php"
						],
						"settings": {
							"foreground": "#C792EA"
						}
					},
					{
						"scope": [
							"punctuation.definition.comment",
							"comment.block",
							"comment.line",
							"comment.block.documentation"
						],
						"settings": {
							"foreground": "#769DAE"
						}
					},
			]
		},
		"variables": {
			"foreground": "#FFFFFF"
		}
	},
```

PS: I made some personal color changes.
