### ISSUE TITLE
Wrong background color on both palenight

### ISSUE THREAD

**Issue by nicovak** [equinusocio/vsc-material-theme#334]
**Describe the bug**

There is a wrong background color on both `palenight` and `palenight contrast`.
I'm working on a macbook pro retina.

**To Reproduce**

Enable one of `palenight` theme listed above. I tested the others and the issue isn't present. Also you may have really good eye to see the issue :wink: You may need to open the screenshot in big and try different angle...

**Expected behavior**

The color should be the same.
It's really subtle. I pointed It out with red dot and drain the color on photoshop.

**Screenshots**

![LINK](https://i.imgur.com/yMo2ysN.jpg)

**Comment by equinusocio** [comment]
Hi @nicovak, thanks for reporting this. We think this is a vscode render issue, the hex codes defined are exactly the same. :(

https://github.com/equinusocio/vsc-material-theme/blob/master/src/themes/settings/specific/palenight.json#L6

https://github.com/equinusocio/vsc-material-theme/blob/master/src/themes/settings/specific/palenight-hc.json#L6

**Comment by kikomatching** [comment]
I'm also encountering this issue after I updated to:

> Version: 1.40.1
> Commit: 8795a9889db74563ddd43eb0a897a2384129a619
> Date: 2019-11-13T16:49:30.162Z
> Electron: 6.1.2
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Linux x64 4.15.0-72-generic

See attached image below.

![Screenshot from 2019-12-06 17-24-37](https://user-images.githubusercontent.com/27290629/70312009-b7989500-184d-11ea-9d0b-7c38b7b40d95.png)
