### ISSUE TITLE
PowerShell Highlighting Recent Bug

### ISSUE THREAD

**Issue by cmcit-bferg** [equinusocio/vsc-material-theme#335]
**Describe the bug**
Some time very recently (in the last week) a change was made that broke variable highlighting in PowerShell. I luckily have a screenshot of a script from before because it was easier than copy-pasting on my phone and I was explaining split to a friend; it shows very clearly the difference.

**Screenshots**
(Old behavior)
![old](https://user-images.githubusercontent.com/46008360/54558099-3b92b000-4993-11e9-95ef-e5d9a06bb1d2.png)
(New behavior)
![new](https://user-images.githubusercontent.com/46008360/54558104-3e8da080-4993-11e9-86e2-e63b1d165ee7.png)

**Comment by equinusocio** [comment]
Hi @cmcit-bferg, this is a regression of 1e549eff08d320f75a74d7e78aca539ddc2cd987. We will fix it soon.

**Comment by cmcit-bferg** [comment]
This appears to be fixed now. Cheers!
