### ISSUE TITLE
Theme info/warning/error squiggles

### ISSUE THREAD

**Issue by yzhang-gh** [equinusocio/vsc-material-theme#336]
Thanks a lot for fixing #325. Now it becomes

![squiggles](https://user-images.githubusercontent.com/7588612/54641836-08cbe300-4a8b-11e9-93fb-de95491ec95c.png)

The colours of info/warning are confusing. Would love to also have them updated accordingly.

(The theme keys are `editorInfo.foreground`, `editorWarning.foreground` and `editorError.foreground`)

Best

**Comment by equinusocio** [comment]
If i understand, info should be green, warning yellow and error red, right? 

And we will make them more visible.

**Comment by yzhang-gh** [comment]
Sounds good to me, as long as they are consistent with the overview ruler colour 😉.
