### ISSUE TITLE
Theme Light: terminal white text

### ISSUE THREAD

**Issue by ddzy** [equinusocio/vsc-material-theme#337]
**Describe the bug**
VScode@1.33.0 - exploration(user setup)
Material-theme@2.8.0
Cmder@1.3

In the latest version of vscode-exploration, terminal text looks white.

**To Reproduce**

**Expected behavior**

**Screenshots**
![github_issue_1](https://user-images.githubusercontent.com/33921398/54728457-f64fc780-4bb8-11e9-9937-846e57d810ea.png)

**Additional context**

**Comment by equinusocio** [comment]
Hi @ddzy, unfortunately we don't support third-party extensions and we can't reproduce this issue.
