### ISSUE TITLE
Line numbers illegible

### ISSUE THREAD

**Issue by giorgio79** [equinusocio/vsc-material-theme#338]
I read raving reviews about this theme, but out of the box the line numbers are illegible. Why? :)

**Comment by equinusocio** [comment]
Hi @giorgio79 , such kind of customisations are personal. Fortunately vscode allows you to easily customise your local installation. Check this section for more informations:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

The keys you have to change are `editorLineNumber.foreground` and `editorLineNumber.activeForeground`
