### ISSUE TITLE
No italics

### ISSUE THREAD

**Issue by yuritoledo** [equinusocio/vsc-material-theme#339]
Hello.

Is possible to make a flag on VSCode settings, to not apply italic fonts? with Fira code, it is not cool.

Thanks.

**Comment by yuritoledo** [comment]
@equinusocio ?

**Comment by equinusocio** [comment]
Hi @yuritoledo. We faced this argument many times. Vscode provides a good way to customise your local theme installation without compromising updates.

Please check this readme section:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

Here more info about these settings here:
https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

You need to find the scopes you want to change (by using the scope inspector vscode provides) and under the settings set the fontStyle key to an empty string. For example:

```js
"scope":  "variable.language",
"settings": {
    "fontStyle": ""
}
```

**Comment by yuritoledo** [comment]
Thank you @equinusocio !
I always edit the `.vscode/{...}` file hehe
