### ISSUE TITLE
Function expression parameter highlighting not working right

### ISSUE THREAD

**Issue by crownlessking** [equinusocio/vsc-material-theme#340]
Issue Type: <b>Bug</b>

In a typescript (v3.3.3) project, I had this exported constant which is a function. Because the parameter list was getting longer, I decided to align them vertically.

e.g.

```ts
export const getRequest = (
   endpoint: string,
   args = '',
   success?: (json: Promise<any>, dispatch?: Dispatch)=>void,
   failure?: (json: Promise<any>, dispatch?: Dispatch)=>void,
) => {}
```

However, the second parameter (that defaults to an empty string) loss its correct highlighting.
This happened using the "Material theme darker".

It is a minor bug but I thought you guys should know, just in case.

Extension version: 2.8.2
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.4.0-143-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4199)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.61GB (8.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by equinusocio** [comment]
Hi @crownlessking, this is the correct behaviour. 
<img width="536" alt="Screenshot 2019-05-01 at 19 27 58" src="https://user-images.githubusercontent.com/10454741/57031167-3fc71400-6c47-11e9-9eac-f6827ddf4643.png">

The first parameter is considered as variable, the second one is a pure string. The last two are considered as functions. You can check the returned syntax scopes by searching for "scope" in the command palette and click on the parameters.
