### ISSUE TITLE
Monokai Theme

### ISSUE THREAD

**Issue by LeonnardoVerol** [equinusocio/vsc-material-theme#341]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for Sublime Monokay Theme
Ex.: 
- Material Theme Monokai
- Material Theme Monokai High Contrast

**Describe alternatives you've considered**
https://marketplace.visualstudio.com/items?itemName=AdamCaviness.theme-monokai-dark-soda
https://marketplace.visualstudio.com/items?itemName=gerane.Theme-FlatlandMonokai

**Comment by equinusocio** [comment]
Hi @LeonnardoVerol. We don't offer support for third-party schemes. We provide an immersive and consistent UX and to keep this approach we can't support external color schemes.
