### ISSUE TITLE
Question about adding Vim/Neovim port to README

### ISSUE THREAD

**Issue by kaicataldo** [equinusocio/vsc-material-theme#342]
Hi! First off, wanted to just say thanks for the awesome work on this theme! I've been maintaining a [port of this theme for Vim/Neovim](https://github.com/kaicataldo/material.vim) for a little while and am wondering if you would be amenable to adding it to the list of ports in the README. We've had a few contributors already and I'd love to have more people contribute to make it even better!

**Comment by equinusocio** [comment]
Hi @kaicataldo. Awesome work! We can consider to add it to the official portings if you add all the current variant available.

**Comment by equinusocio** [comment]
@kaicataldo Any update about this? We noticed that only the lighter variant is missing.

**Comment by kaicataldo** [comment]
@equinusocio Yes, sorry - I had to step away from open source for a bit while to focus on some personal things. I actually just started working on adding the lighter and ocean variants yesterday - will hopefully have that done in the next few days :)

**Comment by equinusocio** [comment]
Oh yep, also the Ocean is missing 😅

**Comment by kaicataldo** [comment]
The bulk of the work is done! https://github.com/kaicataldo/material.vim/pull/21

The last thing I need to do is update the screenshots.

**Comment by kaicataldo** [comment]
Done! Please let me know what you think (hope it's okay that I made a screenshot that kind of matches the site, but let me know if it isn't :)) https://github.com/kaicataldo/material.vim

**Comment by kaicataldo** [comment]
And thanks again for your patience in all this - I didn't expect to be away from OSS for quite so long :)

**Comment by equinusocio** [comment]
Done! Very great work!
