### ISSUE TITLE
Console have issue with displaying colors for text or links in specific scenario

### ISSUE THREAD

**Issue by princeteck** [equinusocio/vsc-material-theme#344]
When using this theme in VS Code i have found it difficult to use console as their is some theming issue. 
Also sometimes the content in the console is highlighted like when we select all the content in it with mouse. It's really annoying to try to figure out the output. Second image represents this issue.
**please have a look at the image below.** 

**To Reproduce**
****Steps to reproduce the behavior:
1. Open a console in any project, here ionic specifically.
2. press Ctrl + ` 
3. Type the command

**Expected behavior**
this is the same with any other theme color scheme been provided. be it light or dark.

**Screenshots**

![error-1-09-04-19](https://user-images.githubusercontent.com/13074740/55750885-f1689000-5a61-11e9-85c7-3e5754570aeb.png)

![error-2-09-04-19](https://user-images.githubusercontent.com/13074740/55751173-ae5aec80-5a62-11e9-8f29-2d33269a8534.png)

**Comment by equinusocio** [comment]
Hi, we can't replicate this issue on any machine we have. We think the issue is related to your local machine configuration.

**Comment by princeteck** [comment]
I will try it on other machine. but recently after update of the theme, it has reduced.
