### ISSUE TITLE
Coloring inside function calls

### ISSUE THREAD

**Issue by jeff-hykin** [equinusocio/vsc-material-theme#346]
**Describe the bug**
The all of the code in the argument section of function calls are blue.

**To Reproduce**
View:
 ```cpp
//Thread used to read chat messages and send them to the server
            std::thread writer([this, username]() {
                    forever {
                        ClientContext temp_context;
                        Empty temp_empty;
                        std::string input = strip(getPostMessage());
                        if(input == "") continue;

                        Message m = MakeMessage(username, input);
                        // stream->Write(m);
                        Status write_status;
                        write_status = stub_->Post(&temp_context, m, &temp_empty);

                        if(!write_status.ok()) {
                            std::cout << "Problem writing post. Please try again..." << std::endl;
                            return;
                        }
                    }
                });
```

**Expected behavior**
The all of the code in the argument section of function would be normally colored.

**Screenshots**

## When lambda is inside of the function arguments
<img width="980" alt="Screen Shot 2019-04-27 at 12 37 30 AM" src="https://user-images.githubusercontent.com/17692058/56845302-c31de980-6884-11e9-9bc5-42f886d38de9.png">

## When lambda is outside of the function arguments
<img width="1039" alt="Screen Shot 2019-04-27 at 12 38 02 AM" src="https://user-images.githubusercontent.com/17692058/56845310-dc269a80-6884-11e9-85d2-8fe729a56a6b.png">

**Additional context**
I do not use the Material Theme myself (although I appreciate it). I maintain the C++ syntax and 5 of my friends have sent me bug reports of this being messed up, even though it's not a syntax issue, so I figured I post it here. Ideally the code colors would not drastically change when the meaning of the code hasn't changed at all.

The fix can be made by removing the `meta.function-call` tag from the "Function, Special Method" section.

**Comment by equinusocio** [comment]
Hi, we can't replicate this issue using **Better C++ Syntax** extension:
<img width="1173" alt="Screenshot 2019-05-01 at 19 37 00" src="https://user-images.githubusercontent.com/10454741/57031638-810bf380-6c48-11e9-8b56-5a768cd4dd4f.png">

**Comment by jeff-hykin** [comment]
Sorry about that, I didn't realize the external function was affecting it. Here's the full code that should reproduce it:
```cpp
void Client::Timeline(const std::string& username) {
        // 
        // Example 1
        // 
            // 
            // Seperated
            // 
            auto b = (std::string)(var1)
            auto a = func1(b)
            // 
            // Nested
            // 
            auto a = func1((std::string)(var1))
        
        // 
        // Example 2
        // 
            // 
            // seperated
            // 
            auto b = [this, username]() {
                    ClientContext temp_context;
                    Empty temp_empty;
                    return true;
                };
            auto a = std::thread writer( b );
            // 
            // nested
            // 
            auto a = std::thread writer([this, username]() {
                ClientContext temp_context;
                Empty temp_empty;
                return true;
            });
    }
```
<img width="593" alt="Screen Shot 2019-05-02 at 10 46 30 AM" src="https://user-images.githubusercontent.com/17692058/57088358-bc99d280-6cc7-11e9-91f1-24ea6ca53092.png">

**Comment by equinusocio** [comment]
Hi @jeff-hykin, we think there is a problem with the **Better C++ Syntax** extension. If you disable it you will see the fix. This extension assign different language scopes so the theme highlights them differently. I think you should report this issue to the extension authors with scopes screenshots (You can run the tool form the command palette searching for "Scope")

**Comment by jeff-hykin** [comment]
Actually, coincidentally enough, I am the author of Better C++ Syntax haha. The extension is also the source for the VS Code C++ grammar, so if it is a problem with the extension now, it'll be a problem with stock VS Code in a month or two. Many times highlighting issues are caused by the extension because since it is testing changes, but I don't think that is the case here.

<img width="732" alt="Screen Shot 2019-05-06 at 6 36 32 PM" src="https://user-images.githubusercontent.com/17692058/57261592-f7846900-702d-11e9-9540-238b0978fe45.png">

In this situation Ideally all function calls e.g. `afunc();` would be tagged with the `meta.function-call` scope, including everything between the `()`'s. This is in accordance with TextMate naming conventions and is the way many other languages grammar works as well, so I believe the scopes are correct. The issue is that the theme ties the `meta.function-call` with the blue color.
