### ISSUE TITLE
Object literal properties color

### ISSUE THREAD

**Issue by tobdub** [equinusocio/vsc-material-theme#349]
It would be nice to have different colors for JavaScript object literal attributes and values to make them easier to distinguish.

**Comment by equinusocio** [comment]
Hi, can you provide more details?

**Comment by tobdub** [comment]
Sure,
```
let value1 = 1;
let value2 = 2;
let obj = {
  property1: value1,
  property2: value2,
};
```
In a case like this, it would be nice if the properties had a different color to clearly distinguish them from the values.

**Comment by equinusocio** [comment]
Do you se something different?
<img width="232" alt="Screenshot 2019-05-16 at 21 59 59" src="https://user-images.githubusercontent.com/10454741/57883268-fa4d3e00-7825-11e9-9fc3-80f1e38101e8.png">

**Comment by tobdub** [comment]
This is what I see, using the default _Material Theme_
![obj-literal-color](https://user-images.githubusercontent.com/17315410/58539901-9567ef80-81f8-11e9-83b0-75183a187e3b.png)

**Comment by equinusocio** [comment]
We can't replicate this issue. Are you using a javascript syntax extension?

<img width="199" alt="Screenshot 2019-05-29 at 11 32 49" src="https://user-images.githubusercontent.com/10454741/58546409-905d6d00-8205-11e9-9147-a547090948f5.png">

**Comment by jabacchetta** [comment]
I'm seeing the same as @tobdub, with no other theme extensions installed other than this one.

**Comment by equinusocio** [comment]
That's the point guys :) The basic vscode highlights aren't good since they don't cover all the syntax scopes.

**Comment by iiKulakov** [comment]
Changed language to typescript, and now **obj : key** looks ok.

<img width="189" alt="Screenshot 2019-06-27 at 08 36 12" src="https://user-images.githubusercontent.com/22544922/60270853-dd8d3700-98b6-11e9-99dd-7cbc10fea75b.png">

**Comment by joshuadavidson** [comment]
I too am seeing the same issue as @tobdub. Changing language to Typescript did nothing for me. Anyone able get this to work?
