### ISSUE TITLE
Add support for statusBarItem.remoteBackground

### ISSUE THREAD

**Issue by misolori** [equinusocio/vsc-material-theme#350]
With the recent support for [VS Code Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development), there's a new color token for remote indicators. You can now set the foreground & background color for a remote indicator via `statusBarItem.remoteForeground`, `statusBarItem.remoteBackground`:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/35271042/57100843-c6760280-6cd4-11e9-8267-ab4e577e46e5.png">

I'll submit a PR with some suggested colors (based on the activity bar badge colors), let me know if you've got any questions or concerns.

**Comment by equinusocio** [comment]
Thank you! We are releasing a new version with this fix :)
