### ISSUE TITLE
Active snippet choice background colour

### ISSUE THREAD

**Issue by Ash258** [equinusocio/vsc-material-theme#352]
**Describe the bug**
Snippet choice active background should have accent colour.

**To Reproduce**
1. Create snippet which has choice option
    1. `"Test":{"prefix": "whatever", "body": "${1|alfa,beta,test|}"}`
2. Invoke this snippet inside any file
3. See that active selected item background is pretty hard to see

**Expected behavior**
Background of selected item should respect accent color

**Screenshots**

![image](https://user-images.githubusercontent.com/13260377/57182490-f1608200-6e9f-11e9-8a2c-bf0c2fe44844.png)

```
Version: 1.34.0-insider
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:22:05.899Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
MaterialThemeExtension: 2.8.2
```

**Comment by equinusocio** [comment]
Hi , since this is a personal taste we suggest to use the awesome vscode api to customise your local theme installation. Check the readme section:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

```js
"editor.tokenColorCustomizations": {
    "[Material Theme VARIANT]": {
        "editorSuggestWidget.selectedBackground": "COLOR"
    },
},
```
