### ISSUE TITLE
Material Lighter theme has unreadable selections

### ISSUE THREAD

**Issue by gencer** [equinusocio/vsc-material-theme#353]
**Describe the bug**
Selections or Find Result in IDE are invisible.

**To Reproduce**
1. Activate `Material Theme Lighter`
2. Select a popup text or find anything across workspace
3. You will see that texts are invisible/unreadable.

**Expected behavior**
Be able to see texts on selections

**Screenshots**
![image](https://user-images.githubusercontent.com/1711576/57291070-65c93a00-70c7-11e9-8235-654ee31f5616.png)

![image](https://user-images.githubusercontent.com/1711576/57291099-75e11980-70c7-11e9-98fd-6dbcb2e2b302.png)

![image](https://user-images.githubusercontent.com/1711576/57291320-df612800-70c7-11e9-9db1-d2b039ec1303.png)

![image](https://user-images.githubusercontent.com/1711576/57301624-1d6b4580-70e2-11e9-9e1a-ac43c9827c1e.png)

**Question**
How can I change background of these selections via `settings.json`?

**Comment by equinusocio** [comment]
```js
"editor.tokenColorCustomizations": {
    "[Material Theme VARIANT]": {
        "editor.selectionBackground": "#229977"
    }
},
```

**Comment by gencer** [comment]
I get following error:

```
Property editor.selectionBackground is not allowed.
Property editor.selectionHighlightBackground is not allowed.
```

When used following code:

```
	"editor.tokenColorCustomizations": {
		"[Material Theme Lighter]": {
			"editor.selectionBackground": "#ECF0F1", # error here
			"editor.selectionHighlightBackground": "#ECF0F1", # error here
		},

```

**Comment by equinusocio** [comment]
Sorry, change the main key from `editor.tokenColorCustomizations` to `workbench.colorCustomizations`

**Comment by gencer** [comment]
I already tried that. It changed nothing. I still get dark selection while i choose light one instead.

**Comment by gencer** [comment]
Update: It changes editor's selection colors. Editor's selection color is already light and visible.

![image](https://user-images.githubusercontent.com/1711576/57885034-bf9dd280-7832-11e9-86f1-9963ed4dbd4c.png)

**Comment by equinusocio** [comment]
😅Sorry, it's late.

```js
"editor.findMatchBackground": "#ff00FF",
"editor.findMatchHighlightBackground": "#0000ff"
```

Thank you for your patience..

**Comment by gencer** [comment]
Ah, no worries! Thank you for taking time to answer me 😊

Just additional question. I've added second image to previous answer. What is it called?

In last image you can see that `const file: any` selected and it is very dark. This tooltip available when hovering a variable.

**Comment by equinusocio** [comment]
I suggest you to use the vscode suggestion tool. Just start a new line after the previous setting (eg. `"editor.findMatchHighlightBackground": "#0000ff"` ) and type `"` to see the suggestions. It should be one of the `editor.find*` rule

**Comment by gencer** [comment]
Got it! Thank you for your help on this late time 👍
