### ISSUE TITLE
Diff colors are dark and hard to see

### ISSUE THREAD

**Issue by flowrean** [equinusocio/vsc-material-theme#355]
The red and green background colors in the diff view are not quite bright. They make it hard to spot the changes, which is the exact purpose of this view. Especially the selected line and the changes within a line (exclamation marks in the screenshot) are hard to spot. I always find myself close to the screen when looking at a diff.
![Screenshot 2019-05-13 at 15 39 14](https://user-images.githubusercontent.com/15046458/57626391-1175fc80-7596-11e9-830a-233856fc91ab.png)

**Comment by equinusocio** [comment]
Hi, please check this section:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

You can use the vscode api to customise your local installation in order to match your personal taste.
