### ISSUE TITLE
inconsistent colors when inside of function calls

### ISSUE THREAD

**Issue by jeff-hykin** [equinusocio/vsc-material-theme#356]
**Describe the bug**
Tokens inside of function calls, the `meta.function-call` scope, are colored inconsistently compared to tokens outside of function calls.

**To Reproduce**
Create a C++ file and copy/paste the following.
```
void Client::Timeline(const std::string& username) {
            // 
            // seperated
            // 
            auto b = [this, username]() {
                    ClientContext temp_context;
                    Empty temp_empty;
                    return true;
                };
            auto a = aFunction( b );
            // 
            // nested
            // 
            auto a = aFunction([this, username]() {
                ClientContext temp_context;
                Empty temp_empty;
                return true;
            });
    }
```
**Expected behavior**
The `// seperated` shows a lambda outside of a function call
The `// nested` shows the same lambda inside of a function call
It's expected that both examples would be colored the same since the meaning of the lambda is not changing.

**Screenshots**
![Screen Shot 2019-05-06 at 7 05 29 PM](https://user-images.githubusercontent.com/17692058/57262504-f2c1b400-7031-11e9-80a2-58b0d87a91af.png)

**Additional context**
I am posting this here because many people think this is a C++ Syntax issue (and report it as a bug to me).

**Suggested Fix**
Remove the coloring of the `meta.function-call` scope.

**Comment by equinusocio** [comment]
Fixed next release. Thank you!
