### ISSUE TITLE
Material Theme Darker High Contrast low readability of line numbers

### ISSUE THREAD

**Issue by jupiterneptune** [equinusocio/vsc-material-theme#357]
Hi,

Thank you for creating this great theme! I am having a small issue (it might have been resolved, I am unable to find a straightforward answer to it..) with line numbers having a low contrast. I am using the Vim extension in VSCode with :relativenumber option set, so I get to be a heavy user of line-based relative motions. I am providing a screenshot here for clarification.

![image](https://user-images.githubusercontent.com/1853331/58023991-d9346800-7b19-11e9-8d6c-b284e04f49e6.png)

**Comment by equinusocio** [comment]
Hi @jupiterneptune. Add the `editorLineNumber.activeForeground` key this under the `workbench.colorCustomizations` object in your configuration.

Ecample:
```js
"workbench.colorCustomizations": {
  "editorLineNumber.activeForeground": "#ff0000"
}
```

More info here:
https://github.com/equinusocio/vsc-material-theme#override-theme-colors

**Comment by jupiterneptune** [comment]
Thank you for your hints!
In my case, I ended up doing:

```js
"workbench.colorCustomizations": {
        "editorLineNumber.foreground": "#FF7042",
        "editorLineNumber.activeForeground": "#00FF00"
}
```

And it worked like a charm.
