### ISSUE TITLE
Clicking a search result makes the highlighted string unreadable for included module names in Ruby

### ISSUE THREAD

**Issue by adamhollett** [equinusocio/vsc-material-theme#358]
**Describe the bug**

If you're using Ruby and search for a term that happens to be an included module, then click the search result, the highlight (red) on the text (also red) makes the text an unreadable rectangle:

<img width="403" alt="29-12-89q27-7ndv8" src="https://user-images.githubusercontent.com/6955296/58577074-b38f1900-8213-11e9-8bae-8871c6a6a013.png">

**To reproduce**

1. Open a .rb file with an included module (a line like `include ModuleName`).
2. Perform a search for the module name.
3. Click the search result for the module's name in the file where it's included.

**Expected behavior**

You should be able to read the string when it's highlighted.

**Comment by Abady321x123** [comment]
this seems to be also for javascript const, anyway you can change the color of the highlighted match by going to settings.json and adding a new color to `editor.findMatchHighlightBackground` in `workbench.colorCustomizations`
