### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by facundovaras** [equinusocio/vsc-material-theme#359]
- Issue Type: `Performance`
- Extension Name: `vsc-material-theme`
- Extension Version: `2.9.0`
- OS Version: `Linux x64 5.0.0-15-generic`
- VSCode version: `1.34.0`

[Equinusocio.vsc-material-theme-unresponsive.cpuprofile.txt](https://github.com/equinusocio/vsc-material-theme/files/3234790/Equinusocio.vsc-material-theme-unresponsive.cpuprofile.txt)

**Comment by equinusocio** [comment]
@LasaleFamine

**Comment by LasaleFamine** [comment]
Hi @facundovaras, and thanks for using the Material Theme.

Can you please give me more details on why you think this is related to the theme itself? I can't get it from the log file. Thanks!

**Comment by facundovaras** [comment]
Hi @LasaleFamine, I was experienced performance issue, open up the panel of VS Code complements and I saw Material Theme with a warning, after that I disabled Material Theme and the performance issues go away.
