### ISSUE TITLE
Rename Symbol input has no contrast.

### ISSUE THREAD

**Issue by SunburnedGoose** [equinusocio/vsc-material-theme#36]
When I try to rename a symbol in VS Code, the input box where I can rename has white text on a white background.

Here's two images with the text selected, and unselected.  I've attached an image of Dark (Visual Studio) to show another example.

![screen shot 2017-05-11 at 12 30 16 pm](https://cloud.githubusercontent.com/assets/984608/25963060/a92c624a-3645-11e7-935f-d61a83366db3.png)
![screen shot 2017-05-11 at 12 30 10 pm](https://cloud.githubusercontent.com/assets/984608/25963062/a9390aae-3645-11e7-88ff-1ea070a58e17.png)
![screen shot 2017-05-11 at 12 31 27 pm](https://cloud.githubusercontent.com/assets/984608/25963096/c7195506-3645-11e7-81aa-d8f5f6068d3c.png)

**Comment by equinusocio** [comment]
This is fixed by vsc 1.13.0-insiders. You have to wait the public release next month.
