### ISSUE TITLE
Syntax Highlighting Updates

### ISSUE THREAD

**Issue by jabacchetta** [equinusocio/vsc-material-theme#360]
Not sure what's intended as opposed to what might just be overlooked tokens, so I'll just post everything that stuck out to me, along with the TextMate updates I made.

1. It seems strange to me that an inherited class has the same color as strings do, as opposed to the same color as the class that's extending.

Example:
```javascript
// myClass is yellow, while someOtherClass and strings are green
class myClass extends someOtherClass {}
```

2. I'm also getting the same green string color for some variables that are used inside template strings.

Example:
```javascript

// process and env are string colored
const path = `${process.env.staticPath}icons`;
```

3. In React JSX, the assignment operator is the same color as the attributes. I would suggest that they be separate colors (same as HTML).

Example:

```javascript
// screen and = are the same colors
<FullScreenModal screen="search" />
```

4. In HTML and JSX, character entities are appearing as multi-colored, because of the punctuation colors.

Example:
```HTML
<div>
  <!-- & and ; are blue, while amp is red -->
  Wit &amp; Wisdom
</div>
```
5. HTML text colors inside JSX being white and matching things like imports/exports/variables seemed like it needed some color separation.

**Below are the rules I added to address all of the above.**

```
"textMateRules": [
        {
          "scope": [
            "punctuation.definition.entity",
          ],
          "settings": {
            "foreground": "#F78C6C"
          }
        },
        {
          "scope": "entity.other.inherited-class",
          "settings": {
            "foreground": "#ffcb6bff"
          },
        },
        {
          "scope": [
            "support.variable",
            "variable",
            "variable.other.constant",
          ],
          "settings": {
            "foreground": "#ffffff"
          }
        },
        {
          "scope": [
            "keyword.operator.assignment",

          ],
          "settings": {
            "foreground": "#89ddffff"
          }
        },
{
          "scope": [
            "meta.jsx.children",
            "text.html.derivative",
          ],
          "settings": {
            "foreground": "#b2ccd6ff"
          }
        },
    ]
```

**Comment by jabacchetta** [comment]
I'm also getting the same green string color for variables inside template variables, which I modified by using the `support.variable` scope.

**Comment by jabacchetta** [comment]
Another suggestion: in React JSX, use different colors for the attributes and assignment operator.

**Comment by equinusocio** [comment]
To correct highlight JSX and advanced js syntaxes you have to use an extension since the basic vscode highlight system doesn't cover all the syntax scopes.


Can you try with this extension installed?
https://github.com/michaelgmcd/vscode-language-babel

**Comment by jabacchetta** [comment]
@equinusocio That did appear to solve my first two suggestions where the green string colors were showing, thanks!

The other 3 issues mentioned still exist.

**Comment by Riseley** [comment]
Hi, @equinusocio, thanks for pointing out that we need the Babel extension to properly correct JSX and advanced JS syntaxes.

However, I still ran into the issues that the key-value inside an object scopes are not properly set even after installing the extension. I wonder if this is a overlooked token in Material Theme or should I post this to Babel? ![image](https://user-images.githubusercontent.com/8508355/59910404-c5e42780-944c-11e9-8d9a-b6a2876d8ca3.png)

**Comment by jabacchetta** [comment]
Ran into another issue. After downloading the extension that was suggested, while some syntax highlighting began working, others began breaking in JavaScript (e.g. `console` in `console.log`).

**Comment by equinusocio** [comment]
@jabacchetta What do you mean with "began breaking". Can you add a screenshot of the changes?

**Comment by jabacchetta** [comment]
@equinusocio 

Here's with the Babel extension disabled. The colors match TypeScript. And note that the italics are working as expected.

<img width="1280" alt="disabled" src="https://user-images.githubusercontent.com/12591890/60275017-c7837480-98be-11e9-997c-944bdf378aec.png">

And here's with Babel extension enabled. Italics not working (as I declared in my settings). Colors seem to be broken?

<img width="1280" alt="enabled" src="https://user-images.githubusercontent.com/12591890/60275082-ed107e00-98be-11e9-92c2-743bfc307d2d.png">

**Comment by equinusocio** [comment]
Can you check the assigned scopes with the scope inspector? Probabily these extensions assign different scopes.
