### ISSUE TITLE
find result can't be recognized

### ISSUE THREAD

**Issue by wlchn** [equinusocio/vsc-material-theme#361]
**Describe the bug**
Find result can't be recognized after clicked.

**To Reproduce**
theme: daker-hc
language: TypeScript

1. Search a constant like FOO_BAR
2. Click a find result in the left bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/4652410/59328933-3a69e880-8d20-11e9-817b-bcd521f566cb.png)

**Comment by equinusocio** [comment]
Same as #358
