### ISSUE TITLE
Highlighted search input is unreadable with Material Theme Lighter enabled.

### ISSUE THREAD

**Issue by kgorol** [equinusocio/vsc-material-theme#362]
![image](https://user-images.githubusercontent.com/34159482/59404794-3681a900-8da8-11e9-8e40-38faca76e9b3.png)

When I highlight the phrase inside search input I can't really see what is selected. Screenshot above describes everything :)

**Comment by gjactat** [comment]
![image](https://user-images.githubusercontent.com/1826064/59860608-81d72100-937f-11e9-8221-f54e719eee41.png)
Pretty hard to read with the Palenight version too (see "ConfigManager")

**Comment by equinusocio** [comment]
@gjactat Hi, what you see is related to #358 not to this one :)
