### ISSUE TITLE
Separate C macro and function colors

### ISSUE THREAD

**Issue by SPAstef** [equinusocio/vsc-material-theme#365]
Hello, I'd like to have the possibility to change the function and macro colors separately. Right now, using textMateRules, it is only possible (as far as I know) to change both of them, by using _entity.name.function_

**Comment by equinusocio** [comment]
Hi, you can use the built-in scope finder to get the scopes tree and try to combine more scopes to target with more precision a keyname. Anyway, this is not related to this extension.
