### ISSUE TITLE
Select the find match result，the border or background is not changed.

### ISSUE THREAD

**Issue by wlchn** [equinusocio/vsc-material-theme#366]
**Describe the bug**
Select the find match result，the border or background is not changed. No selection effect.

**Version**
macOS 10.14.3
vscode: 1.36
Material Theme Darker High Contrast, latest

**To Reproduce**
1. Search a word `fooBar`
2. Click a result in left search bar
3. Select that find match result(teal border)

**Screenshots**
![image](https://user-images.githubusercontent.com/4652410/60643931-39336380-9e67-11e9-80e6-7687afdf8eb4.png)

**Comment by equinusocio** [comment]
Hi @wlchn. Unfortunately we can't find the keys to customise the project-wide search/replace. We will investigate, but probably you'll have to report this to the viscide team.

**Comment by wlchn** [comment]
Hi @equinusocio,  I have updated to 29.1.0 .  

Before select, backgroud is `black`, border is `teal`.
After select,backgroud is `black`, border is `teal`. And there is a cursor in the word end.

There is no difference after select the ` find match` except cursor.

**Comment by equinusocio** [comment]
Hi @wlchn we figure out that this is the default vscode behaviour. You can't select matched result with mouse, you have to use some shortcut.
