### ISSUE TITLE
Color heads-up notification

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#37]
Here is in Nord:
![screenshot 186](https://cloud.githubusercontent.com/assets/26769888/26021041/66725102-37a4-11e7-9cd0-7de2b6388da2.png)

And in Solarized Dark:
![screenshot 187](https://cloud.githubusercontent.com/assets/26769888/26021044/7426eb28-37a4-11e7-9a96-9ef4e929283e.png)

And what Material Theme gives is this:
![screenshot 188](https://cloud.githubusercontent.com/assets/26769888/26021047/88697be6-37a4-11e7-872a-139e382c58bf.png)

Those buttons in heads-up notification (or whatever it is called) can be colored. Please provide it for all of your themes. A color for hovering on it can also be assigned.

**Comment by equinusocio** [comment]
Buttons background and foreground are bugged in the latest public 1.12.
