### ISSUE TITLE
Add support for inputOption.activeBackground

### ISSUE THREAD

**Issue by misolori** [equinusocio/vsc-material-theme#379]
**Describe the bug**
VS Code will be introducing a new token color, `inputOption.activeBackground`, in the July release (1.37). This color is for showing when a button toggle is active (search, find, terminal find, etc.). It also re-uses `focusBorder` but in this theme the focus color is set to transparent, which means the new token color is also transparent. See below where you can't tell which item is "active", please consider adding support for this. You can test this by using the [Insiders version](https://code.visualstudio.com/insiders/), which already adds this.

**To Reproduce**
1. Go to Search
2. Enable one of the search options (match case, whole word, regex)
3. :bug: You can't tell if the option is on/off

**Expected behavior**
To visibly tell the the difference when a toggle is on/off

**Screenshots**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/35271042/62473754-46898980-b756-11e9-8685-4191c896d6c3.png">

**Comment by chshouyu** [comment]
+1
