### ISSUE TITLE
Enhancement: `editor.selectionHighlightBackground`

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#38]
It's hard to find the regions which have the same content as the selection.

![highlight](https://cloud.githubusercontent.com/assets/7588612/26023431/b72462cc-37ed-11e7-90fd-19e2cd7c8c73.png)

**Comment by jadark** [comment]
"workbench.colorCustomizations": {
    "editor.selectionBackground": "#135564",
    "editor.selectionHighlightBackground": "#135564"
},

**Comment by wprater** [comment]
was any work done on this?  I also have a very hard time with all the different selection buffers and multiple selection types.
