### ISSUE TITLE
Not enough contrast for inputOption.activeBackground

### ISSUE THREAD

**Issue by teohhanhui** [equinusocio/vsc-material-theme#380]
**Describe the bug**
The contrast for `inputOption.activeBackground` is bad with "Material Theme Darker".

**Screenshots**
![vscode search bar](https://user-images.githubusercontent.com/548843/62886306-4c293580-bd3b-11e9-918a-62db926b085c.png)

**Additional context**
Follow up to #379 and 971e7ce0dd4c603b388d541c77d68f66ce4fcafe

**Comment by equinusocio** [comment]
The current `inputOption.activeBackground` is not Teal.
https://github.com/equinusocio/vsc-material-theme/blob/master/src/themes/theme-template-color-theme.json#L688-L689

<img width="431" alt="Screenshot 2019-08-14 at 18 50 55" src="https://user-images.githubusercontent.com/10454741/63039876-870aa500-bec4-11e9-93f6-60c9bc098286.png">

Please make sure to not use custom overrides, and le latest material theme version.

**Comment by teohhanhui** [comment]
Oh, sorry, so you've fixed it. Thanks!
