### ISSUE TITLE
highlight typescript interfaces

### ISSUE THREAD

**Issue by phra** [equinusocio/vsc-material-theme#39]
hi,

atm typescripts interface names are not being highlighted.
imho it's nice to have it.
![schermata da 2017-05-15 13-43-04](https://cloud.githubusercontent.com/assets/984628/26058216/c80fb112-3974-11e7-935a-1987e128b934.png)

**Comment by equinusocio** [comment]
Please add the snippet :)

**Comment by phra** [comment]
```ts
const [err1, existing] = await to(ReviewModel.find({ company, product, author }).exec()) as [Error, IReview[]]
```

**Comment by equinusocio** [comment]
What VSC build are you using? This is what i see with vsc 1.12.1:
<img width="838" alt="screen shot 2017-05-15 at 15 08 22" src="https://cloud.githubusercontent.com/assets/10454741/26058975/5aa27e8c-3980-11e7-9bb2-68b35e10c84e.png">

**Comment by phra** [comment]
i don't have the "Error" class highlighted as the interface name.
i'm running this vsc:
```
Versione 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Data 2017-05-04T21:40:39.245Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

if you declare the IReview interface do you get the name highlighted?
```ts
interface IReview {}
```

**Comment by equinusocio** [comment]
Yes, the check the different with jsx react and babel javascript:
<img width="813" alt="screen shot 2017-05-15 at 15 31 52" src="https://cloud.githubusercontent.com/assets/10454741/26059937/c4c5ae1c-3983-11e7-93bf-dca5b25892f0.png">
<img width="844" alt="screen shot 2017-05-15 at 15 31 36" src="https://cloud.githubusercontent.com/assets/10454741/26059938/c53f470e-3983-11e7-938e-11ed3f1da409.png">

**Comment by equinusocio** [comment]
@phra any update?

**Comment by equinusocio** [comment]
@phra You fixed this? what was the problem?

**Comment by phra** [comment]
no time to dig into it, sorry.
