### ISSUE TITLE
Theme Light: Text in block comments is white

### ISSUE THREAD

**Issue by JSteitz** [equinusocio/vsc-material-theme#40]
Source: PHP

Any text that does not start with an asterisk is white in block comments

See Screenshot
![scheduleslidesviewhelper php - master 2017-05-16 10-40-01](https://cloud.githubusercontent.com/assets/677821/26097196/069e4e0c-3a24-11e7-9762-83687ae7a469.jpg)

**full scope tree:**
```
invalid.illegal { "background": "#FF5370", "foreground": "#ffffff" }
invalid.illegal.missing-asterisk.phpdoc.php
comment.block.documentation.phpdoc.php
source.php
meta.embedded.block.php
text.html.php
```

**used scope tree**
```js
invalid.illegal { "background": "#FF5370", "foreground": "#ffffff" }
```

**Comment by equinusocio** [comment]
You have to provide more infos:
- Visual Studio Code build
- Language/syntax
- File extension

**Comment by JSteitz** [comment]
VSC: 1.12.2
VSC Build: 19222cdc84ce72202478ba1cec5cb557b71163de
Theme: 0.0.13
File Extension: .php
Language/Syntax: PHP

Code Snippet:

```
/**
function hello($world) {}
*/
```

**Comment by equinusocio** [comment]
<img width="613" alt="screen shot 2017-05-16 at 11 04 12" src="https://cloud.githubusercontent.com/assets/10454741/26098263/6db2a5d6-3a27-11e7-94b8-c1d467a26cb6.png">

**Comment by JSteitz** [comment]
Disabled all extensions, reinstalled theme, reinstalled VSC.
Still the same result.

**Comment by equinusocio** [comment]
Thank you i just updated the main topic with additional info
