### ISSUE TITLE
No highlight on hovering on file tree list's elements

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#41]
Please add "list.hoverBackground" property to your theme

**Comment by equinusocio** [comment]
The behavior will be the same of Sublime Text Material Theme:
 
![2017-05-16 12 07 46](https://cloud.githubusercontent.com/assets/10454741/26101131/5bfde43c-3a30-11e7-83e3-a90b3ffafccf.gif)

**Comment by ajitid** [comment]
What that means? You won't implement it?

**Comment by equinusocio** [comment]
Check the gif

**Comment by ajitid** [comment]
Okay
