### ISSUE TITLE
Request for different color contrasts in activity bar and sidebar

### ISSUE THREAD

**Issue by imoby** [equinusocio/vsc-material-theme#43]
Request for different different contrasts in activity bar and sidebar similar to the default vscode theme and the sublime text theme as well.

**Comment by equinusocio** [comment]
@imoby Please import this as a wish on beerpay:
https://beerpay.io/equinusocio/vsc-material-theme/wishes

**Comment by imoby** [comment]
@equinusocio any other way of giving you a contribution without using beerpay?

**Comment by equinusocio** [comment]
Since the theme is still in beta release i have to work on more important implementations, so this task will be considered in the future as improvements.

**Comment by thomthom** [comment]
I second this request. I find the contrast of the UI elements to be difficult to read.

Was the a beerpay item added for this?

**Comment by equinusocio** [comment]
i'm working on it

**Comment by equinusocio** [comment]
@thomthom Yes. I work better if i'm drunk. Because if i'm drunk i can't think about that i'm doing this for free. For you.

**Comment by thomthom** [comment]
Now you can support this Wish from https://beerpay.io/equinusocio/vsc-material-theme/wishes/595f919af86e2a2d7d5c9340

🍻 Cheers!

**Comment by equinusocio** [comment]
🍻

**Comment by equinusocio** [comment]
Closed with https://github.com/equinusocio/vsc-material-theme/commit/79d68b32580467bf7879a20b87cc99d6b64a2c03.

Availabe next release.

**Comment by thomthom** [comment]
Wish granted successfully on Beerpay! https://beerpay.io/equinusocio/vsc-material-theme/wishes/595f919af86e2a2d7d5c9340
This issue will be closed.

🍻 Cheers!
