### ISSUE TITLE
New colors are... not so great

### ISSUE THREAD

**Issue by TheDutchCoder** [equinusocio/vsc-material-theme#44]
Since the last update (0.0.15) the colors in my JS files are not very nice anymore. Most has turned into red.

Any plans on reverting that?

![image](https://cloud.githubusercontent.com/assets/1668207/26167304/6954c98c-3b04-11e7-92f3-0d4d5ee0189e.png)

**Comment by Zx-EvM** [comment]
Sorry for offtop. What font do you use? On this screenshot.

**Comment by Zx-EvM** [comment]
@TheDutchCoder Sorry for offtop. What font do you use? On this screenshot.

**Comment by equinusocio** [comment]
This is a regression.

**Comment by equinusocio** [comment]
@TheDutchCoder Can you paste your snippet?

**Comment by TheDutchCoder** [comment]
@Zx-EvM Fira Code is what I use ;)

**Comment by TheDutchCoder** [comment]
@equinusocio what do you need? There's no new version out yet, so my colors are still the same ;)

**Comment by Zx-EvM** [comment]
@TheDutchCoder paste code snippet for test :)

**Comment by equinusocio** [comment]
I need your snippet to pick/check the correct scopes

**Comment by TheDutchCoder** [comment]
```js
  /**
   * Sets a pattern to apply to the product.
   *
   * @return {Promise}
   */
  setPattern ({ commit, dispatch, rootGetters }, payload) {
    commit(types.PRODUCT_SET_PATTERNID, { side: 'front', id: payload.id })
    commit(types.PRODUCT_SET_PALETTEID, { side: 'front', id: payload.defaultPaletteId })
    commit(types.PRODUCT_SET_PATTERNURL, { side: 'front', url: payload.source })

    if (rootGetters['builder/backOptionsIndex'] === 0) {
      commit(types.PRODUCT_SET_PATTERNID, { side: 'back', id: payload.id })
      commit(types.PRODUCT_SET_PALETTEID, { side: 'back', id: payload.defaultPaletteId })
      commit(types.PRODUCT_SET_PATTERNURL, { side: 'back', url: payload.source })
    }

    return dispatch('parseSvgData', true)
      .then(_ => {
        return dispatch('parseLayers', true)
      })
  }
```

**Comment by equinusocio** [comment]
With **javascript (babel)** will look that:
<img width="676" alt="screen shot 2017-05-18 at 15 25 52" src="https://cloud.githubusercontent.com/assets/10454741/26204178/4f94a03c-3bde-11e7-8b11-2a4e71224b62.png">

**Comment by Zx-EvM** [comment]
@equinusocio why not to use colors like in ST3 MT?

![SCREEN](http://i.imgur.com/R2R3GQM.png)

**Comment by TheDutchCoder** [comment]
I don't seem to have that filetype. It also changed after the update, so I would just the original colors back for regular JS files :)

**Comment by equinusocio** [comment]
@TheDutchCoder I suggest you to use this extension for a more complete code highlight
https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

@Zx-EvM Because i think the ST scheme should be improved too.

**Comment by TheDutchCoder** [comment]
Alright that worked, but not too big of a fan of install another plugin to solve this tbh ;)

**Comment by equinusocio** [comment]
I agree with you, but i can only provide colors for language scopes, if the native vsc js highlight doesn't use the correct scope that color will not be used.

**Comment by equinusocio** [comment]
@TheDutchCoder If you want you can install the 0.0.16 pre-release here:
https://github.com/equinusocio/vsc-material-theme/releases/tag/v0.0.16

**Comment by TheDutchCoder** [comment]
Now all my Vue files are messed up too :(
I guess I'll have to go back to another theme for the time being

**Comment by equinusocio** [comment]
with the v0.0.16?

**Comment by TheDutchCoder** [comment]
No v0.0.15 and it just happened when I switched tabs, so this might be more of a VSCode bug?

**Comment by equinusocio** [comment]
Have you tried to restart vsc?

**Comment by TheDutchCoder** [comment]
With v0.0.16 it seems to have been fixed! Thanks!
