### ISSUE TITLE
Red colored variables

### ISSUE THREAD

**Issue by ackzell** [equinusocio/vsc-material-theme#45]
Hi!

Theme in VSCode looks awesome. I am enjoying it a lot. Thanks a lot for your work on this!

I just had a quick question: Is there a way we could have variables colored other than "red"?

I am pasting an image with some *AngularJS* code I have, almost all my code looks red and it kind of makes me uneasy.
![imageedit_1_6892360739](https://cloud.githubusercontent.com/assets/601266/26167903/d84d1364-3afd-11e7-93b1-a2873a3d4b8e.png)

![image](https://cloud.githubusercontent.com/assets/601266/26167578/bad5fc02-3afc-11e7-9092-2b4a1fd2990e.png)

This might be addressed somewhere else but I couldn't find an issue regarding it. Happy to contribute a change if need be. (would need to be pointed in the right direction to make it though)

**Comment by TheDutchCoder** [comment]
https://github.com/equinusocio/vsc-material-theme/issues/44

**Comment by ackzell** [comment]
Ha! You beat me to it, @TheDutchCoder my bad.

**Comment by ajitid** [comment]
@TheDutchCoder @ackzell you both closed your issue. Decide to reopen one of them.

**Comment by TheDutchCoder** [comment]
I did not close mine.

**Comment by ajitid** [comment]
Glanced over, sorry.
