### ISSUE TITLE
Text contrast on inactive pane/tab is very low

### ISSUE THREAD

**Issue by rjv** [equinusocio/vsc-material-theme#47]
Really love the theme! One UI issue keeps cropping up for me in daily use: the contrast of the text on inactive tabs (on an inactive pane) is very low and borderline unreadable. Is there any way this could be adjusted so there is greater contrast (on the dark themes in particular)? Here are some examples of what I mean:

![screenshot_4](https://cloud.githubusercontent.com/assets/532439/26202764/95ab78f8-3ba6-11e7-9043-06a3b090ddee.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/532439/26202763/95a99704-3ba6-11e7-988d-bca42e98ab7d.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/532439/26202765/95af00fe-3ba6-11e7-8458-ba732a315fd6.png)

**Comment by equinusocio** [comment]
Hi @rjv, the issue is that the inactive panel inside an inactive group doesn't have customisation. I will fix that.

For now, you can set the color by adding this to your settings and change the color:
```json
"workbench.colorCustomizations": {
    "tab.inactiveForeground": "#FF00FF"
}
```
