### ISSUE TITLE
Hard to see where mouse pointer will change into resize handle

### ISSUE THREAD

**Issue by fredrikaverpil** [equinusocio/vsc-material-theme#50]
I find it difficult to quickly find where to position the mouse pointer in order to get it to change into a resize handle. I always have to spend a couple of seconds to hunt around before I find the exact spot where I can click and drag to resize.

I usually need to resize the following:

* integrated terminal/output, vertically
* left hand side file tree/search/git/debug/extensions, horizontally
* (opened editors, horizontally) - these do have an indicator, but I feel it could be done a bit more visible

I'm not sure if a solid line is what I'm asking for. Not sure what would be the nicest and follow the material guidelines. Perhaps it would be possible to add a subtle indicator of where the resize edge resides.

It's also possible that this issue is completely solved by #43 if that makes things easier to spot quickly.

And/or perhaps I can add in some kind of visual cue in `settings.json` myself, manually?

A screenshot showing the most difficult spots to find, IMHO:

![screen shot 2017-05-24 at 08 55 40 copy](https://cloud.githubusercontent.com/assets/994357/26390513/23fc55de-405f-11e7-86cc-093ced5a3ea4.png)

Thanks so much for your outstanding work on these excellent themes! :heart: I spend almost full workdays in front of them all week long, and they are very pleasing to work with.

**Comment by equinusocio** [comment]
For now you have to add these settings to your `setting` file:
```js
"workbench.colorCustomizations": {
  "panel.border": "#FF00FF",
  "sideBar.background": "#FF00FF" 
}
```

`panel.border` add a separator to the bottom panel (integrated terminal, etc..) and since there is not a border key for the sidebar, you have to change the `sideBar.background` key. Remember that these settings will always override the current active theme.

When #32 will be implemented you can set a custom settings for the theme, like material theme for Sublime Text.

**Comment by equinusocio** [comment]
@fredrikaverpil From next release you can set `sideBar.border` instead of `sideBar.background`

**Comment by fredrikaverpil** [comment]
Nice, thanks!

**Comment by fredrikaverpil** [comment]
Just sharing the following settings which are super useful and nice with the default Material theme:

```json
{
    "workbench.colorCustomizations": {
        "panel.border": "#1d262a",
        "sideBar.border": "#1d262a"
    }
}
```

**Comment by equinusocio** [comment]
Next release will be the v1 and will allow you to set one of the accent colors o set a custom one. Other settings like separators will be implemented after v1. 👍
