### ISSUE TITLE
Hard to identify which extension is disabled

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#52]
The Python extension is disabled but it's hard to notice

![image](https://cloud.githubusercontent.com/assets/7588612/26569217/e112d13a-453b-11e7-9d38-b8b7174d2a50.png)

**Comment by Zx-EvM** [comment]
![SCREENSHOT](http://i.imgur.com/xMe8TjQ.png)

**Comment by neilsustc** [comment]
Oh, forgot to mention that I manually installed the v0.0.17 downloaded from the releases page 😅

**Comment by equinusocio** [comment]
At the moment the extensions list share style with the sidebar tree, the disabled extension change only opacity to the default list color (that i can't change.) For now i will close until we will have the ability to separate styles between sidebar tree and extensions list.
