### ISSUE TITLE
Filename Focus Disappear in Explorer

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#55]
When I focus on the contents of the file, the focus in the explorer disappear.

![23ne-nk123ne-23c2-23dswa gif](https://user-images.githubusercontent.com/20873402/27217974-fac7fa7c-5230-11e7-9b6e-ca3ba362e220.gif)

For instance, this not happens in Sublime Text 3 MT.

**Comment by equinusocio** [comment]
THis is fixed in the next release,

**Comment by Zx-EvM** [comment]
@equinusocio now I use 0.0.17.

What color you are using for brackets matching highlighting? I need this to customize https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets
