### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#56]
![screenshot 127](https://user-images.githubusercontent.com/26769888/27303149-6d692d7a-5557-11e7-912a-321d67b7ad94.png)
![screenshot 124](https://user-images.githubusercontent.com/26769888/27303150-6d6d4c84-5557-11e7-8153-e141648478ac.png)
"Info" word needs a better color in these themes (Palenight and Light).
Background color of "Info" and of "Error" can also be changed (if that helps).

--------------------------

![screenshot 121](https://user-images.githubusercontent.com/26769888/27303217-a94ed04c-5557-11e7-87f1-cb9b82004446.png)
This default blue colored loading animation can be colored with `"progressBar.background"`

--------------------------- 

![screenshot 120](https://user-images.githubusercontent.com/26769888/27303329-16611730-5558-11e7-8926-ec360b617972.png)
Better contrast is needed in "Error" too (Palenight)

----------------------------------

![screenshot 125](https://user-images.githubusercontent.com/26769888/27303404-597f3e0c-5558-11e7-8778-2e7a9260c649.png)
I think selected option in Light is barely visible.

--------------------------------------

![screenshot 126](https://user-images.githubusercontent.com/26769888/27303442-735e0e8e-5558-11e7-8d0e-073e6ebaf8e7.png)
Color of those keyboard shortcuts in command palette can also be changed and be matched with the theme

-------------------

https://github.com/Microsoft/vscode/pull/27053
Change color of error and warning squiggles

---------------

Put a border around terminal

**Comment by equinusocio** [comment]
@ajitid I can't find the keys for the Error/Info badges

**Comment by ajitid** [comment]
Dracula theme has colored it
![screenshot 131](https://user-images.githubusercontent.com/26769888/27321334-80c84e7c-55b7-11e7-85b1-a5447d016d6a.png)

**Comment by ajitid** [comment]
I used Generate theme from current settings in Dracula and found this at its end: 

	{
			"scope": "token.info-token",
			"settings": {
				"foreground": "#6796e6"
			}
		},
		{
			"scope": "token.warn-token",
			"settings": {
				"foreground": "#cd9731"
			}
		},
		{
			"scope": "token.error-token",
			"settings": {
				"foreground": "#f44747"
			}
		},
		{
			"scope": "token.debug-token",
			"settings": {
				"foreground": "#b267e6"
			}
		}

Are these the needed keys?

**Comment by ajitid** [comment]
Another, status bar color while debugging...
![screenshot 133](https://user-images.githubusercontent.com/26769888/27323929-fb179bd4-55c0-11e7-9155-ba475c173074.png)

**Comment by equinusocio** [comment]
@ajitid I can't find how style keyboard shortcuts in command palette

**Comment by ajitid** [comment]
Did you found it? (Coloring keyboard shortcuts)

**Comment by equinusocio** [comment]
Yes!
