### ISSUE TITLE
Coloring self of function (class method) in Python

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#57]
![screenshot 128](https://user-images.githubusercontent.com/26769888/27304307-325675c2-555b-11e7-85f8-c039c15880ca.png)
![screenshot 129](https://user-images.githubusercontent.com/26769888/27304308-325bee80-555b-11e7-8ae5-7acca0418fda.png)

**Comment by equinusocio** [comment]
@ajitid Just a tip, the theme provide a full set of file icons for a better ux. Check https://github.com/equinusocio/vsc-material-theme#activate-file-icons

**Comment by ajitid** [comment]
I do like the icons this theme comes with.
What I know is that this theme for VS Code will try to look like the Sublime one, so it will never get custom folder icons (eg. for css, img). That's why I didn't put up an issue here for it.

**Comment by ajitid** [comment]
One question, I used Resource Hacker application on Windows to change VS Code's icon. It did changed, but after VS Code updates itself, it reverts back to the original one. Do you know any solution for it?

**Comment by equinusocio** [comment]
The only way to keep icons is to use a theme icons extension.

**Comment by ajitid** [comment]
I used Resource Hacker to change icon at title bar. 
Maybe there is no way to retain title bar icon on Windows then.

**Comment by ajitid** [comment]
[removed all non-relevant comments]

**Comment by equinusocio** [comment]
Now it's red.

**Comment by ajitid** [comment]
Thanks!

**Comment by ajitid** [comment]
2.0?

**Comment by equinusocio** [comment]
Next patch. We are working to improve the custom settings system now.

**Comment by equinusocio** [comment]
@ajitid Try 1.0.1 and let me know if this issue is gone.
