### ISSUE TITLE
Material Theme White font Issue

### ISSUE THREAD

**Issue by NoahHuynh** [equinusocio/vsc-material-theme#58]
Hi I installed this extension and after applying all of the 4 material themes all of my fonts are white.  I wonder is there anything I could possibly be missing or over looking.  Please help if you have any suggestions or fixes, I have VSC 1.3.1

**Comment by equinusocio** [comment]
vsc 1.3.1?

**Comment by NoahHuynh** [comment]
I have 1.3.1 is it beta? 
![image](https://user-images.githubusercontent.com/10272229/27437670-9be68ada-5728-11e7-96ce-35691c0426fb.png)

**Comment by equinusocio** [comment]
It's a older release. Now The public release is 1.13 and material theme support vsc 1.12+. Please update ant let me know if you still have the issue.

**Comment by NoahHuynh** [comment]
Omg I have no idea its that old and the funny thing is when I check for updates it says its the most current one -_- I will install the new one and keep you updated.  Thanks!
![image](https://user-images.githubusercontent.com/10272229/27437894-4c108294-5729-11e7-8b91-c62000b457de.png)

**Comment by equinusocio** [comment]
@NoahHuynh Do you fixed this?
