### ISSUE TITLE
Different colors for open folders and open files

### ISSUE THREAD

**Issue by alexbet** [equinusocio/vsc-material-theme#59]
I set my accent color to acid-lime. However, for some reason the open folders and the open files are different colors (see below).  

![foldersfiles](https://user-images.githubusercontent.com/3966760/27742408-802ac946-5d86-11e7-94dc-6f69fb53c0c1.png)

Can this be fixed so they are all acid lime color please?

Also, is there any way to make those little white arrows that indicate and open and closed folder disappear? We don't need those since we have color indication if a folder is open or not. Maybe it can be a setting so people can choose?

**Comment by equinusocio** [comment]
The arrows can't be removed right now since VSC doesn't add the api to do that. Please +1 this issue:
https://github.com/Microsoft/vscode/issues/25655

About the accent, this should be fixed next release
