### ISSUE TITLE
File icons updates

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme#6]
This is the checklist about the next file icons update

**FILES**
- [x] Update webpack icon
- [x] Add bower icon to `.bowerrc`
- [x] Fix yarn icon color
- [x] Add postcss icon `.postcss`
- [x] Add graphql icon `.gql`, `.graphql`
- [x] Add C and C++ icon `.c`, `.cpp`, `.c++`, `.cc`
- ~~Add polymer icon `Polymer` language ID~~

**FOLDERS**
- [x] Add icon to build/dist folder

**Comment by frankdugan3** [comment]
@equinusocio Would you consider adding icons for [GraphQL](http://graphql.org/)?

Extensions: `.gql` and `.graphql`

**Comment by equinusocio** [comment]
Updated issue

**Comment by ajitid** [comment]
C and C++ icons please!

**Comment by equinusocio** [comment]
@ajitid What file extension you can suggest?

**Comment by ajitid** [comment]
I am asking icons for .c and .cpp. That's what you are asking, aren't you?

**Comment by equinusocio** [comment]
yes added `.c, .cpp, .c++, .cc`
