### ISSUE TITLE
Support more folder icons

### ISSUE THREAD

**Issue by neilsustc** [equinusocio/vsc-material-theme#61]
Another extension [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) supports more specific folder icons, which looks really nice.

![folder icons](https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/master/images/folderIcons.png)

**Comment by skbolton** [comment]
To each their own I really like the accent colored folders

**Comment by equinusocio** [comment]
I will close this because at the moment we have no plan to implement more folder icons that. We need to rethink current folders specific icons.

**Comment by equinusocio** [comment]
@neilsustc For every specifi folder icon you will lose the accent color.

**Comment by neilsustc** [comment]
For me that is fine 😳

**Comment by Zx-EvM** [comment]
> For every specifi folder icon you will lose the accent color.

@equinusocio why? But for `dist` folder icon we have accent color. Or this icon not from MT?

![21-10-2017 18-10-17](https://user-images.githubusercontent.com/20873402/31857157-25b19ad6-b68b-11e7-94c1-dd1e0b12f12f.png)

**Comment by equinusocio** [comment]
We are thinking how to add more folders and relative accents.

**Comment by equinusocio** [comment]
Added

- [x] js
- [x] node
- [x] images
- [x] gulp
- [x] src
- [x] assets
- [ ] scripts
