### ISSUE TITLE
How I add line color below tab

### ISSUE THREAD

**Issue by adrianoresende** [equinusocio/vsc-material-theme#62]
How I add line color below tab?

Example:
![image](https://user-images.githubusercontent.com/798755/28047597-8b443ea0-65c1-11e7-9101-3c4f6a369440.png)

**Comment by equinusocio** [comment]
At the moment vsc doesn't provide API to do that. It allow to change colors only.

**Comment by rishabhsrao** [comment]
[`tab.activeBorder`](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-groups-tabs) can be used to the active tab's line color.
