### ISSUE TITLE
Settings seems broken with some not recognise

### ISSUE THREAD

**Issue by awesomenaz** [equinusocio/vsc-material-theme#65]
Changing color variants does not reflect immediately as it used to before the update. 
Some settings are not recognized, accent being one - error was thrown.

**Comment by equinusocio** [comment]
@OctoD Can you check?

**Comment by awesomenaz** [comment]
@equinusocio doing that works like a charm. All back to normal! Thank you.

**Comment by awesomenaz** [comment]
One issue still persists is that changes are not directly reflected. Require restart for such changes to take into affect.

**Comment by OctoD** [comment]
Could you please provide us vsc version and the exact actions you are performing? Thanks in advance.

**Comment by equinusocio** [comment]
@awesomenaz @OctoD Changing the accent color require a window reload.

**Comment by awesomenaz** [comment]
Current vsc version 1.14.2. 

The steps utilised as specified by docs. 
Options for color scheme as referred above were missing. 
Settings at initial point were throwing error as not found. 

At the moment after resetting all setings related to material theme from configuration file, it works. But changing colors are still not reflecting immediately.

**Comment by antonreshetov** [comment]
Such a hemorrhoid, it would be better not to be updated

**Comment by equinusocio** [comment]
@awesomenaz We can't avoid refresh the window when the accent color is selected, but we can auto-reload the window without ask the user confirm. About the old settings, we are working on it. :)

**Comment by equinusocio** [comment]
@antonreshetov Please provide useful information or you can follow this steps:
1. Remove this theme
2. Leave this topic and this repository too.
3. When leave, remember that we are working for free, for you.

**Comment by awesomenaz** [comment]
Thank you, @equinusocio was just wondering why some behavior related to the theme was changed, while docs remained the same instead of reflecting the changes. 

All in all, at the moment things are working as usual. 

Thank you again for the assist!

**Comment by equinusocio** [comment]
@awesomenaz What do you mean? The README was update to reflect the new activation system. About accent colors nothing's changed. Next patch the accent selection will not ask for user confirm.

**Comment by antonreshetov** [comment]
@awesomenaz The package is cool, not cool one, that now to quickly change the theme I need to go to `Material Theme: Settings` before I just clicked `cmd+k+t` and select theme

**Comment by equinusocio** [comment]
@antonreshetov This was a technical decision. By this way we can have more control over settings, customisations and we can provide more material theme settings easily. By the way, how many time you select the material theme? i think one. Please stop this OT.

**Comment by awesomenaz** [comment]
@equinusocio What I meant was the changes made to the settings - where it was throwing errors. Once all previous settings removed and changes made, things are working fine. My apology for the misunderstanding.

**Comment by equinusocio** [comment]
@awesomenaz The warning and errors are a bug :) removing settings is just a quick fix until we figure what happen. :)

**Comment by awesomenaz** [comment]
@antonreshetov If something goes wrong just let them know, if the changes are too much, use another theme. Don't have to be rude.

**Comment by awesomenaz** [comment]
@equinusocio Yes, this matter is solved for now. Have a great day and thank you again.

**Comment by antonreshetov** [comment]
Peace for everyone, keep on hacking :)

**Comment by sd-design** [comment]
I have Mac OS 10.11.16 - "Material Theme: Settings" doen't work. Setting was wrote in settings.json, but theme doesn't change

**Comment by m19** [comment]
@equinusocio I have the same issue as @sd-design. Fresh VS Code install first time using this theme. Nothing changes for me using the Material Theme Settings menu option.

**Comment by equinusocio** [comment]
@sd-design @m19 have you tried these steps?
https://github.com/equinusocio/vsc-material-theme/issues/65#issuecomment-317367014

**Comment by m19** [comment]
@equinusocio thanks! I just edited my previous post. The issue was not having set `workbench.colorTheme` to `Material Theme`.
First time using VS Code, wasn't aware of this.
