### ISSUE TITLE
Сolor scheme

### ISSUE THREAD

**Issue by antonreshetov** [equinusocio/vsc-material-theme#66]
Missing the choice of color scheme. Only one scheme

![2017-07-24 11 49 50](https://user-images.githubusercontent.com/17480987/28515437-4425f068-7066-11e7-92e1-2e5a24c9a37e.png)

**Comment by equinusocio** [comment]
Please check https://github.com/equinusocio/vsc-material-theme#activate-theme

Theme variant are now under `Material Theme: Settings` command

**Comment by antonreshetov** [comment]
This is not very usability

**Comment by equinusocio** [comment]
If there is instructions, you have to read it 👍

**Comment by antonreshetov** [comment]
When selected through Material Theme: Settings - Light, еheme does not change

**Comment by equinusocio** [comment]
Also check #https://github.com/equinusocio/vsc-material-theme/issues/65
