### ISSUE TITLE
Pressing Escape in theme options breaks theme

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#69]
In theme selection selection of Material theme (Material Theme Settings > Change color variant), I pressed Esc and VS Code reverted to default Dark+ theme.

![anim2](https://user-images.githubusercontent.com/26769888/28549641-11f1979e-70f9-11e7-95c2-0901e8e03352.gif)

And I can't switch back to Material theme because there isn't any option for it. Only way I found to fix this is to reinstall the theme again.

![screenshot 228](https://user-images.githubusercontent.com/26769888/28549779-37ccae94-70fa-11e7-8a19-c486e04723d9.png)
(Green squiggle below theme because VS Code is unable to find it, file icon works fine though.)

![screenshot 229](https://user-images.githubusercontent.com/26769888/28549783-3cba7530-70fa-11e7-8960-0cdebd0af91a.png)
(Material theme option isn't present)

Maybe these themes are needed to put back where they were.

Fix this and notification button colors in next release too.

**Comment by MrJacobSullivan** [comment]
I agree, I think this update broke something. I can't use the darker theme (which I prefer). The only material theme available to me is the default blue tint one.

**Comment by ajitid** [comment]
@MrJacobSullivan I too use darker theme. Instead of keeping all material themes alongwith other themes inside `Color Themes` option, the author has made a different section for it. You can still choose darker theme, it is now in `Material Theme Settings` > `Change color variant ` > `Darker` (see gif at top).

**Comment by MrJacobSullivan** [comment]
Ah, I understand. Thank you!

**Comment by OctoD** [comment]
The fix is committed in the dev branch, and the patch should be released today. Thank you for reporting this bug!
