### ISSUE TITLE
Suggestion about Material Theme Darker

### ISSUE THREAD

**Issue by StefanoPernat** [equinusocio/vsc-material-theme#7]
Hello, let me say that your theme is awesome, is one of the best themes I have ever tried.

In the darker version I found the comments color too dark, and compared to the background color I found very hard to read comments in my code.

May I suggest you a change of color?

best regards
Stefano

![comments_and_backdround](https://cloud.githubusercontent.com/assets/9131699/22981961/fc1b332c-f39d-11e6-9a05-cac786841878.jpg)

**Comment by equinusocio** [comment]
You can edit your local `Material-Theme-Darker.tmTheme` by browsing extensions. Make note that every changes will be lost when you update the extension. At the moment no color scheme changes are planned. Thank you and enjoy :)
