### ISSUE TITLE
After update 2017-07-25, "Material Theme Dark" not exist

### ISSUE THREAD

**Issue by adrianoresende** [equinusocio/vsc-material-theme#78]
Why "workbench.colorTheme": "Material Theme Dark" not work after update?

How I set Dark now?

**Comment by jzone1366** [comment]
@adrianoresende If you follow the directions in the [readme](https://github.com/equinusocio/vsc-material-theme#activate-theme) it tells you how to open the Material Theme settings and activate the colorTheme of your choice. (I just did this on mac running the newest VsCode and newest Update)

**Comment by Zx-EvM** [comment]
https://github.com/equinusocio/vsc-material-theme/issues/75
