### ISSUE TITLE
Wrong Gutter Indicator Color for Modified Lines

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#79]
Windows 10 Version 1703 Build 15063.483
VSCode 1.14.2
Material Theme 1.0.2

https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators

- A red triangle indicates where lines have been deleted
- A green bar indicates new added lines
- **A blue bar indicates modified lines**

Red triangle and green indicators works correctly with Material Theme and with default VSCode theme. Problem only with blue indicator. It looks yellow (with some transparent).

Gif with Material Theme:

![050902402 gif](https://user-images.githubusercontent.com/20873402/28691642-8b5a11ee-72d2-11e7-9b77-c0d05f317385.gif)

Gif with default:

![050902402 gif](https://user-images.githubusercontent.com/20873402/28691885-4e8095c6-72d3-11e7-84e2-49b62dd5f2d4.gif)

**Comment by equinusocio** [comment]
Hi @Zx-EvM. Thank you.

**Comment by Zx-EvM** [comment]
Hi @equinusocio. You're welcome :)

**Comment by equinusocio** [comment]
I think we will work on this (and on 1.1.0) after the summer vacation.

**Comment by Zx-EvM** [comment]
@equinusocio it is possible to use more "soft" colors for this indicators as you use in hyper-material-theme?

VSCode have colors settings for this:

- `editorGutter.background`: Background color of the editor gutter.
- `editorGutter.modifiedBackground`: Editor gutter background color for lines that are modified.
- `editorGutter.addedBackground`: Editor gutter background color for lines that are added.
- `editorGutter.deletedBackground`: Editor gutter background color for lines that are deleted.

**Comment by equinusocio** [comment]
These indicators already use colors from material theme. The yellow is a bit transparent but i will fix all colors.
