### ISSUE TITLE
Port the "default" theme from sublime text 3 to vscode

### ISSUE THREAD

**Issue by ludo237** [equinusocio/vsc-material-theme#8]
Hello everyone.

I would like to know if it's possible to port the classic *default* material theme inside visual studio? I really love it.

For reference I'm talking about this one:

![image](https://cloud.githubusercontent.com/assets/921500/23071225/e5f49ac0-f52d-11e6-980d-bdb668c51545.png)

Currently the theme offers only "darker and lighter" variants.

**Comment by equinusocio** [comment]
Not at the moment. We have to wait until vsc team will release the next month update that will bring UI api to customize other UI elements such sidebar, status bar, activity bar, title bar ecc.. 

Check https://github.com/Microsoft/vscode/issues/20021

**Comment by ludo237** [comment]
@equinusocio not your fault man, did't know about this issue. Thanks to bringing it to my attention who ☮️

**Comment by shaunc869** [comment]
Can this be done now?

**Comment by equinusocio** [comment]
Wut? There is.

**Comment by pronebird** [comment]
There is wut?

**Comment by equinusocio** [comment]
The default theme ready exist...

**Comment by pronebird** [comment]
Oh pretty cool, I just found it!
