### ISSUE TITLE
It is possible to make italic for keywords optional?

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#81]
It is possible to make italic for keywords optionaly?

Generally I mean **`this`** keyword. I use **`Fira Code Regular`** font and in some cases italic looks not so good.

Screenshots for explanations what I mean:

**Fira Code Regular**:

![28-07-2017 19-12-04](https://user-images.githubusercontent.com/20873402/28741337-ea4bdab0-73c8-11e7-9192-25888082670f.png)

![28-07-2017 19-12-24](https://user-images.githubusercontent.com/20873402/28741338-ebacfa24-73c8-11e7-8482-8cac389d4abe.png)

![28-07-2017 19-35-33](https://user-images.githubusercontent.com/20873402/28741498-f6ba1c28-73cb-11e7-9aeb-ace31d8fc6a7.png)

**Consolas**:

![28-07-2017 19-14-53](https://user-images.githubusercontent.com/20873402/28741346-0d417160-73c9-11e7-96ed-ec737ea3e551.png)

In **`Fira Code`** example I think we have long distance between left bracket and `this` keyword.

It's looks good with **`Consolas`** but I need **`Fira Code`** and its ligatures :)

P.S. If it's not possible to make optional, maybe I can to change this myself in source code from version to version :)

**Comment by equinusocio** [comment]
I can't make fixes based in users editor font. I'm sorry but uou have to do it by youself

**Comment by Zx-EvM** [comment]
@equinusocio If I understand correctly in my case I just need go to `.vscode/extensions` directory and change "italic" in this line: https://github.com/equinusocio/vsc-material-theme/blob/master/themes/Material-Theme-Default.json#L250 to "regular" and don't need to create own VSIX installer?

Thank you.

**Comment by equinusocio** [comment]
@Zx-EvM Yes, but you will lost your changes after the extension update.
