### ISSUE TITLE
Add support to Settings Cycler extension

### ISSUE THREAD

**Issue by gil0mendes** [equinusocio/vsc-material-theme#82]
Hello,

First of all, I start working with VSCode and this theme is the best one out there :) 

My question is, there is any way to switch the color variant in the user settings? I'm using [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) to create a day and night ambient, but the only thing that I can do is changing the accent. Any idea? :)

**Comment by equinusocio** [comment]
Not at the moment, these are the mt settings:
```
"workbench.colorTheme": "Material Theme",
 "materialTheme.cache.workbench.settings": {
    "themeColours": "Darker",
    "themeIcons": "eq-material-theme-icons",
    "accent": "Bright Teal",
    "accentPrevious": "Cyan"
  }
```

Now it doesn't work but i think we can work on it and add a watcher to the `materialTheme.cache.workbench.settings` setting @OctoD What do you think?

**Comment by OctoD** [comment]
Seems like settings changer stores and rewrites the content of settings.json. The only way to make settings cycler work is to diff the internal theme settings with the settings.json and re-apply the theme. I think I will work as soon as I will get back from vacation.

**Comment by equinusocio** [comment]
Removed from the roadmap
