### ISSUE TITLE
Cannot change color theme

### ISSUE THREAD

**Issue by skeith69** [equinusocio/vsc-material-theme#85]
following the instructions for changing color theme is not working at all

**Comment by dklesev** [comment]
try ⌘ + Shift + P --> Preferences: Color Theme. There you can select the material theme

**Comment by equinusocio** [comment]
I will update the readme

**Comment by chasebank** [comment]
Gotta say... trying to change the colors in this theme has been of of the harder things I've worked on today, *so far*...

I'm new to VS code, but it looks like Quick Open mentioned in the readme (ctrl + p on Windows), only opens files from your current working directory? It seems to function like a 'find in project'. If I'm in a new VS Code window with nothing open, anything I type returns "no results found".

If I open the material theme extension folder in VS, hit ctrl + p, type "Material Theme". I see no "Material Theme: Settings" in the results.

The closest results are material.theme.config.js and material.theme.config.ts  And taking a look into both of those, changing the color is no more obvious. So, I'm at a complete loss... ¯\_(ツ)_/¯
