### ISSUE TITLE
Request for color change

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#86]
Inactive tabs and unselected filenames in Explorer are quite hard to see. They are legible with:

    "workbench.colorCustomizations": {
        "sideBar.foreground": "#757575",
        "tab.inactiveForeground": "#757575",
        "badge.foreground": "#757575"
    }

for Darker theme.

**Comment by ajitid** [comment]
Seems to be copy of https://github.com/equinusocio/vsc-material-theme/issues/43 . Closing

**Comment by equinusocio** [comment]
You can use `"workbench.colorCustomizations": {},` to override the theme colors.
