### ISSUE TITLE
Add color customizations

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#88]
`"tab.activeBorder"` and `"tab.unfocusedActiveBorder"`

**Comment by Zx-EvM** [comment]
Yes. In new VSCode update `1.16.0` added more new theming color keys:

`tab.activeBorder`: A border drawn to the bottom of the active tab.
`tab.unfocusedActiveBorder`: A border drawn to the bottom of the active tab in an editor group that is not focused.
`editorOverviewRuler.border`: Color of the overview ruler border.
`editorOverviewRuler.findMatchForeground`: Overview ruler marker color for find matches.
`editorOverviewRuler.rangeHighlightForeground`: Overview ruler marker color for range highlights.
`editorOverviewRuler.selectionHighlightForeground`: Overview ruler marker color for selection highlights.
`editorOverviewRuler.wordHighlightForeground`: Overview ruler marker color for symbol highlights.
`editorOverviewRuler.wordHighlightStrongForeground`: Overview ruler marker color for write-access symbol highlights
`editorOverviewRuler.modifiedForeground`: Overview ruler marker color for modified content.
`editorOverviewRuler.addedForeground`: Overview ruler marker color for added content.
`editorOverviewRuler.deletedForeground`: Overview ruler marker color for deleted content.
`editorOverviewRuler.errorForeground`: Overview ruler marker color for errors.
`editorOverviewRuler.warningForeground`: Overview ruler marker color for warnings.
`editorOverviewRuler.infoForeground`: Overview ruler marker color for information messages.

Very cool that now we have more color keys for selection words.

**Comment by equinusocio** [comment]
@ajitid Thank you! I'm working on that right now.
