### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by agauniyal** [equinusocio/vsc-material-theme#9]

**Comment by equinusocio** [comment]
I will add some screenshots in the next beta release.

**Comment by equinusocio** [comment]
![screen shot 2017-02-20 at 09 49 36](https://cloud.githubusercontent.com/assets/10454741/23117842/ea6ebd30-f751-11e6-9fdb-3c42f02d4d0c.png)

**Comment by agauniyal** [comment]
Your theme is quite good! Please add a light variant as well (if possible) 😄

**Comment by equinusocio** [comment]
There is.
