### ISSUE TITLE
Material Theme isn't working on vscode 1.16

### ISSUE THREAD

**Issue by jancassio** [equinusocio/vsc-material-theme#90]
Hello guys,

After update my vscode from `1.15` to `1.16`, this extension is not changing vscode window interface.

I've tried to change accent color and color variant, nothing was changed, still on default vscode theme.
Also, I unistalled vscode entirely (yes I love this extension) to try to solve this problem.

I don't know how to provide more details, the only clue is, I've tried other themes and still in the same problem.

**Comment by equinusocio** [comment]
I just uodated the readme. You need first to acrivate the theme like other themes.
