### ISSUE TITLE
text of inactive tabs

### ISSUE THREAD

**Issue by ajitid** [equinusocio/vsc-material-theme#94]
Thanks for increasing contrast of sidebar text in 1.0.3. Please make color of text of inactive tabs match to the sidebar text in the next release.

![screenshot from 2017-09-27 16-10-45](https://user-images.githubusercontent.com/26769888/30909424-9fb9ac92-a39e-11e7-91f8-ae39fb5dbd18.png)

**Comment by ajitid** [comment]
Thanks! I also wanted to ask you to increase visibility of squiggles (of both errors and warnings). Actually they're quite hard to notice. Were they intentionally have less contrast?

**Comment by equinusocio** [comment]
@ajitid yes. At the moment we have no plan to increase the squiggles contrast. The Inactive tab text was just an issue of inconsistence.

**Comment by ajitid** [comment]
Okay. I don't have any that much issue with squiggles but I do find error squiggle to be not as visible as warning one.

![screenshot from 2017-09-28 20-28-50](https://user-images.githubusercontent.com/26769888/30974165-988dc07c-a48c-11e7-9847-7a3a7d5f55ad.png)
