### ISSUE TITLE
Disable active cursor background color

### ISSUE THREAD

**Issue by iamclaytonray** [equinusocio/vsc-material-theme#98]
I'm not sure how to disable this feature but if you take a look at the screenshot, maybe you'd be able to tell me the rule to throw into my settings. Basically, I don't want any background color for where my active cursor is. What rule would this be, if such a rule exists? (I'm using Palenight)

<img width="1134" alt="screen shot 2017-10-13 at 12 46 20 am" src="https://user-images.githubusercontent.com/16495816/31530762-9acd08dc-afb0-11e7-9847-efe4f74ec39a.png">

**Comment by iamclaytonray** [comment]
I, however, would still like highlighting for when I select lines. Here's a screenshot:

<img width="435" alt="screen shot 2017-10-13 at 12 52 21 am" src="https://user-images.githubusercontent.com/16495816/31530807-dd9a3676-afb0-11e7-951f-9be9afdb23be.png">

**Comment by equinusocio** [comment]
@iamclaytonray You can control this through VSC settings.
```json
// Controls how the editor should render the current line highlight, possibilities are 'none', 'gutter', 'line', and 'all'.
  "editor.renderLineHighlight": "line",
```
