### ISSUE TITLE
Add support for Operator Mono Italic

### ISSUE THREAD

**Issue by sAs59** [equinusocio/vsc-material-theme#99]
Please add support for Operator Mono Italic font. (react component props, import...from, classes, ...)

**Comment by equinusocio** [comment]
Can post a list of what you should like to see italic?

**Comment by equinusocio** [comment]
all of these will be italic:
```
keyword.control",
        "constant.other.color",
        "punctuation",
        "meta.tag",
        "punctuation.definition.tag",
        "punctuation.separator.inheritance.php",
        "punctuation.definition.tag.html",
        "punctuation.definition.tag.begin.html",
        "punctuation.definition.tag.end.html",
        "punctuation.section.embedded",
        "keyword.other.template",
        "keyword.other.substitution"
```

**Comment by BafS** [comment]
From the official [website](https://www.typography.com/blog/introducing-operator) it looks like that:

![](https://d31td5fkd89rr1.cloudfront.net/assets/images/blog/operator_ide2.png)

Basically comments, attributs and "this" (maybe "function" and "class" too, depend on the tastes).

Thanks in advance !
